### ISSUE TITLE
Schema mismatch for input column 'Structure': expected I4, got Key<U4, 0-1>

### ISSUE THREAD

**Issue by PraveenVerma17** [dotnet/machinelearning#1267] opened 2018-10-15 19:48 UTC
### Issue
Schema mismatch for input column 'Structure': expected I4, got Key<U4, 0-1>
Parameter name: inputSchema

### Source code / logs
 static void Main(string[] args)
        {
            Console.WriteLine("Machine Learning Code Started...");

            //Create a learning pipeline
            var pipeline = new LearningPipeline();

            //Load the data into the pipeline
            string filepath = "fruit_data.txt";
            pipeline.Add(new TextLoader(filepath).CreateFrom<FruitData>(useHeader: false, separator: ','));

            //Transform the data
            pipeline.Add(new Dictionarizer("Structure"));
            pipeline.Add(new Dictionarizer("Fruit"));
            Console.WriteLine("Transformation of data has been completed...");

            //Put all the data into vector
            pipeline.Add(new ColumnConcatenator("Features", "Weight", "Structure"));

            //add the classifier 
            pipeline.Add(new FastTreeBinaryClassifier());

            //Convert the label back to text

            //Train the model
            var model = pipeline.Train<FruitData, PredictedFruit>();

            Console.WriteLine("Training of the model has been completed");

        }

Here is the data i have:-

140,pulpi, orange
120,pulpi, orange
130,hard, apple
156,hard, apple
131,pulpi, orange
142,hard, apple
95,hard, apple

**Comment by PraveenVerma17** [comment] 2018-10-18 13:29
Can anyone from MS team provide me some guidance on above issue?

**Comment by GalOshri** [comment] 2018-10-18 16:34
I think the issue is:
`pipeline.Add(new Dictionarizer("Structure"));`

In this case, you want to use "Structure" as a categorical feature, so you should likely use the `CategoricalOneHotVectorizer` as shown in [this tutorial](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare). It might also be useful to read in the "Weight" as a float  if the feature concatenation does not work due to type mismatch.

**Comment by PraveenVerma17** [comment] 2018-10-20 06:14
Thanks GalOshri.


                //create a  pipleline and load the data
                var pipeline = new LearningPipeline();

                //load the data from the fruit data file
                string dataPath = "fruit_data.txt";
                pipeline.Add(new TextLoader(dataPath).CreateFrom<Fruit_Data>(separator: ',', useHeader: false));

                Console.WriteLine("Loading the data completed...");

                //Transform the data
                pipeline.Add(new ColumnCopier(("Fruit", "Label")));

                pipeline.Add(new CategoricalHashOneHotVectorizer("Structure"));
                pipeline.Add(new Dictionarizer("Label"));

                Console.WriteLine("Transformation of data completed...");

                // Puts all features into a vector
                pipeline.Add(new ColumnConcatenator("Features", "Weight", "Structure"));


                // Add a learning algorithm to the pipeline. 
                pipeline.Add(new StochasticDualCoordinateAscentClassifier());

                // Convert the Label back into original text (after converting to number in step 3)
                pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedFruit" });

                Console.WriteLine("Training a model started...");

                // Train your model based on the data set
                var model = pipeline.Train<Fruit_Data, Predicted_Fruit>();

                Console.WriteLine("Training a model completed...");

                //Now we need to send the test data to test the model
                var result = model.Predict(new Fruit_Data()
                {
                   Structure ="hard",
                   Weight =  132
                });

                Console.WriteLine($"Predicted fruit  - {result.PredictedFruits}");

Getting below error now:-
Machine learning Code Started...
Loading the data completed...
Transformation of data completed...
Training a model started...
Automatically adding a MinMax normalization transform, use 'norm=Warn' or 'norm=No' to turn this behavior off.
Using 2 threads to train.
Automatically choosing a check frequency of 2.
Auto-tuning parameters: maxIterations = 214284.
Auto-tuning parameters: L2 = 2.666688E-05.
Auto-tuning parameters: L1Threshold (L1/L2) = 1.
Using best model from iteration 1342.
Not training a calibrator because it is not needed.
Error Occured ! - System.InvalidOperationException: Column 'PredictedFruit' not found.
   at Microsoft.ML.Runtime.EntryPoints.FeatureCombiner.ConvertPredictedLabel(IHostEnvironment env, PredictedLabelInput input) - Exception has been thrown by the target of an invocation.

**Comment by GalOshri** [comment] 2018-10-20 19:04
Based on the error `Column 'PredictedFruit' not found`, there is a mismatch between the column names that the pipeline is outputting and the columns defined in the `Predicted_Fruit` class. Try changing the `"PredictedFruit"` in `[ColumnName("PredictedFruit")]` to `"PredictedLabel"`. 

Additionally, take a look at [this cookbook](https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-do-i-use-the-model-to-make-one-prediction) that helps show how to use the newer ML.NET APIs to make predictions.

**Comment by PraveenVerma17** [comment] 2018-10-20 20:02
Thanks Gal Oshri. This solved the error. 
So we need Label in input class and PredictedLabel in output class. these are mandatory.  We can concatenate same type of column but different type we need to change in vector type to concatenate. 
Now can build some actual application which is  exactly similar as above example i used.

**Comment by GalOshri** [comment] 2018-10-20 20:11
Yes, the Label in the input class is used to train the model in supervised learning problems. The PredictedLabel lets you access the model's prediction. There are other columns in the output that can be used as described [here](https://github.com/dotnet/machinelearning/issues/376#issuecomment-399282699). The new APIs make it easier to discover this and we are working to update the documentation.

Feel free to reach out if you encounter any issues in your application. I'll close this thread.

**Closed** 2018-10-20 20:11 UTC
