### ISSUE TITLE
model.LastTransformer doesn't exist

### ISSUE THREAD

**Issue by philiplai** [dotnet/machinelearning#4937] opened 2020-03-12 05:01 UTC
I was trying to implement Permutation Feature Importance (PFI) for Binary Classification.  But I was stuck on the following line of code.  This method simply doesn't exist.
// Extract the predictor.
var linearPredictor = model.LastTransformer;

I was following the example on https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.permutationfeatureimportanceextensions.permutationfeatureimportance?view=ml-dotnet

Any idea?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec45442-8e5f-a544-cc9a-58483a383513
* Version Independent ID: 040169f9-d169-cbbd-099e-f04a7a5a6b3f
* Content: [PermutationFeatureImportanceExtensions.PermutationFeatureImportance Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.permutationfeatureimportanceextensions.permutationfeatureimportance?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML/PermutationFeatureImportanceExtensions.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/PermutationFeatureImportanceExtensions.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by najeeb-kazmi** [comment] 2020-03-13 01:07
@philiplai can you share the code where you load the data, define the pipeline, and fit the model?

`LastTransformer` is a property of `EstimatorChain`. My best guess without looking at the code is that your model has only one estimator, and is not an `EstimatorChain`. If that is the case, your model will be of type `BinaryPredictionTransformer`, which you can directly pass to PFI instead of the `linearPredictor` in the example.

**Comment by artemiusgreat** [comment] 2020-03-13 05:53
A duplicate of this issue https://github.com/dotnet/machinelearning/issues/3976 
The problem is that model.Load by default returns incorrect type that doesn't have property LastTransformer, so you have to cast it to the right data type explicitly.

**Comment by antoniovs1029** [comment] 2020-03-13 07:25
For the record, I wouldn't think that issue #3976 is a duplicate of this issue here. @artemiusgreat is right in that `mlContext.Model.Load` always return an `ITransformer` ([link to docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.modeloperationscatalog.load?view=ml-dotnet)). Since `ITransformer` doesn't have a `.LastTransformer` property, then it needs to be casted to a `TransformerChain` as shown in the following sample:

https://github.com/dotnet/machinelearning/blob/290da8222d4ebcf5c9c4fa134d27151d4ee69364/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/PermutationFeatureImportanceLoadFromDisk.cs#L36-L41

That cast _must_ be done to access the `.LastTransformer`, that is by design, and it isn't a bug. On the other hand, issue #3976 was actually about that attempting to do that cast caused an exception, and so PRs #4262 and #4306 fixed this. The only reason #3976 is still open is because the issue specifically refers to using ML.NET on F#, and the fix made on those PRs haven't been tested on F#, only on C#.

As for the issue in here, I wouldn't know if the user who created the issue is trying to load a model (in which case, making the cast @artemiusgreat suggested might be enough), or if the user has a model with one transformer (as @najeeb-kazmi has suggested, in which case passing that predictor directly to PFI should be enough).

**Comment by najeeb-kazmi** [comment] 2020-03-18 16:51
Closing this issue. Please feel free to reopen if something remains unanswered.

**Closed by najeeb-kazmi** 2020-03-18 16:51 UTC
Labels: P3, question
