### ISSUE TITLE
Onnxruntime not working properly for netfx

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#2106] opened 2019-01-10 01:37 UTC
I am trying to run the test SimpleEndToEndOnnxConversionTest on netfx

I get this is as an error
```C#
[xUnit.net 00:00:08.31]     Microsoft.ML.Tests.OnnxConversionTest.SimpleEndToEndOnnxConversionTest [FAIL]
Failed   Microsoft.ML.Tests.OnnxConversionTest.SimpleEndToEndOnnxConversionTest
Error Message:
 System.DllNotFoundException : Unable to load DLL 'onnxruntime.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Stack Trace:
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtCreateSessionOptions()
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithMklDnnProvider()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)
   at Microsoft.ML.Transforms.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxUtils.cs:line 101
   at Microsoft.ML.Transforms.OnnxTransform..ctor(IHostEnvironment env, Arguments args, Byte[] modelBytes) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxTransform.cs:line 190
   at Microsoft.ML.Transforms.OnnxTransform..ctor(IHostEnvironment env, String modelFile, String[] inputColumns, String[] outputColumns, Nullable`1 gpuDeviceId, Boolean fallbackToCpu) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxTransform.cs:line 273
   at Microsoft.ML.Transforms.OnnxScoringEstimator..ctor(IHostEnvironment env, String modelFile, String[] inputColumns, String[] outputColumns, Nullable`1 gpuDeviceId, Boolean fallbackToCpu) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxTransform.cs:line 560
   at Microsoft.ML.Tests.OnnxConversionTest.SimpleEndToEndOnnxConversionTest() in C:\git\machinelearning\test\Microsoft.ML.Tests\OnnxConversionTest.cs:line 74
```

Although I looked at the output folder, I saw there was a dll named as Microsost.ML.OnnxRuntime.dll(not sure if it is similar to onnxruntime.dll)
I renamed it to onnxruntime.dll, and then I was getting

```C#
[xUnit.net 00:00:07.41]     Microsoft.ML.Tests.OnnxConversionTest.SimpleEndToEndOnnxConversionTest [FAIL]
Failed   Microsoft.ML.Tests.OnnxConversionTest.SimpleEndToEndOnnxConversionTest
Error Message:
 System.EntryPointNotFoundException : Unable to find an entry point named 'OrtCreateSessionOptions' in DLL 'onnxruntime.dll'.
Stack Trace:
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtCreateSessionOptions()
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithMklDnnProvider()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)
   at Microsoft.ML.Transforms.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxUtils.cs:line 101
   at Microsoft.ML.Transforms.OnnxTransform..ctor(IHostEnvironment env, Arguments args, Byte[] modelBytes) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxTransform.cs:line 190
   at Microsoft.ML.Transforms.OnnxTransform..ctor(IHostEnvironment env, String modelFile, String[] inputColumns, String[] outputColumns, Nullable`1 gpuDeviceId, Boolean fallbackToCpu) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxTransform.cs:line 273
   at Microsoft.ML.Transforms.OnnxScoringEstimator..ctor(IHostEnvironment env, String modelFile, String[] inputColumns, String[] outputColumns, Nullable`1 gpuDeviceId, Boolean fallbackToCpu) in C:\git\machinelearning\src\Microsoft.ML.OnnxTransform\OnnxTransform.cs:line 560
   at Microsoft.ML.Tests.OnnxConversionTest.SimpleEndToEndOnnxConversionTest() in C:\git\machinelearning\test\Microsoft.ML.Tests\OnnxConversionTest.cs:line 74
```

@eerhardt @danmosemsft @shauheen @TomFinley @jignparm

**Comment by shauheen** [comment] 2019-01-10 19:32
@jignparm can you please take a look.

**Comment by jignparm** [comment] 2019-01-13 17:52
Microsost.ML.OnnxRuntime.dll is not the same as  onnxruntime.dll. The first contains the .Net managed code whereas the second contains the native code (and is contained within the runtimes folder in the nuget). What version of .NetFramework are you using (4.6.1 or other?)

@eerhardt, the it seems like the properties file below does not copy the 'onnxruntime.dll' native file to the output folder. Would the logic be the same for different versions of .NetFramework?

https://github.com/Microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/Microsoft.ML.OnnxRuntime.props

**Comment by eerhardt** [comment] 2019-01-14 15:49
That `.props` file is only there to support when a project is using `packages.config`. See:

```xml
  <ItemGroup Condition="Exists('packages.config') OR
                        Exists('$(MSBuildProjectName).packages.config') OR
                        Exists('packages.$(MSBuildProjectName).config')">
```

We are using `PackageReference` in our .csproj, so this code doesn't kick in (by design). Instead, NuGet will automatically include the `runtimes\RID\native` files, if the RID is set correctly. 

It appears that the `RID`s are not lining up correctly. In our ML.NET tests we are using `win-x64` (i.e. any Windows x64 based machine):

https://github.com/dotnet/machinelearning/blob/master/test/Directory.Build.props#L9

But in the OnnxRuntime package, it is using `win10-x64` (i.e. Windows 10 x64 based machines). Thus, the tests aren't picking up these native assets because the test is saying it should run on any Windows machine. While these native assets say they only work on Windows 10.

I've had [conversations](https://github.com/Microsoft/onnxruntime/pull/127#discussion_r239846331) with @shahasad in the past on whether the OnnxRuntime package should change to use the `win-x64` RID. If it packaged the native assets in that folder, this would start working.

**Comment by jignparm** [comment] 2019-01-15 22:51
Fix added to Onnxruntime to update to Win-x64. Will be available in next release of the Nuget.

https://github.com/Microsoft/onnxruntime/blob/139abda393d8410e1c35469adfcc7d13d109a997/csharp/src/Microsoft.ML.OnnxRuntime/Microsoft.ML.OnnxRuntime.csproj#L47

**Comment by jignparm** [comment] 2019-01-31 22:38
Resolved via https://github.com/dotnet/machinelearning/pull/2085

**Closed by jignparm** 2019-01-31 22:38 UTC
Labels: bug
