### ISSUE TITLE
MLContext.BinaryClassification.Trainers does not resolve to a documentation topic in the API Reference.

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/machinelearning#2570] opened 2019-02-15 18:11 UTC
MLContext.BinaryClassification.Trainers does not resolve to a documentation topic in the API Reference.  It should. 

Given the following code: 
     Microsoft.ML.Trainers.SdcaBinaryTrainer train = mlContext.BinaryClassification.Trainers.StochasticDualCoordinateAscent(labelColumn: DefaultColumnNames.Label, featureColumn: DefaultColumnNames.Features);

How do we find and use the available set of Learners / Trainers via from the API Ref?       

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8468bfed-64e4-c462-085d-19c1cce3b627
* Version Independent ID: b4721a22-be85-9b1c-0914-fc591c3e9f28
* Content: [MLContext.BinaryClassification Property (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.mlcontext.binaryclassification?view=ml-dotnet#Microsoft_ML_MLContext_BinaryClassification)
* Content Source: [dotnet/xml/Microsoft.ML/MLContext.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/MLContext.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by shmoradims** [comment] 2019-02-15 22:22
There are two perspectives regarding this issue:

1) Should this work from a pure technical perspective? 
The answer is no, because `MLContext.BinaryClassification` is a property and you cannot extend the path on top of a property. You can only do it on a type. So the following searches will resolve:
* `MLContext.BinaryClassification` (full name: `Microsoft.ML.MLContext.BinaryClassification`)
* `BinaryClassificationCatalog.Trainers` (full name: `Microsoft.ML.BinaryClassificationCatalog.Trainers`)
But `MLContext.BinaryClassification.Trainers` is asking for a property of a property, which won't work.

Please see more similar examples from the rest of .net API in the second point below.

2) Should we make any changes to our naming to help users find all binary classification trainers?
We could do something. Randomly browsing through .net API reference, I found that whenever possible, a class-type property and the class-type itself have identical names. Here are some examples:
* [public ActivationContext ActivationContext { get; } ](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.activationcontext?view=netframework-4.7.2)
* [public Microsoft.AspNetCore.Mvc.ModelBinding.BindingSource BindingSource { get; }](https://docs.microsoft.com/en-us/dotnet/api/system.web.http.fromuriattribute.bindingsource?view=aspnetcore-2.2#System_Web_Http_FromUriAttribute_BindingSource)
* [public virtual System.CodeDom.Compiler.LanguageOptions LanguageOptions { get; }](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.languageoptions?view=netframework-4.7.2#System_CodeDom_Compiler_CodeDomProvider_LanguageOptions)

For top level classes, identical names seems to be the de facto rule. But for APIs that are deeper into the API class hierarchy, there are some exceptions. Below is one examples: 
* [public Microsoft.AspNetCore.Rewrite.RuleResult Result { get; set; }](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.rewrite.rewritecontext.result?view=aspnetcore-2.2#Microsoft_AspNetCore_Rewrite_RewriteContext_Result)

For our top-level catalog classes, we should be able to use identical property & property-type names similar to the rest of .net API. That requires the following renaming:
* `BinaryClassificationCatalog` -> `BinaryClassification`
* `public Microsoft.ML.BinaryClassificationCatalog BinaryClassification { get; }` ->
`public Microsoft.ML.BinaryClassification BinaryClassification { get; }`
* `BinaryClassificationCatalog.BinaryClassificationTrainers` -> `BinaryClassification.Trainers`
* `public Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers Trainers { get; }` -> `public Microsoft.ML.BinaryClassification.Trainers Trainers { get; }`

If we do that, the user can search for `BinaryClassification.Trainers` and find all the binary trainers as extension methods there (although we need to figure out why extension methods sometime show up in the documentation and sometime don't). The sameness of property names and the type names, could be beneficial to the user. 

@TomFinley @eerhardt @shauheen I leave it up to you to decide if this renaming would be worth the cost.

**Comment by JRAlexander** [comment] 2019-02-19 21:36
@dendeli-msft, would this be due to referencing internal types?

**Comment by shmoradims** [comment] 2019-03-27 18:48
Our trainer are nested classes and this issue was caused by a bug on docs engine that couldn't process nested classes. It was tracked down and resolved by the docs team.

It's tracked internally here: https://ceapex.visualstudio.com/Engineering/_workitems/edit/72220

**Comment by shmoradims** [comment] 2019-04-25 17:44
Fixed: https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.binaryclassificationcatalog.binaryclassificationtrainers?view=ml-dotnet&branch=smoke-test-preview

**Closed by shmoradims** 2019-04-25 17:44 UTC
Labels: documentation
