### ISSUE TITLE
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'CpuMathNative' 

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#1999] opened 2019-01-02 22:42 UTC
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### Issue

- **What did you do?** Followed tutorial: https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial

- **What happened?** Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'CpuMathNative' or one of its dependencies: The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
   at Microsoft.ML.Runtime.Internal.CpuMath.Thunk.SumSqU(Single* ps, Int32 c)
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearPredictor predictor, Int32 weightSetCount)
   at Microsoft.ML.Runtime.Learners.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Runtime.Training.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Runtime.Data.EstimatorChain`1.Fit(IDataView input)
   at myApp.Program.Main(String[] args) in C:\Users\jakeradzikowski\dev\iris\Program.cs:line 69
- **What did you expect?** Iris example to work.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by JakeRadMSFT** [comment] 2019-01-02 22:42
Related to #333

**Comment by JakeRadMSFT** [comment] 2019-01-02 22:46
Hey Crew,
Not sure if the tutorial is incomplete or if I'm missing an "obvious" pre-req. It looks like #333 was closed saying Visual C++ Redistributable 2017 might be needed? Should that be added to the tutorial? 

Can I get the dependency with a PackageReference?

**Comment by JakeRadMSFT** [comment] 2019-01-02 22:50
Installed Microsoft Visual C++ Redistributable for Visual Studio 2017  from  https://visualstudio.microsoft.com/downloads/. 

Direct Link: https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by Ivanidzo4ka** [comment] 2019-01-03 13:15
Looks like duplicate of https://github.com/dotnet/machinelearning/issues/1823

**Closed by Ivanidzo4ka** 2019-01-03 13:15 UTC

**Comment by JakeRadMSFT** [comment] 2019-01-08 01:14
Thanks! So it'll be resolved in 0.9
