### ISSUE TITLE
AUC is not defined when there is no positive class in the data (Parameter 'PosSample')

### ISSUE THREAD

**Issue by AnoojNair** [dotnet/machinelearning#5168] opened 2020-05-27 06:48 UTC
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

### AUC is not defined when there is no positive class in the data (Parameter 'PosSample')
![image](https://user-images.githubusercontent.com/8334797/82986574-3080e880-a04a-11ea-8cb3-d41fa3572a97.png)

I get this exception while doing an evaluation on the **AnomalyDetection** model. i am using the **CreditCardFraudDetection** sample and running it on my dataset. i have checked if my test dataset has both positive and negative classes and they are present.

![image](https://user-images.githubusercontent.com/8334797/82986627-4d1d2080-a04a-11ea-87cf-4cd4182e91cf.png)

![image](https://user-images.githubusercontent.com/8334797/82986658-5908e280-a04a-11ea-9315-50f93b0a8803.png)

Am i missing something?

**Comment by michaelgsharp** [comment] 2020-05-27 16:23
Is you dataset something you can share? Just from looking at the screenshots nothing looks wrong, but I can't see much. What is your model made up of?

**Comment by AnoojNair** [comment] 2020-05-27 20:58
Unfortunately, i can't share the dataset.  The model is a RandomizedPCA trainer. After the train test split, my training dataset and test dataset contains a new column called SamplingKeyColumn.Is that ok?

```C#
// Get all the feature column names (All except the Label and the IdPreservationColumn)
            string[] featureColumnNames = trainDataView.Schema.AsQueryable()
                .Select(column => column.Name)                               // Get all the column names
                .Where(name => name != nameof(TransactionObservation.Label)) // Do not include the Label column
                .Where(name => name != "IdPreservationColumn")               // Do not include the IdPreservationColumn/StratificationColumn
             .ToArray();


            // Create the data process pipeline
            IEstimator<ITransformer> dataProcessPipeline = mlContext.Transforms.Concatenate("Features", featureColumnNames)
                                                                               .Append(mlContext.Transforms.NormalizeLpNorm(outputColumnName: "NormalizedFeatures", inputColumnName: "Features"));

            // In Anomaly Detection, the learner assumes all training examples have label 0, as it only learns from normal examples.
            // If any of the training examples has label 1, it is recommended to use a Filter transform to filter them out before training:
            IDataView normalTrainDataView = mlContext.Data.FilterRowsByColumn(trainDataView, columnName: nameof(TransactionObservation.Label), lowerBound: 0, upperBound: 1); ;
            //(trainDataView, columnName: nameof(TransactionObservation.Label), lowerBound: 1, upperBound: 1);

            // (OPTIONAL) Peek data (such as 2 records) in training DataView after applying the ProcessPipeline's transformations into "Features" 
            ConsoleHelper.PeekDataViewInConsole(mlContext, normalTrainDataView, dataProcessPipeline, 2);
            ConsoleHelper.PeekVectorColumnDataInConsole(mlContext, "NormalizedFeatures", normalTrainDataView, dataProcessPipeline, 2);


            var options = new RandomizedPcaTrainer.Options
            {
                FeatureColumnName = "NormalizedFeatures",   // The name of the feature column. The column data must be a known-sized vector of Single.
                ExampleWeightColumnName = null,				// The name of the example weight column (optional). To use the weight column, the column data must be of type Single.
                Rank = 6,									// The number of components in the PCA.
                Oversampling = 20,							// Oversampling parameter for randomized PCA training.
                EnsureZeroMean = true,						// If enabled, data is centered to be zero mean.
                Seed = 1									// The seed for random number generation.
            };


            // Create an anomaly detector. Its underlying algorithm is randomized PCA.
            IEstimator<ITransformer> trainer = mlContext.AnomalyDetection.Trainers.RandomizedPca(options: options);

            EstimatorChain<ITransformer> trainingPipeline = dataProcessPipeline.Append(trainer);

            ConsoleHelper.ConsoleWriteHeader("=============== Training model ===============");

            TransformerChain<ITransformer> model = trainingPipeline.Fit(normalTrainDataView);

            ConsoleHelper.ConsoleWriteHeader("=============== End of training process ===============");

            return model;
```

**Comment by AnoojNair** [comment] 2020-05-28 05:26
Also,

My dataset has 7 columns, including the label. Should the rank(number of components) be 6? 

![image](https://user-images.githubusercontent.com/8334797/83102279-39d08a80-a108-11ea-807c-fcc122425ee6.png)

![image](https://user-images.githubusercontent.com/8334797/83102086-d8a8b700-a107-11ea-91d7-1f5968b7a6f3.png)

**Comment by michaelgsharp** [comment] 2020-05-28 21:28
This [documentation](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/pca-based-anomaly-detection), which is for Azure Machine Learning but the same principles apply, says:

> The decision of how many components to include is an important part of experiment design using PCA. General guidance is that you should not include the same number of PCA components as there are variables. Instead, you should start with some smaller number of components and increase them until some criteria is met.
> ...
> The best results are obtained when the number of output components is less than the number of feature columns available in the dataset.

If your dataset has 7 columns including the label, that means you have 6 features. According to that documentation you will get better results with a rank smaller than 6, so doing 5 is fine.

**Comment by michaelgsharp** [comment] 2020-05-28 21:36
The problem is coming from your call to:
```
mlContext.Data.FilterRowsByColumn(trainDataView, columnName: nameof(TransactionObservation.Label), lowerBound: 0, upperBound: 1);
```
The upper bound is an *exclusive* bound, so its not actually including the value `1`, giving you all the rows were the label is between 0 and .99999. If all your label values are either 0 or 1, then you are only getting the rows where label is 0, causing the `No positive class` error.

You need to change the `upperBound` value. If all your label values are either 0 or 1, then you can change the `upperBound` to be 2. If you have other values you may need to make the `upperBound` more restrictive. Fixing this `upperBound`, though, will resolve your issue.

I am going to close this ticket for now. If you change the `upperBound` and you still have issues please feel free to re-open the ticket.

Thanks!

**Closed by michaelgsharp** 2020-05-28 21:36 UTC
Labels: anomaly, bug, need info

**Comment by AnoojNair** [comment] 2020-05-29 08:37
Hi @michaelgsharp ,

Thanks for the response. The filtering is happening on the trainingdata, which for anomaly detection should only be 0(learning only from the normal samples).  I am going based on the comments from the code samples. 

```c#
            // In Anomaly Detection, the learner assumes all training examples have label 0, as it only learns from normal examples.
            // If any of the training examples has label 1, it is recommended to use a Filter transform to filter them out before training:
            IDataView normalTrainDataView = mlContext.Data.FilterRowsByColumn(trainDataView, columnName: nameof(TransactionObservation.Label), lowerBound: 0, upperBound: 1);
```

But the exception is happening on the evaluation of the test data(which does have both).

**Comment by anilindorkar** [comment] 2020-07-22 18:06
Make sure your Test and Training data must have true and false both kind of data, My Problem resolved once I included true and false, both kind of data in the Test and Training file/dataset.

**Comment by voges316** [comment] 2020-08-05 17:23
Encountered the same issue running anomaly detection on the credit card fraud dataset from Kaggle. Increasing the test/train split (from 20% to 50%) fixed the issue, and it appears the error is thrown when you run mlContext.AnomalyDetection.Evaluate and the number of Predicted Anomalies is zero. 

```
Number of positive alerts in dataset: 152, negative 85553
Number of PREDICTED positive alerts in dataset: 0, negative 85705

Transformed Prediction results
 
Show data in DataView: Showing 1 rows with the columns
######################################################
Row--> | V1:-1.3583541| V2:-1.3401631| V3:1.7732093| V4:0.3797796| V5:-0.50319815| V6:1.8004994| V7:0.79146093| V8:0.24767579| V9:-1.5146543| V10:0.20764287| V11:0.62450147| V12:0.066083685| V13:0.7172927| V14:-0.16594592| V15:2.345865| V16:-2.8900833| V17:1.1099694| V18:-0.12135931| V19:-2.261857| V20:0.5249797| V21:0.24799815| V22:0.7716794| V23:0.90941226| V24:-0.6892809| V25:-0.32764184| V26:-0.13909657| V27:-0.055352796| V28:-0.059751842| Amount:378.66| Label:False| Features:Dense vector of size 29| NormalizedFeatures:Dense vector of size 29| PredictedLabel:False| Score:NaN| labelAsFloat:0

Unhandled exception. System.ArgumentOutOfRangeException: AUC is not defined when there is no positive class in the data (Parameter 'PosSample')

```
