### ISSUE TITLE
[Image Classification DNN based] Cannot use GPU with NuGet 0.16.0-preview2

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#4325] opened 2019-10-11 21:14 UTC
The NuGet package 'Microsoft.ML.Dnn 0.16.0-preview2' is including a dependency on the CPU-based `SciSharp.TensorFlow.Redist` package: 

![image](https://user-images.githubusercontent.com/1712635/66684962-1a93f400-ec30-11e9-96a2-fdb675fa9e20.png)

Therefore the user cannot reference and use the `SciSharp.TensorFlow.Redist-Windows-GPU` package because the CPU version has preference, afaik.  

The NuGet package `Microsoft.ML.Dnn 0.16.0-preview2` must not reference any of those, so depending on what SciSharp TensorFlow redist (CPU vs. GPU) the user is referencing from his code, it'll use CPU or GPU.

I know this is being fixed in the ML.NET source code repo with this PR after my heads-up:
https://github.com/dotnet/machinelearning/pull/4324

**But users mostly use the NuGet packages so we probably need to publish a new fix-patch-release for that package like the following?**:

`Microsoft.ML.Dnn 0.16.1-preview2` ?

Any other solution so users can try Image Classification with GPU when using the NuGet packages?

**Comment by codemzs** [comment] 2019-10-13 23:37
@CESARDELATORRE myself and @eerhardt spoke about this and we feel there might be a workaround that people can use. Basically you also add GPU TF redist and then manually go delete the binaries for CPU. @bpstark was going to verify this works so he can update this thread. I also feel we should wait until someone hits this issue before we consider a patch release ... I want to see how many people that are actually trying this preview have GPUs.

**Comment by bpstark** [comment] 2019-10-14 18:45
Tested work-around, and confirmed we can run with GPU TF for now steps for work-around:

1. Add the TF GPU dependency to your project just as would be required originally.
2. Locate your Nuget package cache it should be something like C:\Users\<your_user_name>\.nuget\packages
3. Copy <package_cache>\scisharp.tensorflow.redist\1.14.0\runtimes\win-x64\native\tensorflow.dll to your desktop or somewhere for safe keeping
4. Overwrite the previously mentioned DLL by copying the GPU version from <package_cache>\scisharp.tensorflow.redist-windows-gpu\1.14.0\runtimes\win-x64\native\tensorflow.dll to <package_cache>\scisharp.tensorflow.redist\1.14.0\runtimes\win-x64\native\tensorflow.dll

Optional: If you want to reset back to the CPU version move the DLL you had saved to the desktop back to the original location as specified in step 3

**Comment by CESARDELATORRE** [comment] 2019-10-16 23:55
Reopening as that workaround is not working for me. I might be missing something else?

Initially, I had my sample working properly with CPU, then I followed the procedure, and when I try to run it, I get this exception:

```
Unhandled Exception: System.FormatException: Tensorflow exception triggered while loading model. ---> System.DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor()
   at Microsoft.ML.Transforms.Dnn.DnnUtils.LoadMetaGraph(String path)
   at Microsoft.ML.Transforms.Dnn.DnnUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   --- End of inner exception stack trace ---
   at Microsoft.ML.Transforms.Dnn.DnnUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.DnnCatalog.ImageClassification(ModelOperationsCatalog catalog, String featuresColumnName, String labelColumnName, String scoreColumnName, String predictedLabelColumnName, Architecture arch, Int32 epoch, Int32 batchSize, Single learningRate, Boolean disableEarlyStopping, EarlyStopping earlyStopping, ImageClassificationMetricsCallback metricsCallback, Int32 statisticFrequency, DnnFramework framework, String modelSavePath, String finalModelPrefix, IDataView validationSet, Boolean testOnTrainSet, Boolean reuseTrainSetBottleneckCachedValues, Boolean reuseValidationSetBottleneckCachedValues, String trainSetBottleneckCachedValuesFilePath, String validationSetBottleneckCachedValuesFilePath)
   at ImageClassification.Train.Program.Main(String[] args) in D:\GitRepos\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ImageClassification_Training\ImageClassification.Train\Program.cs:line 56

C:\Program Files\dotnet\dotnet.exe (process 16404) exited with code -532462766.
```
Am I missing any additional step not provided in the procedure above?

**Comment by codemzs** [comment] 2019-10-17 18:29
@CESARDELATORRE it is because you had CUDA 10.1 installed but once you reverted back to 10.0 you were able to run on GPU. Closing this issue. Feel free to add more details if needed.

**Closed by codemzs** 2019-10-17 18:29 UTC
