### ISSUE TITLE
Update broken documentation code

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#2054] opened 2019-01-07 17:02 UTC
For example: https://github.com/dotnet/machinelearning/blob/80f5720438d544b1c9cf019a889479d8e67d5837/docs/code/SchemaComprehension.md.

Related to #2039 .

**Comment by zeahmed** [comment] 2019-01-10 00:41
@yaeldekel, It seems like duplicate of #2039. Do you want to keep it? Can you please add more detail if its not duplicate? Thanks!

**Closed** 2019-06-30 09:04 UTC
Labels: bug, need info
