### ISSUE TITLE
Add ability to retrieve AutoML trainer parameters

### ISSUE THREAD

**Issue by evo11x** [dotnet/machinelearning#5774] opened 2021-04-28 23:09 UTC
Is there a way to get the AutoML trainer parameters?
Because I need to train over 100 different datasets/models and I cannot run AutoML on each one of them, it takes too long.

**Comment by JakeRadMSFT** [comment] 2021-05-05 22:40
@evo11x Can you tell us more about your scenario? Which parameters would you need?

**Comment by evo11x** [comment] 2021-05-06 12:25
Hi,
   After I run the experiment for a few minutes, I get the best model with accuracy of 0.99, let's say FastForestOva
   And I want to have the trainer parameters for FastForestOva to manually create the same model, because if I create that model with the default parameters I get an accuracy of only 0.45

**Comment by Leuzi** [comment] 2021-05-12 14:04
Same here, the trainer could expose the parameters in order to reproduce the same model using the proper ML.Net trainer because at the end the options for those parameters are hidden since are not in the metrics. Also useful for tracking the result of experiment and track not only the metrics of an experiment but also the parameters used to obtain those metrics.

**Comment by xenoverse-us** [comment] 2022-01-22 20:21
@evo11x @Leuzi I had a similar need and found out that you can save the model from AutoML then load it and use reflection to get those parameters, not the ideal solution but can be done until those are exposed via public accessors.

**Comment by luisquintanilla** [comment] 2022-07-21 20:00
Thanks everyone for the discussion and feedback. We've recently updated our AutoML implementation based on FLAML which should address some of the comments mentioned here. 

For more information, see [blog post](https://devblogs.microsoft.com/dotnet/whats-new-with-mldotnet-automl/#automl-updates) and [sample notebook](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb).

Closing this issue.

**Closed by luisquintanilla** 2022-07-21 20:00 UTC
Labels: enhancement, AutoML.NET, P2
