### ISSUE TITLE
Using "nameof" in "outputColumnName" of "MapKeyToValue"

### ISSUE THREAD

**Issue by Ellyster** [dotnet/machinelearning#5264] opened 2020-06-29 14:15 UTC
### System information

- **OS version/distro**: Windows 10 Enterprise
- **.NET Version (eg., dotnet --info)**: .NET Core 3.1

### Issue
- **What did you do?**
Adapted the Iris as a canary model for our company internal ML platform based on ML.Net.

- **What happened?**
Using to `nameof(IrisModelOutput.Species)`  select the output column name doesn't work.

```cs
public class IrisModelOutput
    {
        [ColumnName("PredictedLabel")]
        public string Species { get; set; }

        public float[] Score { get; set; }
    }
```

If the prediction result DTO `Species` is annotated with `[ColumnName("PredictedLabel")]` if gives an error; if it isn't annotated, it comes empty in the prediction.

- **What did you expect?**
That the predicted species is mapped back to `Species`.

### Source code / logs
In this pipeline's `MapKeyToValue` doesn't work as expected:
```cs
Pipeline = MlContext.Transforms.Concatenate(outputColumnName: "Features", inputColumnNames: new[]
                {
                    nameof(IrisModelInput.SepalLength),
                    nameof(IrisModelInput.SepalWidth),
                    nameof(IrisModelInput.PetalLength),
                    nameof(IrisModelInput.PetalWidth)
                })
                .Append(MlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "Label", inputColumnName: nameof(IrisModelInput.Species)))
                .Append(MlContext.MulticlassClassification.Trainers.SdcaNonCalibrated(labelColumnName: "Label", featureColumnName: "Features"))
                .Append(MlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: nameof(IrisModelOutput.Species), inputColumnName: "Label"));
```
But using the following alternative sintaxis for the last append works correctly:
```csharp
.Append(MlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
```

**Comment by antoniovs1029** [comment] 2020-06-29 19:35
Hi, @Ellyster . Bellow I'll describe what I think is happening. But I'm still not sure if I understand your use case. If my comments don't work for you, it would be very helpful if you could provide a .zip with your application code, and some sample dataset to actually run the code. If that's not possible, a simplified repro that also shows your problem would help. If still not possible, sharing with us the stacktrace that you get when using the `[ColumnName]` attribute, and a screen capture of the output when you use (or not) the last `.Append()` you've mention, would be helpful as well.

### Solution
If I'm understanding your case correctly, I believe that using the last `Append()` you've mentioned:
```C#
// "Option A"
.Append(MlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
```

_Should_ work whether if you use:
```C#
        [ColumnName("PredictedLabel")]
        public string Species { get; set; }
```
or
```C#
        public string PredictedLabel { get; set; } // instead of calling it "Species"
```

This **is** expected behavior.

It should also work in both cases if you used:
```C#
// "Option B"
.Append(MlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel", "PredictedLabel"));
```

But using:
```C#
// "Option C"
.Append(MlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: nameof(IrisModelOutput.Species), inputColumnName: "Label"));
```
**isn't** expected to work in your case.

So when you say that Option A "works correctly", that's expected. So I'm not entirely sure of what is the issue you're reporting, if Option A already works for you? Is your question why Option A works, but Option C doesn't?

### Why Option A works, and Option C doesn't
Again, if I'm understanding your case correctly, the reason Option A works and Option C doesn't is as follows:

First, Option A and Option C aren't equivalent. Option A and Option B above _are_ equivalent, but Option C would be equivalent to:
```C#
// "Option D"
 .Append(MlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: "Species", inputColumnName: "Label"));
```

which is very different from Option A and Option B. So Option C and D are actually doing something completely different.

What option A and B do is take the "PredictedLabel" key column created by your `SdcaNonCalibrated` trainer, then apply a MapKeyToValue transform to it to create a new string column which will also be called "PredictedLabel". In ML.NET when a new column is created with the same name as a previously existing column, the new column "hides" the previous one. So the new "PredictedLabel" containing strings will hide the previous "PredictedLabel" column which contained keys. Then, when using this on your scenario, it would work with your `IrisModelOutput` class, because the `[ColumnName("PredictedLabel")]` attribute would map the "PredictedLabel" column into your `string Species` field.

What option C and D do is to take the "Label" column that was on your input, and apply a MapKeyToValue transform to it to create a new string column which will be called "Species" (i.e. `nameof(IrisModelOutput.Species)`) So in this case, "Species" won't have the strings of the predictions, it will actually have the strings of your input Label column. Also, I would expect your `SdcaNonCalibrated` trainer to produce a "PredictedLabel" key column, which then will be mapped by your `[ColumnName("PredictedLabel")]` attribute to the `string Species` field... but, since the "PredictedLabel" column is of type key, and the `Species` field is of type string, I'd expect a type mismatch exception to be thrown (which is probably the error you're getting). So, in short, there are several steps where "Option C" would fail and/or give unexpected results for your use case, and "Option A" was actually the correct way of getting the desired results.

Finally, I'd like to mention a couple of things that might need to be clarified:
1. I think the `SdcaNonCalibrated` trainer will always output its prediction into a column called "PredictedLabel". I believe this is a default, and it can't be changed by the user.
2. I don't think the `[ColumnName("PredictedLabel")]` is meant to change the name of the field, so `nameof(IrisModelOutput.Species)` is still "Species". What the `ColumnName` attribute is used for is to map values from C# fields to ML.NET columns, or from ML.NET columns to C# fields. In your case, when using the attribute, and the `IrisModelOutput` as the output class of a ML.NET prediction, then what the attribute will do is to automatically map the "PredictedLabel" column found on your ML.NET output data view into the `Species` field of your `IrisModelOutput` class: it _doesn't_ rename the `Species` field itself.

**Comment by Ellyster** [comment] 2020-07-01 15:28
Then it was probably our missunderstanding on how the SdcaNonCalibrated trainer works based on this example:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_Iris

´´´cs
var trainer = mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(labelColumnName: "KeyColumn", featureColumnName: "Features")
            .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: nameof(IrisData.Label) , inputColumnName: "KeyColumn"));
´´´

As you correctly point, it seems that we didn't properly understand that ´PredictedLabel´ was a column created by default by the trainer to place the result, and that it was being update/replaced later when the ´MapKeyToValue´ is applyed. We though, based on the example above, that the prediction result was placed into the same column that you train with, in our case ´Label´. And that was we were trying to map back form there.

What we wanted to then, was this:
´´´cs
Pipeline = MlContext.Transforms.Concatenate(outputColumnName: "Features", inputColumnNames: new[]
                {
                    nameof(IrisModelInput.SepalLength),
                    nameof(IrisModelInput.SepalWidth),
                    nameof(IrisModelInput.PetalLength),
                    nameof(IrisModelInput.PetalWidth)
                })
                .Append(MlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "Label", inputColumnName: nameof(IrisModelInput.Species)))
                .Append(MlContext.MulticlassClassification.Trainers.SdcaNonCalibrated(labelColumnName: "Label", featureColumnName: "Features"))
                .Append(MlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: nameof(IrisModelOutput.Species), inputColumnName: "PredictedLabel"));
´´´

Thanks 💯 for clarifying that for us.

**Comment by antoniovs1029** [comment] 2020-07-01 20:14
Hi, @Ellyster . I'm glad to hear your problem is solved. I'll close this issue now.

The sample you point to is indeed confusing in the way it's reusing the Label column. I'll open and issue on that repository so that changing this is considered. Thanks 😄

**Closed by antoniovs1029** 2020-07-01 20:14 UTC
Labels: P3, question

**Comment by waelhosn** [comment] 2022-02-22 16:18
I am facing an issue with MlContext.MulticlassClassification.PermutationFeatureImportance. The issue is that if my trainer has a conversion appended to the pipeline such as the one found below it will not work. `.Append(MlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: nameof(IrisModelOutput.Species), inputColumnName: "PredictedLabel"));`

So in order to fix this issue I had to create a temporary ML context and add a trainer without the conversion MapKeyToValue in order to get the feature importance to work. I believe this issue could be fixed if we have access to the all the transformers appended to the pipeline rather than having access only to the LastTransformer property, which is in my case the MapKeyToValue.
