### ISSUE TITLE
Update to latest LightGBM version

### ISSUE THREAD

**Issue by KyGurasz** [dotnet/machinelearning#6352] opened 2022-10-05 06:29 UTC
The current version in use with ML.net seems to be 2.3.1, which is from November 2019.  An updated version would bring functionality more in line to what we see in other environments. Also, see issue [#6296](https://github.com/dotnet/machinelearning/issues/6296).

**Comment by luisquintanilla** [comment] 2022-10-07 16:27
Hi @KyGurasz 

Thanks for this issue. In an effort to consolidate requests, I'm closing it as a duplicate of #5447.

**Closed by luisquintanilla** 2022-10-07 16:27 UTC
Labels: enhancement, untriaged
