### ISSUE TITLE
SequencePool.GetCore slower on netcoreapp3.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#2293] opened 2019-01-28 23:46 UTC
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Benchmarks/Text/MultiClassClassification.cs#L122 

Benchmark is slower on netcoreapp3.0. On investigation, I find out the major culprit for the regression is the function below

```C#
// Returns the ID of the requested sequence, or -1 if it is not found.
private int GetCore(uint[] sequence, int min, int lim, out uint hash)
{
    AssertValid();
    Contracts.Assert(0 <= min && min <= lim && lim <= Utils.Size(sequence));

    hash = Hashing.HashSequence(sequence, min, lim);

    for (int idCur = GetFirstIdInBucket(hash); idCur >= 0; idCur = _next[idCur])
    {
        Contracts.Assert(0 <= idCur && idCur < _idLim);
        if (_hash[idCur] != hash)
            continue;

        var ibCur = _start[idCur];
        var ibLim = _start[idCur + 1];
        for (int i = min; ; i++)
        {
            Contracts.Assert(ibCur <= ibLim);
            if (i >= lim)
            {
                // Need to make sure that we have reached the end of the sequence in the pool at the
                // same time that we reached the end of sequence.
                if (ibCur == ibLim)
                    return idCur;
                break;
            }
            if (ibCur >= ibLim)
                break;
            uint decoded;
            var success = TryDecodeOne(_bytes, ref ibCur, _start[idCur + 1], out decoded);
            Contracts.Assert(success);
            if (sequence[i] != decoded)
                break;
        }
    }
    return -1;
}
```

The exclusive time for this function on netcore2.1 is areound 689ms where as on netcoreapp3.0 it takes around 824ms

The function is defined here https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Utils/SequencePool.cs#L151

I was not able to find any reason behind this regression. cc @eerhardt @danmosemsft @jkotas

**Comment by jkotas** [comment] 2019-01-29 00:04
> I was not able to find any reason behind this regression.

@Anipik What have you done to try to find the reason behind this regression?

**Comment by Anipik** [comment] 2019-01-29 00:21
I just did an analysis with the perfview which showed that all the functions that are being called from GetCore i.e. TryDecodeOne and HashSequence are taking the similar time on both the platforms(2.1 and 3.0). From this I concluded that regression is in this function(maybe in the codegen) and not in callees.

I  tried enabling the tiered jitting for this benchmark. I increased the warmup iterations to more than 30. But the numbers were still same. so the regression was not caused due to tiered jitting not being enabled.

I am still trying to separately write a benchmark for this function to confirm the regression. @jkotas anything else i can try to get more info about the regression ?

**Comment by jkotas** [comment] 2019-01-29 01:14
Look at the native code before and after. Benchmark.NET has support to make it easy: https://adamsitnik.com/Disassembly-Diagnoser/ . If you are not able to make heads and tails of the differences, save the disassembly before/after as [gist](https://gist.github.com/) and share the link here so that others can take a look and route it accordingly.

**Comment by Anipik** [comment] 2019-01-31 21:55
Before https://gist.github.com/Anipik/b18c4f874b8ba2004fe2193d7f029f36
after https://gist.github.com/Anipik/7d4f846213f46a8a5d927bd13d41de9c

@jkotas can you help in making sense of this assembly code ?

**Comment by jkotas** [comment] 2019-02-01 02:34
The assembly code needs to be for the `GetCore` method that you have identified as the source of regression. What you have attached does not look like the assembly code for the `GetCore` method.

**Comment by luisquintanilla** [comment] 2022-07-21 19:50
Thanks all for the feedback. Closing this issue since it references out of support .NET versions. If this continues to be an issue on newer / supported versions of .NET, please feel free to open another issue.

**Closed by luisquintanilla** 2022-07-21 19:50 UTC
Labels: Build, P3
