### ISSUE TITLE
SVM IndexOutOfRangeException

### ISSUE THREAD

**Issue by egmkang** [dotnet/machinelearning#5394] opened 2020-09-12 12:17 UTC
### System information

- CentOS 7.x(kernel 3.10.0-514.26.2.el7.x86_64)
- .net core 2.1

### Issue

i use SVM to impl a classifier to test a short input text is AD. recently it throw Exception occasionally (both ML.NET 1.2 and 1.5.1).

### Source code / logs

```
Exception:System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.ML.Internal.Utilities.Utils.CopyTo[T](List`1 src, Span`1 dst, Nullable`1 count)
   at Microsoft.ML.Transforms.Text.WordTokenizingTransformer.Mapper.<>c__DisplayClass8_0.<MakeGetterOne>b__0(VBuffer`1& dst)
   at Microsoft.ML.Transforms.ValueToKeyMappingTransformer.BoundTermMap.Base`1.<>c__DisplayClass3_0.<GetMappingGetter>b__1(VBuffer`1& dst)
   at Microsoft.ML.Transforms.Text.NgramExtractingTransformer.Mapper.<>c__DisplayClass11_0.<MakeGetter>b__2(VBuffer`1& dst)
   at Microsoft.ML.Transforms.LpNormNormalizingTransformer.Mapper.<>c__DisplayClass8_0.<MakeGetter>b__5(VBuffer`1& dst)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper.BoundColumn.<>c__DisplayClass20_0`1.<MakeGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.SchemaBindablePredictorWrapperBase.<>c__DisplayClass19_0`2.<GetValueGetter>b__0(TDst& dst)
   at Microsoft.ML.Data.PredictedLabelScorerBase.EnsureCachedPosition[TScore](Int64& cachedPosition, TScore& score, DataViewRow boundRow, ValueGetter`1 scoreGetter)
   at Microsoft.ML.Data.BinaryClassifierScorer.<>c__DisplayClass15_0.<GetPredictedLabelGetter>b__0(Single& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass10_0`1.<CreateDirectSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
```

**Comment by harishsk** [comment] 2020-09-14 20:12
Hi @egmkang 
Can you please share some sample code and data for us to investigate this issue further?
thanks

**Comment by egmkang** [comment] 2020-09-15 03:20
@harishsk 

It is not easy to reproduce the problem, it takes a long time to run before it appears.

**Comment by harishsk** [comment] 2020-09-15 04:37
From the call stack, it doesn't appear to be anything to do with SVM. But there seems to be an index error while tokenizing some text. 

It is going to be difficult for us to investigate without a reproducible environment we can debug. Can you please share some details of your pipeline and/or scoring code? I am not sure how much it will help, but I can see if there are some hints there.

The other thing to try is also that, since ML.NET is open source, you can debug it yourself. Either with public symbols or by building the binaries yourself. Let me know if either of those cases sound like something you want to try and you would like some help with either of those.

**Comment by antoniovs1029** [comment] 2020-09-21 22:43
Hi, @egmkang . As mentioned by @harishsk , we can't look further into this if you are not able to share your dataset and code. I'll also want to ask how long does it take to reach that error? and if it's a consistent error (i.e. if every time you try to run your code the error happens)? Also, how big is your dataset (number of rows, and memory size)?

Also, as he mentioned, it seems it would be a problem with WordTokenizer, and not with SVM. It seems the error is thrown in here when trying to do the `.CopyTo()` call:

https://github.com/dotnet/machinelearning/blob/4960f9de83351b25874e58d1ca504c9a32aa1112/src/Microsoft.ML.Transforms/Text/WordTokenizing.cs#L263-L269

Just from looking at the code I can't find any issue with it. It seems the exception you're getting would happen only if the `terms` List has more elements than the ones `editor.Values` can have. But in the `VBufferEditor.Create(ref dst, terms.Count)` step, `editor.Values` array is actually resized to be the same size as `terms.Count`. Resizing the array occurs here:

https://github.com/dotnet/machinelearning/blob/4960f9de83351b25874e58d1ca504c9a32aa1112/src/Microsoft.ML.DataView/VBuffer.cs#L426-L430

Notice that the `values` array is going to be resized up to the `maxCapacity` value (which in this case would be `ArrayUtils.ArrayMaxSize = 0X7FEFFFFF`). So the only explanation I can think of so far for your exception is that the `terms` List has over 0X7FEFFFFF elements (which is over 2,000 million terms), and so the `editor.Values` array will only be resized to 0x7FEFFFFF, without throwing and error, but then the code throws when trying to copy all of `terms` into `editor.Values`.

On this context, the elements of `terms` are the tokenized terms after applying the WordTokenization to any given row of your dataset. So I wonder: what separators are you using for the WordTokenizer? Do you have any row on your dataset which would result on a list of over 2 thousand million tokens?

**Comment by egmkang** [comment] 2020-09-22 02:46
only a few tokens in my dataset, about 3000 lines.
one line has less than 10 tokens, separated by space.

**Comment by antoniovs1029** [comment] 2020-09-22 17:18
1. How long does it take to train?
2. Is the error thrown during training or inferencing?
3. Whenever you run your code you hit this issue with the same stack trace? Or does it happen only occasionally?
4. Please try having a pipeline only with the WordTokenizer and see if that reproduces the error. Since your dataset is small, I'd hope this train much faster.

**Comment by egmkang** [comment] 2020-09-23 03:00
1. training is very fast, about 10 seconds
2. no
3. occasionally. after server runs for few days, the program throw exception frequently.
4. i will have a try.

**Comment by antoniovs1029** [comment] 2020-09-30 21:39
I will close this issue, since we're unable to further investigate without a repro. Please, feel free to reopen whenever you're able to provide a repro. Thanks!

**Closed by antoniovs1029** 2020-09-30 21:39 UTC
Labels: Awaiting User Input
