### ISSUE TITLE
System.AccessViolationException' occurred in TensorFlow.NET.dll when calling predictionEngine.Predict()

### ISSUE THREAD

**Issue by hexate** [dotnet/machinelearning#5792] opened 2021-05-12 04:25 UTC
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Issue

- **What did you do?**
Trying to create a prediction engine and then calling Predict() after loading a tensorflow model. The error is thrown when trying to call Predict().

Latest nugets are referenced:
Microsoft.ML - 1.5.5
Microsoft.ML.TensorFlow - 1.5.5
TensorFlow.NET - 0.40.1

- **What happened?**

Encounter this error:

An unhandled exception of type 'System.AccessViolationException' occurred in TensorFlow.NET.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

- **What did you expect?**
No error. Ability to call Predict()

### Source code / logs

x64 is selected for building.

`
TensorFlowModel tensorFlowModel = mlContext.Model.LoadTensorFlowModel(modelLocation);

IEstimator<ITransformer> pipeline = tensorFlowModel.ScoreTensorFlowModel("sequential_1/dense_1/BiasAdd", "inputs", false)
    .Append(mlContext.Transforms.CopyColumns("Prediction", "sequential_1/dense_1/BiasAdd"));

var engine = mlContext.Model.CreatePredictionEngine<TensorData, PricePrediction>(model);
var prediction = engine.Predict(data); // error thrown on this line
`

**Comment by michaelgsharp** [comment] 2021-06-03 22:13
What version of tensorflow was used to create the model you are loading?

**Comment by afust003** [comment] 2021-07-20 15:09
Running into a similar issue, any updates on this?

**Comment by afust003** [comment] 2021-07-20 17:20
> Running into a similar issue, any updates on this?

Solution suggestion: We has a similar issue loading a custom TensorFlow "frozen_model" .pb file.
The problem was that one of the "input" elements was an float[] decorated with Vector(1) but the array was being initialized to an array of 0 elements via new float[] (for testing purposes) and we were receiving the above-mentioned AccessViolationException. I believe this to be the root cause of our problem. Hope this helps.

**Comment by michaelgsharp** [comment] 2021-07-20 19:47
So the issue was resolved when you fixed the issue with your input then?

**Comment by afust003** [comment] 2021-07-20 22:07
> So the issue was resolved when you fixed the issue with your input then?

Yes @michaelgsharp. We are using TensorFlow 2.x. I wasn't the original issue creator but it's been opened for over 1 month. We ran into this issue yesterday and were able to resolve it within ~4 hours of trial/error.

**Comment by michaelgsharp** [comment] 2021-07-21 00:58
Well I'm going to close this as resolved then as the root cause of the problem has been figured out.

**Closed by michaelgsharp** 2021-07-21 00:58 UTC
Labels: P3, image, question
