### ISSUE TITLE
broken links in documentation search results

### ISSUE THREAD

**Issue by Dmitry-A** [dotnet/machinelearning#2776] opened 2019-02-27 22:56 UTC
Go to 
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml?view=ml-dotnet&branch=smoke-test-preview
Type IEstimator in the search box
A few search results appear, first one being:
Microsoft.ML.Core.Data.IEstimator<TTransformer> Interface
Linking to https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.core.data.iestimator-1?view=ml-dotnet

This link goes to 404

**Comment by TomFinley** [comment] 2019-02-27 23:31
Thank you @Dmitry-A!

That's kind of weird. It's almost as if the search index was constructed over code built *before* #2529 was checked in (this being about two weeks ago), but the actual documentation pages (including namespace names) were taken from after it was checked in. I wonder if @JRAlexander has any thoughts on this, since he is AFAIK our documentation expert.

It should of course [link to this](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.iestimator-1?view=ml-dotnet&branch=smoke-test-preview).

Maybe the smoke test infrastructure is incomplete, and just links to the existing docs (which would of course be pre-#2529)? I could easily imagine this being a deliberate design limitation of the smoke-testing, but I'd feel better knowing for sure.

**Comment by JRAlexander** [comment] 2019-02-28 00:12
Index is on prod only, not review. Reference docs created since 0.10.0 launch won’t display when you search in the left hand navbox until the review docs are pushed to live after 0.11.0 launches and then reindexed.

You can access new content directly, it just isn't indexed yet.

**Comment by JRAlexander** [comment] 2019-02-28 00:38
@Dmitry-A , @TomFinley, @shauheen It shows up here: https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.iestimator-1?view=ml-dotnet&branch=smoke-test-preview

**Comment by JRAlexander** [comment] 2019-02-28 00:41
Looks like it's in the Microsoft.ML namespace. https://github.com/dotnet/machinelearning/blob/b1801a8a6b6463ec5f6fb576ca279343e7cfaebb/src/Microsoft.ML.Core/Data/IEstimator.cs#L11

**Comment by TomFinley** [comment] 2019-02-28 01:24
Yes, I see, thank you @JRAlexander. Good to know this is deliberate and working as intended.

(We are in the process of cleaning up our namespaces. `Microsoft.ML.Core.Data` is hardly an appropriate place for something as central as `IEstimator`!!)

Should we close @Dmitry-A?

**Comment by Dmitry-A** [comment] 2019-02-28 02:15
> Yes, I see, thank you @JRAlexander. Good to know this is deliberate and working as intended.
> (We are in the process of cleaning up our namespaces. Microsoft.ML.Core.Data is hardly an appropriate place for something as central as IEstimator!!)
> Should we close @Dmitry-A?

Sure, as long as this won't show up in release, all good.

**Comment by Dmitry-A** [comment] 2019-02-28 02:16
By design

**Closed** 2019-02-28 02:16 UTC
Labels: Bug Bash, documentation
