### ISSUE TITLE
DataView.GetColumn: Multiple columns with same name but different type

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning#6332] opened 2022-09-20 06:29 UTC
**Is your feature request related to a problem? Please describe.**
I am running model.Transform.

Then, I am would like to get the original field "Quote" with type string.
I would expect the following to work, but it gives an exception about wrong type:
`IDataView predictions= model.Transform(myDataFrame);
var quotes = predictions.GetColumn<string>("Quotes").ToList();`

The problem seems to be transforms (Micorsoft.ML.AutoML in 1.6.0) has created transforms to different types.
![image](https://user-images.githubusercontent.com/26261427/191181885-98105788-c6f7-4da9-b46e-b0cfce1f0c7b.png)

`'Cannot map column (name: Quote, type: Vector<Single, 2>) in data to the user-defined type, System.String. Arg_ParamName_Name'`

**Describe the solution you'd like**
GetColumn should try to find column with the specified type <string> if multiple columns with the same name exists.

**Describe alternatives you've considered**
I have not yet solved this issue.

 I suppose my solution will be :
1) get the values before Transform()
2) looping through all columns and checking type and name would work.

**Additional data**
I would like to get the column here to be sure the row-order is the same. 

I assume Transform() should preserve order(?) . If so, then I suppose this is not a very important issue.

**Comment by luisquintanilla** [comment] 2022-09-27 21:32
Hi @torronen 

Thanks for this issue. I believe this is by design. If you care about preserving the original / intermediate data, it's recommended that you set the outputColumnName as something other than the inputColumnName. However, if you don't do that, you can still access any of the other columns by the same name except you do so by using the column's index instead of the name.

**Comment by torronen** [comment] 2022-09-28 09:18
@luisquintanilla Thank you. 
Just final confirmation: The order of the rows in DataView is the same before and after .Transform(), is that correct? 

```
DataView original = GetDataView();
DataView final = pipe.Transform(original);
// final has preserved order, row order is always same as in original
```

For context: I wanted to get the element id's for each prediction and to make sure the order is the same. My first instict was to get Score column and then get the EntityId column from the final dataview with predictions. Instead, I should take the entityId's from the original dataview --OR-- get the column index number. 

Normally EntityId would not have tranforms, I think, but in this case it is text and this is a Model Builder or Microsoft.ML.AutoML model so it has automatically added some default transforms to text fields.

---
Additional similar context: I may want to average the prediction by some category. For example, if we run predictions for student test scores I might not care about individual students (even if predict at this level), and I want to get the average for each age group. So I will need to get the age column for each prediction.

**Comment by luisquintanilla** [comment] 2022-10-07 17:19
Correct. The order is preserved. @michaelgsharp can confirm though.

**Comment by michaelgsharp** [comment] 2022-10-10 19:50
Thats correct @luisquintanilla and @torronen. Order is preserved. Closing this issue for now as it has been resolved, but feel free to open another if the need arises.

**Closed by michaelgsharp** 2022-10-10 19:50 UTC
Labels: enhancement, untriaged
