### ISSUE TITLE
Textloader behavior for non present columns

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#3054] opened 2019-03-21 21:26 UTC
```
MLContext mlContext = new MLContext();
mlContext.Log += MlContext_Log;
var loader = mlContext.Data.CreateTextLoader(new Data.TextLoader.Options()
{
    Columns = new[] { new Data.TextLoader.Column("A", Data.DataKind.Int32, 0),
                      new Data.TextLoader.Column("B", Data.DataKind.Single, 1),
                      new Data.TextLoader.Column("C", Data.DataKind.Single, 2),
                      new Data.TextLoader.Column("D", Data.DataKind.Single, 3),
                      new Data.TextLoader.Column("E", Data.DataKind.Single, 4),
                      new Data.TextLoader.Column("F", Data.DataKind.Single, 5),
                      new Data.TextLoader.Column("G", Data.DataKind.Single, 6),}
                      });
var data =loader.Load("sample.txt");
var pr = data.Preview();
}

private static void MlContext_Log(object sender, LoggingEventArgs e)
{
    Console.WriteLine(e.Message);
}
```
[sample.txt](https://github.com/dotnet/machinelearning/files/2994016/sample.txt)

Right now if I inspect any column other than "A" I would see array of zeros.
I see no messages in log regarding: column with index 1 not found.
I'm not sure why it's zeros and not NaN (so we can treat them as missing values).
I don't know what behavior should TextLoader have, either fail or send warning messages, but I found it strange what we don't do anything right now.

**Comment by Ivanidzo4ka** [comment] 2019-03-21 21:27
cc @TomFinley @eerhardt @yaeldekel

**Comment by yaeldekel** [comment] 2019-03-22 19:42
From this comment: https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Data/Conversion.cs#L1328
it seems that this is what TextLoader has always done, although I'm not sure which makes more sense (0 or NaN). 

I noticed that for integer types, we claim in the comment here https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Data/Conversion.cs#L1208 to return false for non-parsable text or overflow, but in the code of that method, we actually throw in case of overflow.

**Comment by TomFinley** [comment] 2019-03-27 14:59
> From this comment: https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Data/Conversion.cs#L1328
> it seems that this is what TextLoader has always done, although I'm not sure which makes more sense (0 or NaN).

Given that neither text nor integers support `NA` any longer (and cannot, see [ref here](https://github.com/dotnet/machinelearning/issues/673#issuecomment-413870755) ), and we probably want our conversions to be sparsity preserving, the only valid choice if we do not throw is for the text to remain the empty string, and correspondingly (since we want this particular conversion to be sparsity preserving) for that empty string to be parsed as zero.

Of course, in the same PR associated with the linked issue we also made clear that we were abandoning our prior stance that cursors should not throw, and instead we now believe cursors are free to throw. So with that shift in stance, may if you indicate that a file has five fields but only three are observed, it should throw.

But, it definitely is not a bug. It *was* designed that was for reasons that were (under the "no throw" constraint) actually completely inevitable. But with the lifting of that constraint we are free to do something else, if we want.

But probably not now, since that would involve a rather drastic shift in behavior for text loader which we probably cannot undertake at this time since it would represent a breaking change. Certainly documenting this behavior of `TextLoader` would be worthwhile.

**Comment by mstfbl** [comment] 2020-01-15 01:48
Closing this issue per @TomFinley 's last comment.

**Closed by mstfbl** 2020-01-15 01:48 UTC
Labels: P3, api, question
