### ISSUE TITLE
[Image Classification API] TensorFlow exception triggered while loading model

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#4420] opened 2019-10-30 21:11 UTC
### System information

- **OS version/distro**: Windows 10 
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1 
- **NuGet Packages**

  - Microsoft.ML (1.4.0-preview3-28230-5)
  - Microsoft.ML.ImageAnalytics (1.4.0-preview3-28230-5)
  - Microsoft.ML.Vision (1.4.0-preview3-28230-5)

### Issue

Tried to train a model using Image Classification API and ResNetV2101 architecture.

### Source code / logs

Source Code: https://github.com/luisquintanilla/machinelearning-samples/blob/testing-1.4.0-samples/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/Program.cs

Stack Trace:

```text
   System.FormatException
  HResult=0x80131537
  Message=Tensorflow exception triggered while loading model.
  Source=Microsoft.ML.TensorFlow
  StackTrace:
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.Vision.ImageClassificationTrainer.LoadTensorFlowSessionFromMetaGraph(IHostEnvironment env, Architecture arch, String path)
   at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at DLImageClassificationBinary.Program.Main(String[] args) in C:\Users\luquinta.REDMOND\source\repos\DLImageClassificationBinary\DLImageClassificationBinary\Program.cs:line 60

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by ashbhandare** [comment] 2019-10-30 22:37
Was able to reproduce the error. The error occurs because the tensorflow DLL is not found. It can be resolved by installing the appropriate nuget : SciSharp.TensorFlow.Redist ( or SciSharp.TensorFlow.Redist-Windows-GPU for GPU support) (https://github.com/dotnet/machinelearning/blob/master/docs/api-reference/tensorflow-usage.md).

**Closed by ashbhandare** 2019-10-30 22:37 UTC
