### ISSUE TITLE
System.IO.PathTooLongException when Saving Model

### ISSUE THREAD

**Issue by tatooian** [dotnet/machinelearning#1356] opened 2018-10-24 13:47 UTC
### System information

- **Windows**:
- **.NET Version 4.7.2**: 

### Issue

- **What did you do?**
I tried to save a model.
- **What happened?**
I got a 'System.IO.PathTooLongException', and saving was unsuccessful.
- **What did you expect?**
I expected the model to save. When training other models in the same application, they save successfully.

### Source code / logs
**Exception hit at:**
Microsoft.ML.Data.dll!Microsoft.ML.Runtime.Model.Repository.GetPath(out string pathEnt, out string pathTemp, string dir, string name, bool createDir) Line 270
\src\Microsoft.ML.Data\Model\Repository.cs(270)

**In Watch**, 'entityPath' = 'C:\Users\Ian Wallace\AppData\Local\Temp\TLC_4A390CA5\TransformerChain\Transform_000\Transform_000\Transform_000\Transform_000\Transform_000\Transform_001\Transform_000\Transform_000\Transform_000\Transform_000\Transform_000\Step_002\Mapper\Vocabulary\Model.key' 

**Exception:**
System.IO.PathTooLongException
  HResult=0x800700CE
  Message=The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
  Source=mscorlib
  StackTrace:
```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) in f:\dd\ndp\clr\src\BCL\system\io\__error.cs:line 168
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) in f:\dd\ndp\clr\src\BCL\system\io\directory.cs:line 374
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost) in f:\dd\ndp\clr\src\BCL\system\io\directory.cs:line 115
   at Microsoft.ML.Runtime.Model.Repository.GetPath(String& pathEnt, String& pathTemp, String dir, String name, Boolean createDir) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\Repository.cs:line 270
   at Microsoft.ML.Runtime.Model.RepositoryWriter.CreateEntry(String dir, String name) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\Repository.cs:line 329
   at Microsoft.ML.Runtime.Model.ModelSaveContext..ctor(RepositoryWriter rep, String dir, String name) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaveContext.cs:line 87
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveSubModel(String dir, Action'1 fn) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 79
   at Microsoft.ML.Runtime.Data.TermTransform.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\Transforms\TermTransform.cs:line 707
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.RowToRowMapperTransform.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataView\RowToRowMapperTransform.cs:line 299
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TextTransform.Transformer.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Transforms\Text\TextTransform.cs:line 627
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.Save(ModelSaveContext ctx) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 159
   at Microsoft.ML.Runtime.Model.ModelSaveContext.SaveModel[T](RepositoryWriter rep, T value, String path) in E:\A\_work\292\s\src\Microsoft.ML.Data\Model\ModelSaving.cs:line 38
   at Microsoft.ML.Runtime.Data.TransformerChain'1.SaveTo(IHostEnvironment env, Stream outputStream) in E:\A\_work\292\s\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs:line 195
```
**Comments**:
When the local user's temp folder path is combined with the temporary folder hierarchy created while saving, it can exceed the 260 character limit.
I can save other models successfully using the same code. The folder hierarchy has less depth, so I guess they don't hit the limit.

**Workaround**:
I can set the local user TMP environment variable to 'C:\Tmp', reboot, and the model saves successfully.

**Comment by artidoro** [comment] 2018-10-27 00:32
Thank you for reporting the bug!

**Comment by Zruty0** [comment] 2018-10-29 16:41
@tatooian , would youi mind sharing the training code? It sounds strange that we need such a deep tree of transformers for the model.

Nevertheless, it is a bug that we'll have to fix, I'm just double-checking that the paths look indeed sensible for the complexity of your model.

**Comment by shmoradims** [comment] 2018-11-28 19:14
@tatooian, could you please share your code/data so that we can repro the bug and fix it? thanks.

**Comment by tatooian** [comment] 2018-11-29 10:48
I'm not sure how much you need, but here goes:
```
    public abstract class BaseBatten
    {
        [Column("0")]
        public float Index;

        [Column("1")]
        public float TackEvalData;

        [Column("2")]
        public float BattenType;

        [Column("5")]
        public float Length;

        [Column("6")]
        public float Carbon;

        [Column("7")]
        public float BattenCount;

        [Column("8")]
        public float BattenConfigID;

        [Column("9")]
        public float MaxAws;

        [Column("10")]
        public float Weight;
    }

    public class BattenThickness: BaseBatten 
    {
        [Column("3")]
        public float Width;

        [Column("4")]
        [ColumnName("Label")]
        public string Label;
    }

    public enum PipelineType: byte
    {
        Unspecified = 0,
        MainsailBattenWidth = 1,
        MainsailBattenThickness = 2,
        HeadsailBattenWidth = 3,
        HeadsailBattenThickness = 4,
        WebbingMaterial = 5,
        WebbingWidth = 6,
        WebbingMaxLength = 7,
        WebbingQty = 8
    }

    public abstract class BaseBattenClassificationPipeline : BaseClassificationPipeline
    {
        public BaseBattenClassificationPipeline(FileResolver resolver, Enums.PipelineType pipelineType) : base(resolver, pipelineType)
        {
        }

        public override void GetData(DataTable srcDataTable)
        {
            base.GetData(srcDataTable);
            var d = new BattenDataSet(srcDataTable);
            _DataView = _LocalEnvironment.CreateDataView(d.GetData(_PipelineType));
            Console.WriteLine(" Data Mapped");
        }
    }

  public class BattenThicknessPipeline : BaseBattenClassificationPipeline
    {
        public BattenThicknessPipeline(FileResolver resolver, PipelineType pipelineType) : base(resolver, pipelineType)
        {
        }

        public override void TrainModel()
        {
            ConfigureLightGbmArguments();

            var DataViewSchema = _DataView.AssertStatic(_LocalEnvironment, c => (
                     Index: c.R4.Scalar,
                     TackEvalData: c.R4.Scalar,
                     Type: c.Text.Scalar,
                     Length: c.R4.Scalar,
                     Carbon: c.Text.Scalar,
                     BattenCount: c.R4.Scalar,
                     BattenConfig: c.Text.Scalar,
                     MaxAws: c.R4.Scalar,
                     Width: c.R4.Scalar,
                     Label: c.Text.Scalar
               ));
            var EstimatorPipeline = DataViewSchema.MakeNewEstimator()
                .Append(mapper: a => (
                    a.Label,
                    TypeID: a.Type.FeaturizeText(),
                    CarbonID: a.Carbon.FeaturizeText(),
                    BattenConfigID: a.BattenConfig.FeaturizeText(),
                    Data1: a
                ))
                .Append(mapper: r => (
                    r.Label,
                    // Concatenate all required features together into one column 'Features'.
                    Features: r.TypeID.ConcatWith(r.CarbonID, r.BattenConfigID, r.Data1.Index, r.Data1.TackEvalData, r.Data1.Length, r.Data1.MaxAws, r.Data1.BattenCount, r.Data1.Width)
                ))
                .Append(mapper: r => (
                    r.Label,
                    // Normalize (rescale) the features to be between -1 and 1. 
                    Features: r.Features.Normalize(
                    // When the normalizer is trained, the below delegate is going to be called.
                    // We use it to memorize the scales.
                    onFit: (scales, offsets) => _NormalizedScales = scales)
                ))
                .Append(mapper: r => (
                      r.Label,
                    // Train the multi-class LightGbm model to predict the label using features.
                    Predictions: _Classification.Trainers.LightGbm(r.Label.ToKey(), r.Features, advancedSettings: a => { a = _LightGbmArgs; },
                    onFit: p => _Predictor = p)
                ))
                .Append(r => (
                    //need to treat Label as Key 
                    LabelKey: r.Label.ToKey(),
                    //instance of ClassificationVectorData returned
                    r.Predictions,
                    //the predicted classification - see: prediction.PredictedClass
                    PredictedClass: r.Predictions.predictedLabel.ToValue(),
                    r.Label
                ));

            var (TrainingData, TestingData) = _Classification.TrainTestSplit(DataViewSchema, testFraction: 0.5);

            // Train the model.
            var Model = EstimatorPipeline.Fit(TrainingData);

            // Evaluate
            var Metrics = _Classification.Evaluate(Model.Transform(TestingData), r => r.LabelKey, r => r.Predictions);
            Console.WriteLine("AccuracyMicro: " + Metrics.AccuracyMicro);
            Console.WriteLine("AccuracyMacro: " + Metrics.AccuracyMacro);


            //var CvResults = _Classification.CrossValidate(DataViewSchema, EstimatorPipeline, r => r.LabelKey, numFolds: 3);
            //var microAccuracies = CvResults.Select(r => r.metrics.AccuracyMicro);
            //Console.WriteLine("MicroAccuracies Average: " + microAccuracies.Average());
            //var macroAccuracies = CvResults.Select(r => r.metrics.AccuracyMacro);
            //Console.WriteLine("MacroAccuracies Average: " + macroAccuracies.Average());
            SaveModel(Model.AsDynamic);
        }

        protected override void ConfigureLightGbmArguments()
        {
            //_LightGbmArgs.CatL2 = 1;
            _LightGbmArgs.CatSmooth = 20;
            //_LightGbmArgs.EarlyStoppingRound = 0;
            //_LightGbmArgs.LearningRate = 0.4;
            //_LightGbmArgs.MaxBin = 2048;
            //_LightGbmArgs.MaxCatThreshold = 32;
            //_LightGbmArgs.MinDataPerGroup = 100;
            //_LightGbmArgs.NumBoostRound = 200;
            //_LightGbmArgs.NumLeaves = 575;
            //_LightGbmArgs.Sigmoid = 0.5;
            //_LightGbmArgs.Silent = false;
            //_LightGbmArgs.UseMissing = false;
            _LightGbmArgs.UseSoftmax = true;
            // _LightGbmArgs.VerboseEval = false;
        }
    }
```

**Comment by wschin** [comment] 2018-12-20 21:42
What is `SaveModel` in your example code? I tried copy-and-paste your code but there are several missing definitions.

**Comment by wschin** [comment] 2018-12-21 19:11
Ok, finally I got something similar to run. If you are able to clone ML.NET repo, the following example can be executed by copy-and-pasting it to `machinelearning\test\Microsoft.ML.StaticPipelineTesting\Training.cs` and running it via `Visual Studio Test Explorer`.
```csharp
        public class CustExample
        {
            [Column("0")]
            public float Index;
            [Column("1")]
            public float TackEvalData;
            [Column("2")]
            public string Type;
            [Column("3")]
            public float Width;
            [Column("4")]
            [ColumnName("Label")]
            public string Label;
            [Column("5")]
            public float Length;
            [Column("6")]
            public string Carbon;
            [Column("7")]
            public float BattenCount;
            [Column("8")]
            public string BattenConfig;
            [Column("9")]
            public float MaxAws;
            [Column("10")]
            public float Weight;
        }

        static public List<CustExample> GenerateExamples(int count)
        {
            var examples = new List<CustExample>();
            var rnd = new Random(0);
            for (int i = 0; i < count; ++i)
            {
                var example = new CustExample();
                example.Index = rnd.NextSingle();
                example.TackEvalData = rnd.NextSingle();
                var buffer = new byte[5];
                rnd.NextBytes(buffer);
                example.Type = System.Text.Encoding.UTF8.GetString(buffer);
                example.Width = rnd.NextSingle();
                rnd.NextBytes(buffer);
                example.Label = System.Text.Encoding.UTF8.GetString(buffer);
                example.Length = rnd.NextSingle();
                rnd.NextBytes(buffer);
                example.Carbon = System.Text.Encoding.UTF8.GetString(buffer);
                example.BattenCount = rnd.NextSingle();
                rnd.NextBytes(buffer);
                example.BattenConfig = System.Text.Encoding.UTF8.GetString(buffer);
                example.MaxAws = rnd.NextSingle();
                example.Weight = rnd.NextSingle();
                examples.Add(example);
            }
            return examples;
        }

        [Fact()]
        public void LightGBMCustTest()
        {
            var mlContext = new MLContext(seed: 1, conc: 1);
            var examples = GenerateExamples(1000);
            var dataView = ComponentCreation.CreateDataView(mlContext, examples);

            var ctx = new MulticlassClassificationContext(mlContext);

            var staticDataView = dataView.AssertStatic(mlContext, c => (
                         Index: c.R4.Scalar,
                         TackEvalData: c.R4.Scalar,
                         Type: c.Text.Scalar,
                         Width: c.R4.Scalar,
                         Label: c.Text.Scalar,
                         Length: c.R4.Scalar,
                         Carbon: c.Text.Scalar,
                         BattenCount: c.R4.Scalar,
                         BattenConfig: c.Text.Scalar,
                         MaxAws: c.R4.Scalar,
                         Weight: c.R4.Scalar));
            var pipe = staticDataView.MakeNewEstimator()
                    .Append(mapper: a => (
                        a.Label,
                        TypeID: a.Type.FeaturizeText(),
                        CarbonID: a.Carbon.FeaturizeText(),
                        BattenConfigID: a.BattenConfig.FeaturizeText(),
                        Data1: a
                    ))
                    .Append(mapper: r => (
                        r.Label,
                        // Concatenate all required features together into one column 'Features'.
                        Features: r.TypeID.ConcatWith(r.CarbonID, r.BattenConfigID, r.Data1.Index, r.Data1.TackEvalData, r.Data1.Length, r.Data1.MaxAws, r.Data1.BattenCount, r.Data1.Width)
                    ))
                    .Append(mapper: r => (
                        r.Label,
                        // Normalize (rescale) the features to be between -1 and 1. 
                        Features: r.Features.Normalize(
                        // When the normalizer is trained, the below delegate is going to be called.
                        // We use it to memorize the scales.
                        )
                    ))
                    .Append(mapper: r => (
                        r.Label,
                        // Train the multi-class LightGbm model to predict the label using features.
                        Predictions: ctx.Trainers.LightGbm(r.Label.ToKey(), r.Features)
                    ))
                    .Append(r => (
                        //need to treat Label as Key 
                        LabelKey: r.Label.ToKey(),
                        //instance of ClassificationVectorData returned
                        r.Predictions,
                        //the predicted classification - see: prediction.PredictedClass
                        PredictedClass: r.Predictions.predictedLabel.ToValue(),
                        r.Label
                    ));

                var (TrainingData, TestingData) = ctx.TrainTestSplit(staticDataView, testFraction: 0.5);

                // Train the model.
                var Model = pipe.Fit(TrainingData);

                // Evaluate
                var Metrics = ctx.Evaluate(Model.Transform(TestingData), r => r.LabelKey, r => r.Predictions);
                Console.WriteLine("AccuracyMicro: " + Metrics.AccuracyMicro);
                Console.WriteLine("AccuracyMacro: " + Metrics.AccuracyMacro);

            using (var fs = File.Create("D:\\Repos\\model.zip"))
                mlContext.Model.Save(Model.AsDynamic, fs);
        }
```
On the other hand, the model I created doesn't contain folders as deep as yours. At most, I have `model.zip\TransformerChain\Transform_000\Transform_000\Transform_000\Step_002\Mapper\Vocabulary`. Of course, it's possible to create very hierarchical models containing sub-directories like `TransformerChain\Transform_000\Transform_000\Transform_000\Transform_000\Transform_000\Transform_001\Transform_000\Transform_000\Transform_000\Transform_000\Transform_000\Step_002\Mapper\Vocabulary\Model.key', which unfortunately, is caused by ML.NET's current design. Btw, I saw `TLC` in your model path; could you please double-check if you are using TLC or ML.NET?

**Comment by tatooian** [comment] 2019-01-10 13:46
Hard to say, as this line
`Predictions: ctx.Trainers.LightGbm(r.Label.ToKey(), r.Features)`
refuses to build, with the error:

'MulticlassClassificationContext.MulticlassClassificationTrainers' does not contain a definition for 'LightGbm' and the best extension method overload 'LightGbmExtensions.LightGbm(RegressionContext.RegressionTrainers, string, string, string, int?, int?, double?, int, Action<LightGbmArguments>)' requires a receiver of type 'RegressionContext.RegressionTrainers'

**Comment by wschin** [comment] 2019-03-26 16:57
Massive renaming happened in the past 2 months. Please take a look at the [latest stable example](https://github.com/dotnet/machinelearning/blob/9caafb04d2b4f298f2a9479a9550597afee32c94/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/LightGbm.cs#L6) of LightGbm. All LightGbm functions for regression and classification are [here](https://github.com/dotnet/machinelearning/blob/8b1b14f916428967dc0066b956485c35a0090fe3/src/Microsoft.ML.LightGbm/LightGbmCatalog.cs).

**Comment by codemzs** [comment] 2019-06-30 07:50
please check the current stable API and see if this repros. closing but feel free to reopen.

**Closed by codemzs** 2019-06-30 07:50 UTC
Labels: need info
