### ISSUE TITLE
Remove the dead code inside the FastTree assembly

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2468] opened 2019-02-07 22:37 UTC
The code inside src/Microsoft.ML.FastTree/Application is not in use. 

Delete the Folder.

**Comment by codemzs** [comment] 2019-02-08 14:52
Have you confirmed this is not used by internal repo? If it is we should make sure we move these files there after they are removed from here.

**Comment by Ivanidzo4ka** [comment] 2019-02-12 04:20
They are used, but I don't see huge issues in restoring this files internally. 
I'm closing issue, since files and catalog no longer part of this repository.

**Closed by Ivanidzo4ka** 2019-02-12 04:20 UTC
Labels: good first issue, nit, up-for-grabs
