### ISSUE TITLE
ONNX outputs don't match model outputs after serialization

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2980] opened 2019-03-15 21:33 UTC
When I save a model to ONNX, load, and apply it with `ApplyOnnxModel`, it adds a zero as a suffix to all columns, including the expected output. This includes input columns, so the resulting `IDataView` now has double the columns, plus the output. To top it off, it's not clear how to find the output because it's been renamed.

Example:
ML.NET model
  Input:  `Features`
  Output: `Score`
  Resulting Schema: `Features`, `Score`

After Onnx Serialization / Deserialization:
  Input: `Features`
  Output: `Features0`, `Score0`
  Resulting Schema: `Features`, `Features0`, `Score0`

I am not sure if this is by design, but it feels like a bug.

**Comment by jignparm** [comment] 2019-03-18 22:22
What does the model above produce as outputs  (try this viewer https://github.com/lutzroeder/netron/releases/tag/v2.9.4) ? The zeros at the end of the names seems odd -- unless those are the names of the model outputs.

The OnnxTransform will generate output **all** output columns by default, with  names, type and shape specified by the model, unless the user specifies explicitly the list of columns they are interested in.

**Comment by rogancarr** [comment] 2019-03-18 22:30
@jignparm Check out this PR: #2984 . I think the issue is the way we save or load the model.

**Comment by jignparm** [comment] 2019-03-21 21:51
@rogancarr , looks like the PR is merged.

For issues #2980, #2981 and #2982, the likely reason for the behaviour is the way the model is generated, as you mentioned above, using the function **mlContext.Model.ConvertToOnnx(model, data, file);**. 

The OnnxTransform should honor the type, shape and names as specified by the model. In case there's a discrepancy with the OnnxTransform, that can be tracked in a separate issue.

**Comment by rogancarr** [comment] 2019-03-21 22:58
@jignparm The PR for tests is merged, but I'm still investigating this particular behavior. I'll post here once I've updated. I do think that it's in the function you call out.

**Comment by singlis** [comment] 2019-04-05 00:50
The "0" is because we are preserving the input column to imitate the behavior of what we would have in ml.net where the original columns are preserved as part of the output. In order to preserve the input, we are passing the input through an identity transform. ONNX can't have multiple inputs/outputs of the same name, so ML.NET generates the new output name by appending a 0 to the name:
![image](https://user-images.githubusercontent.com/17055319/55597042-7f5e1700-5700-11e9-8cdf-5a7b9e9652d3.png)

This is by design. If we want true "end-to-end" symmetry with an imported ONNX model in that  we have the same outputs as the original ML.NET model, then we would have to add CopyColumn transforms that rename the column back to the original column. 

I feel like this is treading on the doing things automagically so I will add @TomFinley in case he has some thoughts, but from the stance of having an explicit API, then we don't want to do a conversion and this behavior is OK. If the user wants to rename back to the original, they can add a CopyColumn to rename.

**Closed** 2020-02-19 18:11 UTC
Labels: P3, bug, usability
