### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by pockiez** [dotnet/machinelearning#5190] opened 2020-06-02 07:34 UTC
### System information

- Windows 10 10.0.18363.836
- .NET Core 3.1
- Microsoft.ML 1.5

### Issue

- How to fix this.

![image](https://user-images.githubusercontent.com/11924335/83492875-22194d80-a4de-11ea-9d0d-4066d8a132b2.png)

**Comment by Lynx1820** [comment] 2020-06-02 16:26
Hi @pockiez, 

Can you provide the code to replicate?

**Comment by mstfbl** [comment] 2020-06-15 23:34
Hi @pockiez,
Can you provide the code with which you've obtained this error? We cannot diagnose your issue if we do not know how you have obtained it. We will close this issue if we are not able to reproduce in a timely manner. Thanks.

**Comment by mstfbl** [comment] 2020-06-18 03:43
Closing this issue as author has not responded. @pockiez feel free to reopen this issue and provide your repro for our diagnosis. Thanks.

**Closed by mstfbl** 2020-06-18 03:43 UTC
Labels: Awaiting User Input, P1
