### ISSUE TITLE
"Input string was not in a correct format." exception when executing experiment with ML.AutoML

### ISSUE THREAD

**Issue by patricia-ikosoft** [dotnet/machinelearning#5428] opened 2020-10-12 12:57 UTC
### System information

- Microsoft Windows 7 Professional, Version	6.1.7601 Service Pack 1 Build 7601
- .Net Core 3.1
- Microsoft.ML.AutoML 0.17.2

### Issue

- I am executing an experiment with ML.AutoML, using the data from test2.csv
-  I constantly have a parsing exception on experiment.Execute(data, labelProperty.Name),
no matter what label I'm choosing, or if I'm loading the data directly from the file or I'm reading and parsing it myself.

 at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Microsoft.ML.AutoML.SweeperProbabilityUtils.ParameterSetAsFloatArray(IValueGenerator[] sweepParams, ParameterSet ps, Boolean expandCategoricals)
   at Microsoft.ML.AutoML.SmacSweeper.FitModel(IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.SmacSweeper.ProposeSweeps(Int32 maxSweeps, IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.PipelineSuggester.SampleHyperparameters(MLContext context, SuggestedTrainer trainer, IEnumerable`1 history, Boolean isMaximizingMetric)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IEnumerable`1 trainerAllowList)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, String labelColumnName, String samplingKeyColumn, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at MLPoc.Services.LoadDataService.TrainDataAndCreateModel(List`1 properties, DynamicTypeProperty labelProperty, List`1 lineValues) in C:\DevITPAzurePatricia\Ikosoft\MLPoc\Services\LoadDataService.cs:line 81

### Source code / logs
[code.zip](https://github.com/dotnet/machinelearning/files/5365217/code.zip)

**Comment by frank-dong-ms** [comment] 2020-10-20 03:58
@patricia-ikosoft Sorry for late response, could you please share a complete repro project, I download you code piece and there are some missing definition: MLPoc.Data, DynamicTypeProperty, DataModel and LoadDataHelper.

**Comment by patricia-ikosoft** [comment] 2020-10-20 09:04
[complete_code.zip](https://github.com/dotnet/machinelearning/files/5407642/complete_code.zip)

**Comment by patricia-ikosoft** [comment] 2020-10-20 09:06
You can test it by running the app, selecting the .csv file, selecting "HistorySalesPrice" in the dropdown, and click on the button "Click me" to run the experiment

**Comment by frank-dong-ms** [comment] 2020-10-20 21:41
@patricia-ikosoft I tried run you sample and get below error message with call stack:
All instances skipped due to missing features.

call stack:
   at Microsoft.ML.Trainers.FastTree.DataConverter.MemImpl.MakeBoundariesAndCheckLabels(Int64& missingInstances, Int64& totalInstances)
   at Microsoft.ML.Trainers.FastTree.DataConverter.MemImpl..ctor(RoleMappedData data, IHost host, Double[][] binUpperBounds, Single maxLabel, Boolean dummy, Boolean noFlocks, PredictionKind kind, Int32[] categoricalFeatureIndices, Boolean categoricalSplit)
   at Microsoft.ML.Trainers.FastTree.DataConverter.Create(RoleMappedData data, IHost host, Int32 maxBins, Single maxLabel, Boolean diskTranspose, Boolean noFlocks, Int32 minDocsPerLeaf, PredictionKind kind, IParallelTraining parallelTraining, Int32[] categoricalFeatureIndices, Boolean categoricalSplit)
   at Microsoft.ML.Trainers.FastTree.ExamplesToFastTreeBins.FindBinsAndReturnDataset(RoleMappedData data, PredictionKind kind, IParallelTraining parallelTraining, Int32[] categoricalFeaturIndices, Boolean categoricalSplit)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.ConvertData(RoleMappedData trainData)
   at Microsoft.ML.Trainers.FastTree.FastForestRegressionTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.AutoML.SmacSweeper.FitModel(IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.SmacSweeper.ProposeSweeps(Int32 maxSweeps, IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.PipelineSuggester.SampleHyperparameters(MLContext context, SuggestedTrainer trainer, IEnumerable`1 history, Boolean isMaximizingMetric)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IEnumerable`1 trainerAllowList)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, String labelColumnName, String samplingKeyColumn, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at MLPoc.Services.LoadDataService.RunExperiment(MLContext mlContext, IDataView data, DynamicTypeProperty labelProperty) in C:\code\complete_code\complete_code\MLPoc\Services\LoadDataService.cs:line 130

**Comment by frank-dong-ms** [comment] 2020-10-21 03:38
Looks like previous error I got is not stable, sometimes I can run experiment without issue sometime I get previous error.
Looked at call stacks and error messages I can tell they both are complain about data is not in right format or no data at all, so @patricia-ikosoft looks like the exception you got is related to data loading process. Could you please try to mock some data instead of loading from file and then see if you can reproduce your exception?
Also, ML.NET has its own data loading functionality, you could reference below API: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textloadersavercatalog.loadfromtextfile?view=ml-dotnet

**Comment by patricia-ikosoft** [comment] 2020-10-21 07:48
I always reproduce the error, even if I tried to use LoadFromTextFile or LoadFromEnumerable (using a predefined data model, not dynamic, and parsing myself the values from file). It is systematic on my machine (Windows7). What I noticed on the other hand it is that, if I lower the time of the experiment (60 seconds for example), I no longer have the error

**Comment by frank-dong-ms** [comment] 2020-10-21 22:02
@patricia-ikosoft Thanks, please do create repro code sample using LoadFromTextFile, I will try to create a azure vm with window7 to see if I can repro your issue.

**Comment by patricia-ikosoft** [comment] 2020-10-22 09:50
[Uploading complete_code2.zip…]()

**Comment by patricia-ikosoft** [comment] 2020-10-22 09:53
I just uploaded you the repo. Thanks.

**Comment by frank-dong-ms** [comment] 2020-10-23 07:11
@patricia-ikosoft Thanks, I did created an Azure vm with windows7 (Windows 7 Enterprise, this is the only available image on Azure for windows7) and still no repro on your issue.

I found one issue read through your code is DataModel class, when LoadColumn you should always starts from index 0 instead of 1, could you please fix that and see if the error you are seeing still exists?

**Comment by patricia-ikosoft** [comment] 2020-10-23 09:00
I modified the index, but I still  have the error. Could it be a problem of culture ? I've seen this other issue, that seems to be identical:
https://github.com/dotnet/machinelearning/issues/5162

**Comment by frank-dong-ms** [comment] 2020-10-23 22:16
Yeah, looks like it is same issue, could you try on en-US? @patricia-ikosoft 
At the same time, I do found another issue with AutoML experiment that after about 70 round of experiment, FastTree will complaint about it input data and throw exception, I think we should either properly handle this exception or stop early in this case I'm working on an PR for this issue.

**Comment by patricia-ikosoft** [comment] 2020-10-26 18:31
How could I change the culture that is used internally by ML.Net ?

**Comment by frank-dong-ms** [comment] 2020-10-27 01:40
@patricia-ikosoft just change the system culture to en-US

**Comment by patricia-ikosoft** [comment] 2020-10-28 12:39
Changing the culture to en-US does not seem to solve the problem.

**Comment by patricia-ikosoft** [comment] 2020-11-03 15:37
Yes, it was French initially. Yes, I restated the machine

**Comment by jakub-sedlacek** [comment] 2020-12-28 13:49
Hello, I encountered same error and resolved it by changing system's decimal separator from ',' to '.' (my culture is cs-CZ). After restart everything worked ok.

**Comment by luisquintanilla** [comment] 2022-07-21 19:00
Thanks all for the comments and feedback. We've [updated the implementation of AutoML](https://devblogs.microsoft.com/dotnet/whats-new-with-mldotnet-automl/), so previous API patterns are no longer applicable. Closing this issue for now. Please feel free to open a new issue if it continues to be a problem.

**Closed by luisquintanilla** 2022-07-21 19:00 UTC
Labels: bug, AutoML.NET
