### ISSUE TITLE
How do I use the ML.NET API to implement something like the model builder effect in VS2022？

### ISSUE THREAD

**Issue by landonzeng** [dotnet/machinelearning#6219] opened 2022-06-08 10:31 UTC
**Is your feature request related to a problem? Please describe.**
How can I use the ML.NET API to achieve a model generator effect similar to the one in VS2022. I did not find in the relevant documentation

**Describe the solution you'd like**
I want to dynamically implement a web page like the UI of the .mbconfig window created by the model builder in VS2022 or VS2019, where the user selects the data in the business database for forecasting operations.

**Describe alternatives you've considered**

**Additional context**
Like this UI, is it possible for the developer to implement the content of the interface by means of API calls?
![1](https://user-images.githubusercontent.com/7336781/172595403-8824135b-e9ad-4607-a101-74fcc0608c4c.png)
![2](https://user-images.githubusercontent.com/7336781/172595414-c9762b2d-059c-469b-b3f0-57f096a29073.png)
![3](https://user-images.githubusercontent.com/7336781/172595427-bfeb122f-d5e4-4136-8582-8c7abbcab914.png)
![4](https://user-images.githubusercontent.com/7336781/172595434-70576b34-f24f-4206-8f67-6c9975efdce8.png)

**Comment by luisquintanilla** [comment] 2022-06-10 21:58
Hi @landonzeng 

I'm not sure I fully understand the question so I'll try and answer it in a few ways. Feel free to clarify if my comments don't answer your question.

Model Builder is powered by the ML.NET API, it just exposes its functionality via a UI. If you're referring to can you use the ML.NET API to create a UI like Model Builder, the answer is no. 

If you mean can you train models from a code-first approach like Model Builder, the answer is yes.

Here is some documentation for similar scenarios (classification, regression) but using the API. https://docs.microsoft.com/dotnet/machine-learning/tutorials/sentiment-analysis

Also, we have the AutoML API which is a layer on top of the ML.NET API that automates the training process. The AutoML API is what powers Model Builder and our CLI.

You can see samples of the AutoML API here:

https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb

Whether using the ML.NET API or AutoML API, the UI would serve as the interface for you to gather the inputs you need to train models and pass those inputs to the respective APIs for your intended purpose.

**Comment by landonzeng** [comment] 2022-06-13 02:56
@luisquintanilla Thanks! 
I want to do configurable development through web pages.
The user can select different algorithm models on the page, and then the system automatically adjusts the parameters, similar to the UI configuration of VS2022, but I did not find any relevant cases in the ML.NET API, the API samples are not automatically generated parameters of various algorithms, the user needs to define their own parameters, which will make it more difficult for the user. I would like to implement this function through a web page, but I don't know how to do it.

**Comment by michaelgsharp** [comment] 2022-06-13 19:55
@LittleLittleCloud can you take a look and see if AutoML would work for him?

**Comment by luisquintanilla** [comment] 2022-06-15 17:36
Thanks for that clarification @landonzeng.

I would encourage you taking a look at our AutoML API and Sweepable Estimators. 

Here's a sample notebook that uses them in a pipeline: https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Forecasting%20using%20SSA%20with%20Luna%20Dataset.ipynb

You can also find API documentation for AutoML here: https://docs.microsoft.com/dotnet/api/microsoft.ml.automl?view=ml-dotnet-preview

**Comment by LittleLittleCloud** [comment] 2022-06-15 18:59
@landonzeng 

yes, Sweepable API would be your solution. You can find how to do it from examples in @luisquintanilla answer. Sweepable API is fairly new in ML.Net and you need to use nightly build to access that.

A bit extra info to add, you can also transfer forecasting to a regression problem, which would give you more trainers available. And you can find the example of how to do it [here](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Forecasting%20using%20Regression%20with%20Luna%20Dataset.ipynb)

Once you get the best `result` from `AutoMLExperiment`, you will be able to find the best pipeline and best parameter in `result.TrialSettings.Pipeline` and `result.TrialSettings.Parameter`. However, you will need to come up with your own code in order to produce C# code from that pipeline and parameter as it's not something available in ML.Net.

**Comment by michaelgsharp** [comment] 2022-07-11 16:59
Closing this for now. Thanks for the help @LittleLittleCloud and @luisquintanilla.

**Closed by michaelgsharp** 2022-07-11 16:59 UTC
Labels: question, untriaged
