### ISSUE TITLE
Add a transformer/estimator for loading images out of byte vectors

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1609] opened 2018-11-13 17:30 UTC
Right now we can only load images from disk files. I think it's worthwhile to either update `ImageLoadingTransformer` to be able to load from byte vectors (interpreted as streams), or add another estimator/transformer to do this.

cc @CESARDELATORRE @yaeldekel

**Comment by CESARDELATORRE** [comment] 2019-01-11 17:54
Let's close this issue when the new issue is added to 0.10 backlog, ok?
But I agree, since this issue https://github.com/dotnet/machinelearning/issues/2121 is related and I'm providing further info about the impacted scenarios.

**Comment by zeahmed** [comment] 2019-01-11 19:35
I am closing this issue as a duplicate of #2121.

**Closed by zeahmed** 2019-01-11 19:35 UTC
