### ISSUE TITLE
AutoML 0.3.0 does not generate namespace properly when solution name contains space

### ISSUE THREAD

**Issue by ebizupnorth** [dotnet/machinelearning#3858] opened 2019-06-12 22:10 UTC
### System information

- **OS version/distro**: 
OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
- **.NET Version (eg., dotnet --info)**: 
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

### Issue

- **What did you do?**
Followed the tutorial on using AutoML from https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/scenario but used a project name as "AutoML Sentiment". Note: It contains a space.
- **What happened?**
AutoML did not consider the space in the project name. Generated code below gives a compile error.
```
//*****************************************************************************************
//*                                                                                       *
//* This is an auto-generated file by Microsoft ML.NET CLI (Command-Line Interface) tool. *
//*                                                                                       *
//*****************************************************************************************

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;
using AutoML SentimentML.Model.DataModels;
using Microsoft.ML.Trainers;

namespace AutoML SentimentML.ConsoleApp
{
    public static class ModelBuilder
    {
............
    }
}
```
- **What did you expect?**
I expected that AutoML should replace the space with "_" in order to compile as shown below:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;
using AutoML_SentimentML.Model.DataModels;
using Microsoft.ML.Trainers;

namespace AutoML_SentimentML.ConsoleApp
{
    public static class ModelBuilder
    {
............
    }
}
```

**Comment by justinormont** [comment] 2019-06-13 09:48
@ebizupnorth: Thanks for filing the bug. I think it's a duplicate of https://github.com/dotnet/machinelearning/issues/3792. Feel free to re-open if needed.

**Closed by justinormont** 2019-06-13 09:48 UTC
Labels: AutoML, bug, duplicate
