### ISSUE TITLE
Gradual Memory Increase

### ISSUE THREAD

**Issue by akshayabnave** [dotnet/machinelearning#5161] opened 2020-05-25 11:51 UTC
I am not sure whether this is write channel but I need quick help

We have observed that gradual increase in memory of Host object of module Microsoft.ML.Data.

We have .net core worker service running as windows service.

It does prediction for 50 ML models in parallel.

1. We are loading all models into memory then creating 50 threads for 50 models which would be running continuously and predicting values.

2. For testing purpose we stop all threads ever 1hour and dispose it. Then calling GC.Collect().

3. Also taking memory snapshot every 1 hour using VS performance profiler. We have observed that
gradual increase in memory of Host object of module Microsoft.ML.Data. 

4. If we remove all loded models from memory and call GC.  the the memory consumed by Host object of module Microsoft.ML.Data gets freed.

Could you please suggest anything if we want to resolve gradual increase of memory without removing models from memory.

``` csharp

private List<PredictionResult> ExecuteModel(ModelTransformer modelTransformer, IDataView dataView, DateTime requestDateTime) 
        {
            List<PredictionResult> predictionResults = null;
            try
            {
                if (modelTransformer.Transformer != null)
                {
                    string modelConfigId = modelTransformer.ModelConfigId;
                    string actualValueColumnName = modelTransformer.TextLoaderOutputColumn;
                    string tagNameForPredictedValue = modelTransformer.PredictedTagName;
                    string tagNameForActualValue = modelTransformer.TargetVariable;

                    predictionResults = new List<PredictionResult>();
                    IDataView predictions = modelTransformer.Transformer.Transform(dataView);

                    Logger.log.InfoFormat("[Request at {0} Model Id: {1}] prediction value extraction", requestDateTime, modelConfigId);

                    IEnumerable<float> listScore = predictions.GetColumn<float>("Score");

                    Logger.log.InfoFormat("[Request at {0} Model Id: {1}] score extraction completed", requestDateTime, modelConfigId);

                    IEnumerable<string> listTime = predictions.GetColumn<string>(preModelExecutionDetails.TextLoaderColumn[0].Name);

                    Logger.log.InfoFormat("[Request at {0} Model Id: {1}] Time extraction completed", requestDateTime, modelConfigId);

                    IEnumerable<float> listActualValues = predictions.GetColumn<float>(actualValueColumnName);

                    predictions = null;

                    Logger.log.InfoFormat("[Request at {0} Model Id: {1}] actual value extraction completed", requestDateTime, modelConfigId);

                    predictionResults.AddRange(
                        listTime.Zip(listScore, (time, score) => new PredictionResult
                        {
                            TagName = tagNameForPredictedValue,
                            Timestamp = Convert.ToDateTime(time),
                            Confidence = ConfigParameters.TagValueDefaultConfidence,
                            Value = score.ToString(),
                            ValueType = Models.ValueType.SCORE.ToString()
                        }).ToList());

                    predictionResults.AddRange(
                        listTime.Zip(listActualValues, (time, actualVal) => new PredictionResult
                        {
                            TagName = tagNameForActualValue,
                            Timestamp = Convert.ToDateTime(time),
                            Confidence = ConfigParameters.TagValueDefaultConfidence,
                            Value = actualVal.ToString(),
                            ValueType = Models.ValueType.ACTUAL.ToString()
                        }).ToList());
                }
            }
            finally
            {
                modelTransformer = null;
            }
            return predictionResults;
        }
```

**Comment by mstfbl** [comment] 2020-05-26 05:07
Hi @akshayabnave , if possible, can you share a screenshot of your memory usage showing the accumulation of `IHost` objects?

PR #4995 was merged to remove `IHost` objects that are already cleaned up by GC, and as you said in the PR description, these `IHost` objects are cleaned up after garbage collection. If you are still seeing an accumulation, it may be because GC hasn't collected these yet, because they may be still being used.

I will investigate this issue, and get back to you soon. It would be very helpful if I can attempt to reproduce this issue with the project and data that you have. We can work offline to reproduce if that works better!

**Comment by akshayabnave** [comment] 2020-05-26 08:05
Hello @mstfbl 

Thank you for quick reply,
Here I am attaching screen capture of Memory snapshot.
For this testing, We have loaded all ML models into the memory then created 4 tasks running in parallel and each task is executing 60-90 ML models (we have configuration in SQL for total no. of ML model for each task) sequentially every minute. These tasks are running continuously till the lifetime of the service. We found that Object type host of module Microsoft.ML.Data gradually increasing over the period of time.

In Production environment, there will be 50 Tasks and each task would be executing 60-90 ML models (doing prediction by using models which are already loaded into memory) sequentially every minute. During testing of 50 task we found gradual increase in memory but not able to take memory snapshot as it was taking long time in VS so did with 4 tasks.

Could you please tell me how we can connect offline so that I will check with the team how we do it. 

Thank you.


<img width="902" alt="Snaphot 4" src="https://user-images.githubusercontent.com/39438829/82875674-52e50a00-9f55-11ea-9b09-3fa7c5ae312f.png">
<img width="902" alt="Snaphot 5" src="https://user-images.githubusercontent.com/39438829/82875681-54aecd80-9f55-11ea-9307-bcfc375b5dce.png">
<img width="908" alt="Snaphot 6" src="https://user-images.githubusercontent.com/39438829/82875689-59738180-9f55-11ea-84be-71ece10c45f8.png">
<img width="910" alt="Snaphot 1" src="https://user-images.githubusercontent.com/39438829/82875691-5b3d4500-9f55-11ea-92af-474c32d8391e.png">
<img width="905" alt="Snaphot 2" src="https://user-images.githubusercontent.com/39438829/82875696-5d070880-9f55-11ea-8106-2c3974a4f10c.png">
<img width="907" alt="Snaphot 3" src="https://user-images.githubusercontent.com/39438829/82875700-5ed0cc00-9f55-11ea-982e-19fc0c5508b6.png">

**Comment by mstfbl** [comment] 2020-05-26 17:14
Hi @akshayabnave ,

Thank you for the screenshots and for your explanation. By the way, which version of ML .NET are you using? It is very likely that this issue may still be fixed by #4995 in our newest v1.5 release that will be made available soon.

My work email is mustafa.bal@microsoft.com . Please feel free to reach out to me through this email!

**Comment by akshayabnave** [comment] 2020-05-27 06:21
Hello @mstfbl ,

We are using ML.NET 1.4.

Thank you.

**Comment by mstfbl** [comment] 2020-05-27 17:42
Hi @akshayabnave ,

ML .NET v1.5.0 is out! Please feel free to download from [here](https://www.nuget.org/packages/Microsoft.ML/), and let us know if you see a similar memory leak of `IHost` objects

**Closed** 2020-05-27 17:51 UTC
Labels: P1, bug, need info

**Comment by akshayabnave** [comment] 2020-05-28 16:00
Hello @mstfbl 
We have downloaded and testing it. I will let you if we face same issue. 
Thank you for your support.
