### ISSUE TITLE
Build error: MSML_TypeParamName reports "TType" as not standard

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning#6528] opened 2022-12-22 10:16 UTC
**System Information (please complete the following information):**
 - OS & Version: Windows 11 v10.0.22621.963
 - ML.NET Version: ML.NET v2.0
 - .NET Version: .NET 7

**Describe the bug**
After successfully building the ML.NET project when I try to build it again in Visual Studio, I get the "Type parameter name 'TType' not standard" error and the build fails.

**To Reproduce**
1. Clone this repo
2. Run the `build.cmd` in PowerShell
3. Open the `Microsoft.ML.sln` solution in Visual Studio 2022
4. Try to build the project (F6)
5. (optional) Open a source file that causes the failure (eg. [NormalizeColumnSng.cs](https://github.com/dotnet/machinelearning/blob/main/src/Microsoft.ML.Data/Transforms/NormalizeColumnSng.cs))
6. See the errors in the Error List window

**Expected behavior**
As described [in this document](https://github.com/dotnet/machinelearning/blob/main/docs/building/windows-instructions.md#building-from-visual-studio-2019), I would expect the build command to work in Visual Studio.

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/910321/209109755-42d1147d-6460-4156-a66b-f1a55e9f039f.png)

**Additional context**
I use Visual Studio Enterprise 2022 v17.4.3.

If I refactor the type `TType` to `TTest` then it works fine.

I also tried to keep the `TType` class name, and change [the condition in `TypeParamNameAnalyzer` class](https://github.com/dotnet/machinelearning/blob/9d798f1bb3fb17fe97eba77a694c35e2cb46a4b7/tools-local/Microsoft.ML.InternalCodeAnalyzer/TypeParamNameAnalyzer.cs#L44) from
```csharp
if (name == null || (name.StartsWith("T") && Utils.NameIsGood(name, 1, true))) return;
```
to
```csharp
if (name == null || (true && Utils.NameIsGood(name, 1, true))) return;
```
and it made it work, I could build the solution without any errors.

It doesn't make any sense to me, I hope someone else will understand what's the underlying issue here.

**Comment by michaelgsharp** [comment] 2023-02-06 20:00
@andrasfuchs I am wondering if either it was a temporary issue or something with that specific version of VS. I am using 17.4.4 and I am unable to reproduce this. Closing for now, but if you are able to reproduce still please either re-open or create a new issue for it.

**Closed by michaelgsharp** 2023-02-06 20:00 UTC
Labels: untriaged

**Comment by andrasfuchs** [comment] 2023-03-01 12:53
I have just re-cloned the repo, and tried again. 

I have Visual Studio 2022 v17.4.5 and I still have the same issue as before.

`build.cmd` output:
![image](https://user-images.githubusercontent.com/910321/222142611-7242f936-7151-4eb0-a272-a0df24b53ae3.png)

Error list window in VS after hitting F6 (Build solution):
![image](https://user-images.githubusercontent.com/910321/222143348-8048d5f1-1451-4a85-a617-d8652266e9de.png)

Build log in the Output window:
```
Build started...
1>------ Build started: Project: Microsoft.ML.AutoML.SourceGenerator, Configuration: Debug Any CPU ------
2>------ Build started: Project: Microsoft.ML.InternalCodeAnalyzer, Configuration: Debug Any CPU ------
1>Microsoft.ML.AutoML.SourceGenerator -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.AutoML.SourceGenerator\Debug\netstandard2.0\Microsoft.ML.AutoML.SourceGenerator.dll
2>Microsoft.ML.InternalCodeAnalyzer -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.InternalCodeAnalyzer\Debug\netstandard2.0\Microsoft.ML.InternalCodeAnalyzer.dll
3>------ Build started: Project: Microsoft.ML.Tokenizers, Configuration: Debug Any CPU ------
4>------ Build started: Project: Microsoft.ML.SearchSpace, Configuration: Debug Any CPU ------
5>------ Build started: Project: Microsoft.ML.Mkl.Redist, Configuration: Debug Any CPU ------
6>------ Build started: Project: Microsoft.ML.NugetPackageVersionUpdater, Configuration: Debug Any CPU ------
7>------ Build started: Project: RemoteExecutorConsoleApp, Configuration: Debug Any CPU ------
8>------ Build started: Project: Microsoft.ML.DataView, Configuration: Debug Any CPU ------
9>------ Build started: Project: Microsoft.ML.CpuMath, Configuration: Debug Any CPU ------
5>Microsoft.ML.Mkl.Redist -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.Mkl.Redist\Debug\netstandard2.0\Microsoft.ML.Mkl.Redist.dll
3>Microsoft.ML.Tokenizers -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.Tokenizers\Debug\netstandard2.0\Microsoft.ML.Tokenizers.dll
10>------ Build started: Project: Microsoft.ML.Tokenizers.Tests, Configuration: Debug Any CPU ------
7>RemoteExecutorConsoleApp -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\RemoteExecutorConsoleApp\Debug\net461\win-x64\RemoteExecutorConsoleApp.exe
4>Microsoft.ML.SearchSpace -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.SearchSpace\Debug\netstandard2.0\Microsoft.ML.SearchSpace.dll
9>Microsoft.ML.CpuMath -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.CpuMath\Debug\netstandard2.0\Microsoft.ML.CpuMath.dll
10>Microsoft.ML.Tokenizers.Tests -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.Tokenizers.Tests\Debug\net461\win-x64\Microsoft.ML.Tokenizers.Tests.dll
6>Microsoft.ML.NugetPackageVersionUpdater -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.NugetPackageVersionUpdater\Debug\net6.0\Microsoft.ML.NugetPackageVersionUpdater.dll
7>RemoteExecutorConsoleApp -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\RemoteExecutorConsoleApp\Debug\net6.0\RemoteExecutorConsoleApp.dll
6>Microsoft.ML.NugetPackageVersionUpdater -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.NugetPackageVersionUpdater\Debug\net461\win-x64\Microsoft.ML.NugetPackageVersionUpdater.exe
10>Microsoft.ML.Tokenizers.Tests -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.Tokenizers.Tests\Debug\net6.0\Microsoft.ML.Tokenizers.Tests.dll
9>Microsoft.ML.CpuMath -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.CpuMath\Debug\netcoreapp3.1\Microsoft.ML.CpuMath.dll
11>------ Build started: Project: Microsoft.ML.CpuMath.PerformanceTests, Configuration: Debug Any CPU ------
8>Microsoft.ML.DataView -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.DataView\Debug\netstandard2.0\Microsoft.ML.DataView.dll
12>------ Build started: Project: Microsoft.Data.Analysis, Configuration: Debug Any CPU ------
13>------ Build started: Project: Microsoft.ML.Core, Configuration: Debug Any CPU ------
12>Microsoft.Data.Analysis -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.Data.Analysis\Debug\netstandard2.0\Microsoft.Data.Analysis.dll
14>------ Build started: Project: Microsoft.Data.Analysis.Interactive, Configuration: Debug Any CPU ------
14>Microsoft.Data.Analysis.Interactive -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.Data.Analysis.Interactive\Debug\netcoreapp3.1\Microsoft.Data.Analysis.Interactive.dll
15>------ Build started: Project: Microsoft.Data.Analysis.Interactive.Tests, Configuration: Debug Any CPU ------
11>Microsoft.ML.CpuMath.PerformanceTests -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.CpuMath.PerformanceTests\Debug\net6.0\Microsoft.ML.CpuMath.PerformanceTests.dll
15>Microsoft.Data.Analysis.Interactive.Tests -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.Data.Analysis.Interactive.Tests\Debug\net6.0\Microsoft.Data.Analysis.Interactive.Tests.dll
13>Microsoft.ML.Core -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.Core\Debug\netstandard2.0\Microsoft.ML.Core.dll
16>------ Build started: Project: Microsoft.ML.Maml, Configuration: Debug Any CPU ------
17>------ Build started: Project: Microsoft.ML.Data, Configuration: Debug Any CPU ------
16>Microsoft.ML.Maml -> C:\Work\dotnet\machinelearning-origin\artifacts\bin\Microsoft.ML.Maml\Debug\netstandard2.0\Microsoft.ML.Maml.dll
17>C:\Work\dotnet\machinelearning-origin\src\Microsoft.ML.Data\Transforms\NormalizeColumnSng.cs(530,42,530,47): error MSML_TypeParamName: Type parameter name 'TType' not standard
17>C:\Work\dotnet\machinelearning-origin\src\Microsoft.ML.Data\Transforms\NormalizeColumnSng.cs(640,39,640,44): error MSML_TypeParamName: Type parameter name 'TType' not standard
17>C:\Work\dotnet\machinelearning-origin\src\Microsoft.ML.Data\Transforms\NormalizeColumnSng.cs(597,39,597,44): error MSML_TypeParamName: Type parameter name 'TType' not standard
17>Done building project "Microsoft.ML.Data.csproj" -- FAILED.
18>------ Build started: Project: Microsoft.ML.TestFrameworkCommon, Configuration: Debug Any CPU ------
19>------ Build started: Project: Microsoft.ML.ResultProcessor, Configuration: Debug Any CPU ------
20>------ Build started: Project: Microsoft.ML.PCA, Configuration: Debug Any CPU ------
21>------ Build started: Project: Microsoft.ML.KMeansClustering, Configuration: Debug Any CPU ------
22>------ Build started: Project: Microsoft.ML.Transforms, Configuration: Debug Any CPU ------
23>------ Build started: Project: Microsoft.ML.StandardTrainers, Configuration: Debug Any CPU ------
24>------ Skipped Build: Project: Microsoft.ML.NightlyBuild.Tests, Configuration: Debug Any CPU ------
24>Project not selected to build for this solution configuration 
22>C:\Work\dotnet\machinelearning-origin\src\Microsoft.ML.Transforms\MissingValueReplacingUtils.cs(369,32,369,37): error MSML_TypeParamName: Type parameter name 'TType' not standard
22>Done building project "Microsoft.ML.Transforms.csproj" -- FAILED.
25>------ Build started: Project: Microsoft.ML, Configuration: Debug Any CPU ------
26>------ Build started: Project: Microsoft.ML.TorchSharp, Configuration: Debug Any CPU ------
27>------ Build started: Project: Microsoft.Data.Analysis.Tests, Configuration: Debug Any CPU ------
28>------ Build started: Project: Microsoft.Extensions.ML, Configuration: Debug Any CPU ------
29>------ Build started: Project: Microsoft.ML.Experimental, Configuration: Debug Any CPU ------
30>------ Build started: Project: Microsoft.ML.EntryPoints, Configuration: Debug Any CPU ------
31>------ Build started: Project: Microsoft.ML.Recommender, Configuration: Debug Any CPU ------
32>------ Build started: Project: Microsoft.ML.SamplesUtils, Configuration: Debug Any CPU ------
33>------ Build started: Project: Microsoft.ML.OnnxTransformer, Configuration: Debug Any CPU ------
34>------ Build started: Project: Microsoft.ML.TimeSeries, Configuration: Debug Any CPU ------
35>------ Build started: Project: Microsoft.ML.OneDal, Configuration: Debug Any CPU ------
36>------ Build started: Project: Microsoft.ML.ImageAnalytics, Configuration: Debug Any CPU ------
37>------ Build started: Project: Microsoft.ML.Ensemble, Configuration: Debug Any CPU ------
38>------ Build started: Project: Microsoft.ML.Parquet, Configuration: Debug Any CPU ------
39>------ Build started: Project: Microsoft.ML.OnnxConverter, Configuration: Debug Any CPU ------
40>------ Build started: Project: Microsoft.ML.Mkl.Components, Configuration: Debug Any CPU ------
41>------ Build started: Project: Microsoft.ML.FastTree, Configuration: Debug Any CPU ------
42>------ Build started: Project: Microsoft.ML.DnnImageFeaturizer.ResNet101, Configuration: Debug Any CPU ------
43>------ Build started: Project: Microsoft.ML.DnnImageFeaturizer.ResNet50, Configuration: Debug Any CPU ------
44>------ Build started: Project: Microsoft.ML.DnnImageFeaturizer.AlexNet, Configuration: Debug Any CPU ------
45>------ Build started: Project: Microsoft.ML.DnnImageFeaturizer.ResNet18, Configuration: Debug Any CPU ------
46>------ Build started: Project: Microsoft.ML.TensorFlow, Configuration: Debug Any CPU ------
47>------ Build started: Project: Microsoft.ML.Samples.OneDal, Configuration: Debug Any CPU ------
48>------ Build started: Project: Microsoft.ML.FSharp.Tests, Configuration: Debug Any CPU ------
49>------ Build started: Project: Microsoft.ML.LightGbm, Configuration: Debug Any CPU ------
50>------ Build started: Project: Microsoft.ML.Sweeper, Configuration: Debug Any CPU ------
51>------ Build started: Project: Microsoft.ML.TestFramework, Configuration: Debug Any CPU ------
52>------ Build started: Project: Microsoft.ML.Vision, Configuration: Debug Any CPU ------
53>------ Build started: Project: Microsoft.ML.DnnAnalyzer, Configuration: Debug Any CPU ------
54>------ Build started: Project: Microsoft.ML.Samples.GPU, Configuration: Debug Any CPU ------
55>------ Build started: Project: Microsoft.ML.AutoML, Configuration: Debug Any CPU ------
56>------ Build started: Project: Microsoft.ML.Samples, Configuration: Debug Any CPU ------
57>------ Build started: Project: Microsoft.ML.IntegrationTests, Configuration: Debug Any CPU ------
58>------ Build started: Project: Microsoft.ML.SearchSpace.Tests, Configuration: Debug Any CPU ------
59>------ Build started: Project: Microsoft.Extensions.ML.Tests, Configuration: Debug Any CPU ------
60>------ Build started: Project: Microsoft.ML.TimeSeries.Tests, Configuration: Debug Any CPU ------
61>------ Build started: Project: Microsoft.ML.CpuMath.UnitTests, Configuration: Debug Any CPU ------
62>------ Build started: Project: Microsoft.ML.CodeAnalyzer.Tests, Configuration: Debug Any CPU ------
63>------ Build started: Project: Microsoft.ML.PerformanceTests, Configuration: Debug Any CPU ------
64>------ Build started: Project: Microsoft.ML.Predictor.Tests, Configuration: Debug Any CPU ------
65>------ Build started: Project: Microsoft.ML.Sweeper.Tests, Configuration: Debug Any CPU ------
66>------ Build started: Project: Microsoft.ML.CodeGenerator, Configuration: Debug Any CPU ------
67>------ Build started: Project: Microsoft.ML.AutoML.Interactive, Configuration: Debug Any CPU ------
68>------ Build started: Project: Microsoft.ML.AutoML.Samples, Configuration: Debug Any CPU ------
69>------ Build started: Project: Microsoft.ML.AutoML.Tests, Configuration: Debug Any CPU ------
70>------ Build started: Project: Microsoft.ML.Console, Configuration: Debug Any CPU ------
71>------ Build started: Project: Microsoft.ML.Benchmarks.Tests, Configuration: Debug Any CPU ------
72>------ Build started: Project: Microsoft.ML.OnnxTransformerTest, Configuration: Debug Any CPU ------
73>------ Build started: Project: Microsoft.ML.Tests, Configuration: Debug Any CPU ------
74>------ Build started: Project: Microsoft.ML.CodeGenerator.Tests, Configuration: Debug Any CPU ------
75>------ Build started: Project: Microsoft.ML.Core.Tests, Configuration: Debug Any CPU ------
========== Build: 16 succeeded, 58 failed, 0 up-to-date, 1 skipped ==========
========== Elapsed 00:16,975 ==========

```

Strange! 

Could someone else please try to reproduce this step-by-step?
I'm obviously don't question your successful build @michaelgsharp, I'm just very curious how come this can happen. 
It must be some environmental thing?

I think it's an important issue, because errors like this could prevent potential contributors to work on the repo, especially because the hack I made wasn't that obvious to find...
