### ISSUE TITLE
Q: Feature Importance, new API

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#1255] opened 2018-10-14 18:29 UTC
Hi there,

I have been looking forward to getting my hands on the new API and taking a look at using it to discover feature scores/importance used. Several requests were raised with this in mind and there is an implementation now. But I am struggling to find an example or test by way of illustration. Can someone please forward a link or any snippets. Thanks!

Best regards
Fig

**Comment by shmoradims** [comment] 2018-12-28 20:49
I think we have better & newer answer for this issue now.

@rogancarr / @artidoro, do we have public documentation for the explanability work?

**Comment by rogancarr** [comment] 2019-01-02 21:42
For extracting **Feature Contributions** from existing models for individual predictions, we have the `FeatureContributionCalculationTransform`. [This example code](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs) shows you how to use it.

For examining overall feature importance of a model, we have `Permutation Feature Importance`. You can find documentation [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.permutationfeatureimportanceextensions.permutationfeatureimportance?view=ml-dotnet#Microsoft_ML_PermutationFeatureImportanceExtensions_PermutationFeatureImportance_Microsoft_ML_BinaryClassificationContext_Microsoft_ML_Runtime_IPredictionTransformer_Microsoft_ML_Runtime_IPredictor__Microsoft_ML_Runtime_Data_IDataView_System_String_System_String_System_Boolean_System_Nullable_System_Int32__) and a sample for [regression](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIRegressionExample.cs) and [binary classification](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PfiBinaryClassificationExample.cs).

For building high-complexity interpretable models, we have `Generalized Additive Models` implemented through boosting stumps. You can find the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttree.gamtrainerbase-3?view=ml-dotnet) and a sample [here](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/GeneralizedAdditiveModels.cs).

**Comment by shmoradims** [comment] 2019-01-02 23:48
@lefig, if Rogan's answer above is not enough, please reopen the issue with additional questions. I'm closing it for now. Thanks.

**Closed by shmoradims** 2019-01-02 23:48 UTC
Labels: answered, documentation, explainability, first response, question

**Comment by bartczernicki** [comment] 2019-02-26 02:57
@rogancarr What do the scores/contribution in FCC mean? Do they need to be converted to probabilities?  I might be missing something, but for binary classification FCC doesn't give obvious answer.

DALEX (R package) does this so much nicer, where the added feature contributions can be added together to form the total probability:
![image](https://user-images.githubusercontent.com/39144110/53384141-e0e3d680-3947-11e9-8b8d-b4ffaabb01e3.png)

**Comment by rogancarr** [comment] 2019-03-01 00:50
Hi @bartczernicki !

The contributions calculated by FCC (`FeatureContributionCalculator`) are determined by the raw Score, and not the probability.

A bit of background: In ML.NET, we differentiate between classifiers and calibrated classifiers. Think of any linear model, like a Perceptron or SVM: These produce a separating hyperplane; each example is given some score, and we classify based on what side of the boundary the points are on (i.e. >0?). We can take these scores and learn a calibrator to produce a probability between 0 and 1 (for a basic overview, see the wikipedia article on [Platt Calibration](https://en.wikipedia.org/wiki/Platt_scaling)). (Note that some classifiers, like Logistic Regression and FastTree, are learned with a calibrator and don't need to be calibrated after the fact).

Contributions are based on the Score, as the probability is squished non-linearly between 0 and 1, while the score has a range of +-infinity, and is the actual number that the model is producing. Plus it's easier to model the feature-separability of the Score. Additionally, each model class in ML.NET has its own method for computing contributions. See the [Feature Contribution Calculator docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.featurecontributioncalculatingtransformer?view=ml-dotnet#remarks) for full details. I've also put some rows from a feature calculation with a linear model and a FastTree model below.

Now back to that graph: Feature Contributions calculated by FCC won't fit on that sort of graph because contributions describe how the feature affects the score: They either drive the score up, or drive the score down (i.e. are positive or negative). The graph you show seems to be measuring feature *importance* because each feature has a positive magnitude between  0 and 0.89 and none seem to be driving the final probability down towards 0.

For a closer look, let's explore the outputs of a couple models.

Output from a `LogisticRegression` model over the UCI Adult dataset. Note that the bias term for the model is ` -7.72289`, so most features have positive contributions.
```
Label   Probability     Score   TotalContribution+Bias       Feature-Contributions
False   0.09    -2.35   -2.35   -0.07, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.33, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.59, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.04, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.34, 0.00, 0.00, 0.00, 0.00, 0.00, 0.17, 0.00, 0.00, 0.00, 0.00, 0.00, 0.97, 2.63, 0.38, 0.00, 1.1557
False   0.44    -0.24   -0.24   0.00, -0.21, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.33, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.76, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.86, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.32, 0.00, 0.00, 0.00, 0.00, 0.17, 0.00, 0.00, 0.00, 0.00, 0.00, 1.24, 2.63, 0.00, 0.00, 0.3756
```

Output from a `FastTree` model over the UCI Adult dataset. Note that the contributions do not add up to the Score for the tree models; FCC for trees asks a "what-if" question and the contribution scores are calculated based on a hypothetical alternative score.
```
Label   Probability     Score   TotalContribution       Feature-Contributions
False   0.00    -13.44  -74.14  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.67, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -2.30, 0.65, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -3.73, 0.00, 0.00, 0.00, -6.97, 0.00, 0.00, 0.00, 0.00, -2.47, 0.76, 0.00, 0.00, 0.00, 0.75, -2.57, 0.00, 0.00, -6.73, 0.00, 1.54, 0.00, 0.00, -3.75, 0.72, 0.00, 1.87, 0.00, 0.00, 0.00, 0.00, 0.72, 0.00, 2.53, -5.03, -38.57, -14.13, 0.9022
False   0.24    -2.92   -1.24   0.00, -1.51, -1.06, 0.00, 0.00, 0.00, 0.00, 1.87, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 4.14, 0.00, -0.80, 0.00, -1.29, 0.00, -1.09, 1.70, 1.13, 0.00, 1.04, 0.00, 0.00, 0.00, 0.00, 0.00, -3.42, 0.00, -1.17, 0.00, 2.62, 0.00, 0.00, -2.93, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.81, 1.34, 0.00, 6.95, 3.53, 0.00, -8.89, -5.2082
```

**Comment by rogancarr** [comment] 2019-03-01 00:52
I don't have a great stand-alone sample yet, but if you want to recreate the above numbers, you can run this code in the `Microsoft.ML.Samples/` project in the repository.

```cs
public static void Example()
{
    // Create a new context for ML.NET operations. It can be used for exception tracking and logging, 
    // as a catalog of available operations and as the source of randomness.
    var mlContext = new MLContext();

    // Download and featurize the dataset.
    var data = SamplesUtils.DatasetUtils.LoadFeaturizedAdultDataset(mlContext);

    var trainer = mlContext.BinaryClassification.Trainers.LogisticRegression(); // .FastTree(); //

    // Now we train the model and score it on the transformed data.
    var model = trainer.Fit(data);
    var scoredData = model.Transform(data);

    // Create a Feature Contribution Calculator
    var featureContributionCalculator = mlContext.Model.Explainability.FeatureContributionCalculation(model.Model.SubModel, model.FeatureColumn, normalize: false);

    // Calculate the feature contributions for all features given trained model parameters
    // And don't normalize the contribution scores
    var contributionsData = featureContributionCalculator.Fit(scoredData).Transform(scoredData);
    var sampledContributions = mlContext.Data.TakeRows(contributionsData, 10);

    Console.WriteLine($"Bias: {model.Model.SubModel.Bias}");

    // Let's now walk through the first ten records and see which feature drove the values the most
    // Get prediction scores and contributions
    var scoringEnumerator = mlContext.Data.CreateEnumerable<BinaryClassificationWithContributions>(sampledContributions, false);
    Console.WriteLine("Label\tProbability\tScore\tTotalContribution\tFeature-Contributions");
    foreach (var row in scoringEnumerator)
        Console.WriteLine("{0:0.00}\t{1:0.00}\t{2:0.00}\t{3:0.00}\t{4}",row.Label, row.Probability, row.Score,
            SumVector(row.FeatureContributions)+model.Model.SubModel.Bias, GetVectorString(row.FeatureContributions)); // + 
}

private static string GetVectorString(float[] vector, string separator=", ")
{
    string output = "";
    for (int i = 0; i < vector.Length - 1; i++)
        output += $"{vector[i]:0.00}{separator}";
    output += $"{vector[vector.Length - 1]:0.0000}";
    return output;
}

private static double SumVector(float[] vector)
{
    double total = 0.0;
    for (int i = 0; i < vector.Length; i++)
        total += vector[i];
    return total;
}

private sealed class BinaryClassificationWithContributions
{
    public bool Label { get; set; }

    public float Probability { get; set; }

    public float Score { get; set; }

    public float[] FeatureContributions { get; set; }
}
```
