### ISSUE TITLE
Question about TFIDF

### ISSUE THREAD

**Issue by Jrjuniorjr** [dotnet/machinelearning#5562] opened 2020-12-19 00:39 UTC
Hi to all, I'm new on ML.NET and I'm trying to FeaturizeText with TF-IDF.
In the Jupyter Notebook and in .NET Interactive, this code gets an error:

```C#
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using Microsoft.ML.Transforms.Text;
using System.Collections.Generic;

namespace SentimentAnalysis
{
    public class Input
    {
        [LoadColumn(0)]
        public string Text { get; set; }
        [LoadColumn(1)]
        public int Rating { get; set; }
    }
    public class Output
    {
        public float[] Features { get; set; }
    }
    class Program
    {
        public static TextFeaturizingEstimator.Options GetOptions()
        {
            var vectorizedTextOptions = new TextFeaturizingEstimator.Options()
            {
                KeepDiacritics = false,
                KeepPunctuations = false,
                KeepNumbers = true,
                CaseMode = TextNormalizingEstimator.CaseMode.Lower,
                StopWordsRemoverOptions = new StopWordsRemovingEstimator.Options()
                {
                    Language = TextFeaturizingEstimator.Language.English
                },

                // ngram options
                WordFeatureExtractor = new WordBagEstimator.Options()
                {
                    NgramLength = 1,
                    UseAllLengths = false, // Produce both unigrams and bigrams
                    Weighting = NgramExtractingEstimator.WeightingCriteria.TfIdf, // TF-IDF
                },

                // chargram options
                CharFeatureExtractor = null
            };
            return vectorizedTextOptions;

        }
        static void Main(string[] args)
        {
            var context = new MLContext();
            var list = new List<Input>()
            {
                new Input()
                {
                    Text = "This is machine learning example", Rating = 4
                },
                new Input()
                {
                    Text = "I like .NET", Rating = 5
                }
            };
            var samples = context.Data.LoadFromEnumerable<Input>(list);
            var options = GetOptions();
            var transformFitted = context.Transforms.Text.FeaturizeText(
                    "Features",
                    options,
                    "Text"
                ).Fit(samples);

            var tfIdfTransformed = transformFitted.Transform(samples);

            var predictionEngine = context.Model.CreatePredictionEngine<Input, Output>(transformFitted);
            Output prediction = null;

            VBuffer<ReadOnlyMemory<char>> slotNames = default;
            tfIdfTransformed.Schema["Features"].GetSlotNames(ref slotNames);

            var tfIdfColumn = tfIdfTransformed.GetColumn<VBuffer<float>>(tfIdfTransformed.Schema["Features"]);
            var slots = slotNames.GetValues();

            Console.Write("NGrams: ");
            foreach (var featureRow in tfIdfColumn)
            {
                foreach (var item in featureRow.Items())
                {
                    Console.Write($"{slots[item.Key]}  ");
                }
                Console.WriteLine();
            }
        }
    }
}
```

And I do var slot = slotNames.GetValues() what I'm getting is:

Error: (3.1): error CS8345: The field or a self-implemented property cannot be of type 'ReadOnlySpan <ReadOnlyMemory <char>>', unless it is an instance member of a reference struct.

And in Visual Studio 2019, it works well, but when I try to loop over the columns:

```C#
       Console.Write("NGrams: ");
        foreach (var featureRow in tfIdfColumn)
        {
            foreach (var item in featureRow.Items())
            {
                Console.Write($"{slots[item.Key]}  ");
            }
            Console.WriteLine();
        }
```

It repeats some words.

For example: If I get two input: "This is a test", "I like dotnet", what I got print is:
This is a test
test I like dotnet

It is just an example.

Another question is how can I get do something like this in ML.NET:

This code is in python:

```python
docs = []
for index, row in df_balenceado.iterrows():
    docs.append(row["CleanReview-NoStemming"])

tfidf_vectorizer=TfidfVectorizer()
fitted_vectorizer=tfidf_vectorizer.fit(docs)
tfidf_vectorizer_vectors=fitted_vectorizer.transform(docs)
feature_names = tfidf_vectorizer.get_feature_names()
dictonary = pd.DataFrame(tfidf_vectorizer_vectors.todense().tolist(), columns=feature_names)
dictonary.head()
pickle.dump(fitted_vectorizer, open("tfidf_nostemming.pkl", "wb"))
dictonary = variance_threshold_selector(dictonary, 0.00005)
dictonary.to_csv("DictionaryNoStemming.csv", index=False)
```

**Comment by antoniovs1029** [comment] 2020-12-28 23:04
> And I do var slot = slotNames.GetValues() what I'm getting is: Error: (3.1): error CS8345: The field or a self-implemented property cannot be of type 'ReadOnlySpan <ReadOnlyMemory >', unless it is an instance member of a reference struct.

@eerhardt , do you know why would the user get this error on a Jupyter notebook but not on Visual Studio?

> And in Visual Studio 2019, it works well, but when I try to loop over the columns: [...] It repeats some words.

Perhaps the problem is that the `featureRow` actually is a vector (more precisely a `VBuffer<float>` of size the number of tokens you had, containing the TFIDF of the token, which might be 0. So when printing the tokens the way you do, you are actually also printing tokens that have TFIDF of 0 in the vector. Changing the code as follows seems to fix the problem:

```C#
foreach (var featureRow in tfIdfColumn)
{
    foreach (var item in featureRow.Items())
    {
        if(item.Value > 0)
            Console.Write($"({slots[item.Key]}, {item.Value})  ");
    }
    Console.WriteLine();
}
```

![image](https://user-images.githubusercontent.com/38739674/103247383-8ccb2400-491b-11eb-9f95-8334c4bf8160.png)

> Another question is how can I get do something like this in ML.NET. This code is in python.
So many things happen in that python code, and in general ML.NET might not be providing what you're doing on that code:
1. Get the TFIDF representation of your docs: you're already able to do that on the code you gave
2. Create a Pandas-like structure that has one column per each token to represent the TFIDF results: I don't think there's a straightforward way to create a new ML.NET IDataView where each column is a token that's output of the Featurizer, but in general this isn't necessary as having only one column containing the VBuffers and the slot names as described above is enough. Also, notice that there's a project called DataFrame that is compatible with ML.NET's IDataViews: [[1](https://devblogs.microsoft.com/dotnet/an-introduction-to-dataframe/
)] [[2](https://github.com/dotnet/machinelearning/issues/5347)], but I'm not sure about how the experience would be for IDataViews that have columns that contain vectors (VBuffer), and I wouldn't expect it to provide the ability to create a new DataFrame with the columns of the inner vectors.
3.  Serializing the TFIDF output: you can simply use `context.Data.SaveAsText(tfIdfTransformed, outputStream);` If you change the default options such as having a separatorChar of comma, it can output a CSV file.
4. Applying `variance_threshold_selector` to the output of TFIDF: I'm not completely sure of how the algorithm for this Sci-kit feature selection method works, but I'm afraid we don't have it on ML.NET. So my best advice would be for you to actually implement the algorithm inside a `CustomMappingTransformer` and add it to the output of the TextFeaturizer.

**Comment by eerhardt** [comment] 2021-01-04 19:59
>> And I do var slot = slotNames.GetValues() what I'm getting is: Error: (3.1): error CS8345: The field or a self-implemented property cannot be of type 'ReadOnlySpan ', unless it is an instance member of a reference struct.

> @eerhardt , do you know why would the user get this error on a Jupyter notebook but not on Visual Studio?

When you have a top-level variable in C# notebooks, behind the scenes dotnet-interactive is trying to create a field on an auto-generated class. Since you can't have a ReadOnlySpan as a field on a normal class, the C# compiler spits this error out.

cc @jonsequitur @colombod

**Comment by antoniovs1029** [comment] 2021-01-05 03:52
Thanks for the insight, @eerhardt .
I'll close this issue now, @Jrjuniorjr . Please feel free to reopen if you are still facing issues.

**Closed by antoniovs1029** 2021-01-05 03:52 UTC
Labels: P3, question
