### ISSUE TITLE
Exception during Predict 

### ISSUE THREAD

**Issue by PerfectEngineer** [dotnet/machinelearning#6307] opened 2022-08-27 07:12 UTC
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version:  ML.NET v1.7.1
 - .NET Version:  .NET 6.0
 - SciSharp.TensorFlow.Redis: 2.3.1
**Expected behavior**
Should able to get prediction 

**CODE**

BitmapImage imageAsBitmap = new BitmapImage(new Uri("D:/ImageToGetPrediction.jpeg"));
var encoder = new JpegBitmapEncoder();
encoder.Frames.Add(BitmapFrame.Create(imageAsBitmap));
var input = new Input();

using (MemoryStream ms = new MemoryStream())
{
    encoder.Save(ms);
    input.Image = ms.ToArray();
}
    var prediction = _predictor.Predict(input);

**STACKTRACE**

Error: External component has thrown an exception 

STACKTRACE:    at Tensorflow.c_api.TF_SessionRun(IntPtr session, TF_Buffer* run_options, TF_Output[] inputs, IntPtr[] input_values, Int32 ninputs, TF_Output[] outputs, IntPtr[] output_values, Int32 noutputs, IntPtr[] target_opers, Int32 ntargets, IntPtr run_metadata, SafeStatusHandle status)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.Runner.Run()
   at Microsoft.ML.Vision.ImageClassificationModelParameters.Classifier.Score(VBuffer`1& image, Span`1 classProbabilities)
   at Microsoft.ML.Vision.ImageClassificationModelParameters.<>c__DisplayClass22_0`2.<Microsoft.ML.Data.IValueMapper.GetMapper>b__0(VBuffer`1& src, VBuffer`1& dst)
   at Microsoft.ML.Data.SchemaBindablePredictorWrapperBase.<>c__DisplayClass19_0`2.<GetValueGetter>b__0(TDst& dst)
   at Microsoft.ML.Data.PredictedLabelScorerBase.EnsureCachedPosition[TScore](Int64& cachedPosition, TScore& score, DataViewRow boundRow, ValueGetter`1 scoreGetter)
   at Microsoft.ML.Data.MulticlassClassificationScorer.<>c__DisplayClass16_0.<GetPredictedLabelGetter>b__1(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)

**Comment by michaelgsharp** [comment] 2022-10-10 19:57
Clsoing this as it appears to be a duplicate of #6308 6308

**Closed by michaelgsharp** 2022-10-10 19:57 UTC
Labels: untriaged
