### ISSUE TITLE
Trouble using RobustScaler

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#5222] opened 2020-06-09 21:53 UTC
### System information

- Microsoft Windows 10 Enterprise, Version	10.0.18363 Build 18363

- ML.NET v1.5

### Issue

I'm trying to transform my dataset with the RobustScaler.  The program compiles and runs, but I get the exception:  

`Unable to find an entry point named 'RobustScalerFeaturizer_float_CreateEstimator' in DLL 'Featurizers'.`

Here is a segment of my code where the exception is thrown:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

using Microsoft.ML;
using Microsoft.ML.AutoML;
using Microsoft.ML.Data;
using Microsoft.ML.Featurizers;
.
.
.
    var trainDataView = mlContext.Data.LoadFromTextFile<ModelInput>(
        path: @"../../../data/train.csv",
        hasHeader: true,
        separatorChar: ',');

    RobustScalerTransformer model = null;
    var pipeline = mlContext.Transforms.RobustScaler("vwapGain");
    try {
      model = pipeline.Fit(trainDataView);
    } catch (EntryPointNotFoundException ex) {
      Console.WriteLine("{0}:\n   {1}", ex.GetType().Name, ex.Message);
    }
```
Here is a list of the packages in my program:

![image](https://user-images.githubusercontent.com/1317234/84204754-a16bcb80-aa60-11ea-85ae-c7776b5fdccd.png)

Any suggestions will be greatly appreciated.

Charles

**Comment by michaelgsharp** [comment] 2020-06-10 03:27
Hey @CBrauer, the issue is that we have the incorrect version of the `Featurizers` dll being linked when we create the nuget package. This one is on me as I updated the version in the source code, but did not update the version in the `.nupkgproj` file itself. 

I will create a PR shortly that will address this. A workaround for you for now would just be to manually update/install the correct version of the nuget. If you search for `Microsoft.MLFeaturizers` (note how this package doesn't have a `.` after ML) nuget package, and install the latest version of it (should be 0.4.1), it should resolve this issue.

I will leave this issue open and let the PR close it. If you have any further issues please reach back out.

**Closed** 2020-06-10 05:35 UTC
