### ISSUE TITLE
Creating both environment and context is annoying

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1045] opened 2018-09-26 20:26 UTC
This is what I have to write in the docs all the time:
```c#
// Create a new environment for ML.NET operations. It can be used for exception tracking and logging, 
// as well as the source of randomness.
var env = new LocalEnvironment();

// We know that this is a classification task, so we create a multiclass classification context: it will give us the algorithms
// we need, as well as the evaluation procedure.
var classification = new MulticlassClassificationContext(env);
```

Can we make context create the environment if they aren't provided one? And also expose it as a property?

/cc @TomFinley

**Comment by shauheen** [comment] 2018-10-05 21:55
Duplicate of #1098

**Closed by shauheen** 2018-10-05 21:55 UTC
Labels: api
