### ISSUE TITLE
Time Series support

### ISSUE THREAD

**Issue by BernhardGlueck** [dotnet/machinelearning#495] opened 2018-07-05 13:52 UTC
Quick question: I know that right now there is no real support for time series.... ( both on the data input side as well as in the implemented Learners ) 

However before i could often solve my case by windowing over the sequential stream of events i wanted to base my prediction on e.g 

For this i would need Collection support for columns... is this possible right now ? 

E.g 

class MeasurementTick  {

   DateTime TimeStamp { get; set; }
   float Temperature { get; set; }
   float Pressure { get; set; }
}

class FixedSizeMeasureMentWindow {
   IList<MeasurementTick> Ticks { get; set; }
}

Using FixedSizeMeasureMentWindow as my input data type....

**Comment by abgoswam** [comment] 2018-10-18 18:48
DRI RESPONSE : Adding support for time series is being tracked using issue #978. Planning to close this issue (duplicate of #978)

**Closed** 2018-10-22 16:28 UTC
Labels: Time Series, question
