### ISSUE TITLE
Latent Dirichlet Allocation (LDA) - how to get a list of topics?

### ISSUE THREAD

**Issue by MagicMaxxx** [dotnet/machinelearning#2197] opened 2019-01-21 13:00 UTC
### System information

- **OS version/distro**:
Windows 10 Home
- **.NET Version (eg., dotnet --info)**: 
2.1.6

### Question
Hello

I have the latest ML.NET version 0.9.0 and I'm trying to use LDA - Latent Dirichlet Allocation but can't figure out how to get a list of topics generated by LDA, can you please suggest how to do it?

Thanks!

**Comment by rogancarr** [comment] 2019-03-05 19:45
The public API for LDA does not allow for looking at the model. It comes back as an ITransformer, but there is no .Model property.	 	 	 

@shauheen  @eerhardt  @TomFinley  Flagging this as Project 13 because it's a V1 Scenario (see #2498). 
- I can inspect the topics after training an LDA transform. Easy to find via auto-complete.
I suggest that we aim for V1.1 because this would be a pure *addition* to the APIs. Is there an official Project 14 in the works?

**Comment by antoniovs1029** [comment] 2020-01-09 01:33
I will close this issue since it's a duplicate of #4322 , so that further discussion occurs there.

**Closed by antoniovs1029** 2020-01-09 01:33 UTC
Labels: P1, api, enhancement
