### ISSUE TITLE
Invalid type ('Vec<R4>') error on Training.

### ISSUE THREAD

**Issue by bzn7** [dotnet/machinelearning#558] opened 2018-07-19 13:04 UTC
### System information

- **OS version/distro**: Windows 10 17134.165
- **.NET Version (eg., dotnet --info)**: 4.7.03056

### Issue
I'm getting this exception while Train. Couldn't find any tip, please help.

`ArgumentOutOfRangeException: Source column 'Features' has invalid type ('Vec<R4>'): Expected known size vector.`

- **What did you do?**
Copied some code from iris sample to my project.
- **What happened?**
Couldn't train my model.

### Source code / logs

        public class IrisData
        {
            [Column("0")] public float[] param1 = new float[1];
            [Column("1")] public float[] param2 = new float[1000];
            [Column("2")] public float[] param3 = new float[1000];
            [Column("3")] public float[] param4 = new float[1000];
            [Column("4")] public float[] param5 = new float[1000];
            [Column("5", name: "Label")] public string Label;
        }

        public class IrisPrediction
        {
            [ColumnName("PredictedLabel")]
            public string PredictedLabels;
        }

        //Program adds some irisData to this list while working
        public static List<IrisData> History = new List<IrisData>()  { };
        
        private static PredictionModel<IrisData,IrisPrediction> readyModel;

Working code

        public static async void Learn()
        {
            readyModel = await TrainAsync();
        }

        internal static async Task<PredictionModel<IrisData, IrisPrediction>> TrainAsync()
        {
            var pipeline = new LearningPipeline();
            var data = History;
            var collection = CollectionDataSource.Create(data);

            pipeline.Add(collection);
            pipeline.Add(new ColumnConcatenator("Features", "param1", "param2", "param3", "param4", "param5"));
            pipeline.Add(new StochasticDualCoordinateAscentClassifier());

            var model = pipeline.Train<IrisData, IrisPrediction>();
            return model;
        }

**Comment by sfilipi** [comment] 2018-07-19 15:18
In your 'Source code/logs' section we can't see enough to tell what the problem is. 
Can you paste your LearningPipeline? Did you keep the 

`pipeline.Add(new ColumnConcatenator("Features", "param1", "param2", "param3", "param4", "param5"));`

I am assuming the `working code` is just extracted from the machinelearning-samples repo?

**Comment by Ivanidzo4ka** [comment] 2018-07-19 17:37
You need to specify  [VectorType(N)] on top of each array field where N is size of this array.
see https://github.com/dotnet/machinelearning/blob/8ce2a232e907d518979e7105842ae575a7427377/test/Microsoft.ML.Tests/LearningPipelineTests.cs#L85

**Comment by bzn7** [comment] 2018-07-21 17:08
> I am assuming the working code is just extracted from the machinelearning-samples repo?

@sfilipi  Actually all of code above is mine but most of my code also comes from samples repo. I just redesigned variables. You can see my new code below.

> IYou need to specify [VectorType(N)] on top of each array field where N is size of this array.

@Ivanidzo4ka I tried this but now application gets in break mode without error while train. If i debug it step by step i see same issue with that link: https://github.com/dotnet/machinelearning/issues/285#issuecomment-400787100

My new code like this:
(Start point: MLCore.Learn(); )

```
class MLData
    {
        public class IrisPrediction
        {
            [ColumnName("PredictedLabel")]
            public string PredictedLabels;
        }

        public class IrisData
        {
            [Column("0")] public double param1;
            [Column("1")] [VectorType(1000)] public float[] param2;
            [Column("2")] [VectorType(1000)] public float[] param3;
            [Column("3")] [VectorType(1000)] public float[] param4;
            [Column("4")] [VectorType(1000)] public float[] param5;
            [Column("5", name: "Label")] public string Label;
        }

        public static List<IrisData> History = new List<IrisData>() { };  //Program adds some irisData to this list while working before train
    }
```

```
class MLCore
    {
        private static PredictionModel<IrisData,IrisPrediction> readyModel;

        internal static async Task<PredictionModel<IrisData, IrisPrediction>> TrainAsync()
        {
            var data = History;

            var pipeline = new LearningPipeline()
            {
                CollectionDataSource.Create(data),
                new ColumnConcatenator(outputColumn: "Features", "param1", "param2", "param3", "param4", "param5"),
                new StochasticDualCoordinateAscentClassifier()
            };

            var model = pipeline.Train<IrisData, IrisPrediction>();
            return model;
        }

        public static async void Learn()
        {
            readyModel = await TrainAsync();
        }

        public static void Think()
        {
            try
            {
                var prediction = readyModel.Predict(new IrisData()
                {
                    param1 = PGlobals.param1,
                    param2 = PGlobals.param2,
                    param3 = PGlobals.param3,
                    param4 = PGlobals.param4,
                    param5 = PGlobals.param5,
                });

                PGlobals.predictedResult = prediction.PredictedLabels;
            }

            catch
            {
                //Nothing
            }

        }
    }
```
Thank you for your help.

**Comment by Ivanidzo4ka** [comment] 2019-02-06 23:52
Considering we no longer use this API, i'm closing this issue.

**Closed by Ivanidzo4ka** 2019-02-06 23:52 UTC
