### ISSUE TITLE
NullReferenceException when training data

### ISSUE THREAD

**Issue by ivan-pelly** [dotnet/machinelearning#6470] opened 2022-11-24 17:03 UTC
**System Information (please complete the following information):**
 - OS & Version: Windows 10 
 - ML.NET Version: Microsoft.ML 2.0.0, Microsoft.ML.AutoML 0.20.0
 - .NET Version: NET 6.0

**Describe the bug**
Training following the example at https://github.com/jwood803/MLNetExamples/tree/master/MLNetExamples/AutoML throws a System.AggregateException

**To Reproduce**
1. Load the attached project
2. Edit line 6 in Program.cs to point to the path of the provided data file on your system
3. Run the code

**Expected behavior**
The code executes to completion.

[NDML.zip](https://github.com/dotnet/machinelearning/files/10086423/NDML.zip)

**Comment by ivan-pelly** [comment] 2022-11-25 21:39
Additional error info attached.
![mlerror](https://user-images.githubusercontent.com/18688474/204057556-8f613453-e3ab-4fa7-9ecf-340845038da9.jpg)

**Comment by michaelgsharp** [comment] 2022-11-28 19:49
@LittleLittleCloud looks like this is using AutoML. Any ideas?

@luisquintanilla are you familiar with that sample by Jon?

**Comment by ivan-pelly** [comment] 2022-11-28 23:00
Thanks for giving this a look. Happy to provide any additional info as needed.

**Comment by luisquintanilla** [comment] 2022-11-29 19:44
Hi @ivan-pelly,

Thanks for your question. This looks like it's using the old AutoML API. We recommend you use the new AutoML API. Check out this [guide](https://learn.microsoft.com/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api) for more information. You can also find accompanying [samples](https://github.com/dotnet/machinelearning-samples/blob/main/samples/csharp/getting-started/MLNET2/README.md).

Closing this issue for now. If you run into issues with the new AutoML API, please feel free to open a new issue.

**Closed by luisquintanilla** 2022-11-29 19:44 UTC
Labels: AutoML.NET, untriaged

**Comment by ivan-pelly** [comment] 2022-11-29 21:22
Hi @luisquintanilla  - thanks for the info. My project is using Microsoft.ML.AutoML version 0.20.0, which it reports as the latest stable version. Is there a more recent version I'm not seeing, or are you referring to a different package? Any guidance appreciated. Thank you!

**Comment by ivan-pelly** [comment] 2022-11-29 21:26
![0 20 0](https://user-images.githubusercontent.com/18688474/204651233-ed3b3982-4a07-4540-87b5-ed5a088301a9.jpg)

**Comment by luisquintanilla** [comment] 2022-11-29 21:26
@ivan-pelly 2.0.0 is the latest version. However, the old APIs are still part of that package. For example, your call to `CreateRegressionExperiment` and `Progress<T>` are the old APIs. I would recommend looking at the how-to guide and samples which show the new API.

**Comment by ivan-pelly** [comment] 2022-11-29 21:29
Got it - thanks! So the old and new api's are in the same package? Is there a way to distinguish which is which, or would just need to follow the docs and hope I don't call something old? Cheers.
