### ISSUE TITLE
How to continue training based on the existing model?

### ISSUE THREAD

**Issue by 22140505** [dotnet/machinelearning#517] opened 2018-07-10 16:32 UTC

**Comment by ErcinDedeoglu** [comment] 2018-07-10 18:58
+1

**Comment by zeahmed** [comment] 2018-07-10 21:49
The core API does have this feature implemented. Please see the following interface and its implementations. However, current front facing C# API does not expose incremental training feature.
https://github.com/dotnet/machinelearning/blob/f7a55268646363e625cfe8e40b30a9fc5cc6298e/src/Microsoft.ML.Core/Prediction/ITrainer.cs#L143

If you follow the new API #371 test cases and adapt your code in this format you might be able to use it.
https://github.com/dotnet/machinelearning/tree/master/test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation

Please look at the following trainers for more details (this is the rough list).

- AveragedLinearTrainer
- LbfgsTrainerBase
- OnlineLinearTrainer
- LogisticRegression
- AveragedPerceptronTrainer
- FieldAwareFactorizationMachineTrainer
- LinearSvm
- MulticlassLogisticRegression
- OnlineGradientDescentTrainer
- PoissonRegression
- StochasticGradientDescentClassificationTrainer

We will have concrete documentation and sample code available once we are close to releasing new API #371.

**Comment by Ivanidzo4ka** [comment] 2018-10-18 23:40
DRI RESPONSE: I'm considering this as duplicate of #470.

**Closed by Ivanidzo4ka** 2018-10-18 23:40 UTC
Labels: documentation
