### ISSUE TITLE
Far more weights than features when obtaining PFI Metrics for Binary Classification

### ISSUE THREAD

**Issue by HamzahIqbal765** [dotnet/machinelearning#4296] opened 2019-10-04 15:22 UTC
Windows 10 v. 1809
- NET Core SDK (3.0.100): 

I have used trained model with numerical features, and this has successfully returned PFI metrics, whereby the number of weights is equivalent to the number of features.
However, the issue arises when  I pass a dataset without numerical features. When the features are categorical and strings, I use one hot encoding to convert the features into the appropriate vectors. 
In both the former and present case, I use a FastForest trainer. 
When I follow the documentation for PFI, the model is trained fine, but when I run the code:

` VBuffer<float> weights = default;
linearPredictor.Model.SubModel.GetFeatureWeights(ref weights);`

I get over 80 weights when I only have 12 features in my data. And I cannot continue following the documentation since it matches the index of the weights against the index of the feature.

Is there a way to get the PFI when using OneHotEncoding?

**Comment by antoniovs1029** [comment] 2019-10-04 16:39
Could you please provide sample code to see how you built your model and replicate your problem?  

Thanks.

**Comment by famschopman** [comment] 2019-10-05 18:08
I solved this by checking a number of parametes that are added to features add by the normalization. You can check for IsHidden, Label and Features.

var sortedIndices = permutationMetrics.Select((metrics, index) => new { index, metrics.AreaUnderRocCurve })
                .OrderByDescending(feature => Math.Abs(feature.AreaUnderRocCurve.Mean))
                .Select(feature => feature.index);

 foreach (int i in sortedIndices)
            {
                if (transformedData.Schema[i].IsHidden || transformedData.Schema[i].Name == "Label" || transformedData.Schema[i].Name == "Features")
                {
                    continue;
                }

                  // do your thing
            }

**Comment by yaeldekel** [comment] 2019-10-07 06:58
Hi @HamzahIqbal765,
PFI always operates on the numerical features that were passed to the trainer (in your case, FastForest trainer). When the original features in the dataset are categorical or strings, this means that the trainer sees the output of the one-hot encoding transformer, so this is also the set of features that PFI uses.
We have an open issue #4266 to make PFI support raw features, maybe @najeeb-kazmi would have some comments about your scenario?

**Comment by HamzahIqbal765** [comment] 2019-10-07 09:15
@antoniovs1029 this is the code I am using: 
`
IDataView trainingDataView = 
mlContext.Data.LoadFromTextFile<BackgroundVariablesInput>(
                                            path: filepath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

 var featureColumns = trainingDataView.Schema.Select(x => x.Name).Where(x => x != "Label").ToArray();

var dataProcessPipeline =mlContext.Transforms.Categorical.OneHotEncoding(new[] { new InputOutputColumnPair("Disability", "Disability"), new InputOutputColumnPair("PropertyType"), new InputOutputColumnPair("AgeGroup"), new InputOutputColumnPair("BusinessActivityGroup"), new InputOutputColumnPair("BusnessUnit"), new InputOutputColumnPair("Gender"), new InputOutputColumnPair("Region"), new InputOutputColumnPair("TimeTaken"), new InputOutputColumnPair("Contractor"), new InputOutputColumnPair("Trades") })
                                      .Append(mlContext.Transforms.Concatenate("Features", new[] { "Disability", "PropertyType", "AgeGroup", "BusinessActivityGroup", "BusnessUnit", "Gender", "Region", "TimeTaken", "Contractor", "Trades", "durationbetweenrepaircompleteandsurveycomplete", "PreviousRepairs" }))
                                      .AppendCacheCheckpoint(mlContext);


            var trainer = mlContext.BinaryClassification.Trainers.FastForest(numberOfLeaves: 113, minimumExampleCountPerLeaf: 1, numberOfTrees: 100, labelColumnName: "Label", featureColumnName: "Features");
            var pipeline = dataProcessPipeline.Append(trainer);

 var model = pipeline.Fit(trainingDataView);
            var transformedData = model.Transform(trainingDataView);

var linearPredictor = model.LastTransformer;

// var calibratedEstimator = mlContext.BinaryClassification.Calibrators.Platt();
          //  var calibratedTransformer = calibratedEstimator.Fit(transformedData);
        //    var finalData = calibratedTransformer.Transform(transformedData);

            Console.WriteLine("Starting PFI");
            var permutationMetrics = mlContext.BinaryClassification.PermutationFeatureImportance(linearPredictor, transformedData, permutationCount: 5);
            Console.WriteLine("Ended PFI");
            
 VBuffer<float> weights = default; 
linearPredictor.Model.GetFeatureWeights(ref weights);

var sortedIndices = permutationMetrics.Select((metric, index) => new { index, metric.AreaUnderRocCurve }).OrderByDescending(feature => Math.Abs(feature.AreaUnderRocCurve.Mean))
                .Select(feature => feature.index);

  foreach (int i in sortedIndices)
            {
                Console.WriteLine("");
                string line = $"{featureColumns[i]}, {weights.GetValues().ToArray()[i]},{metrics[i].AreaUnderRocCurve.Mean}, {metrics[i].AreaUnderRocCurve.StandardError * 1.96}," +
                    $"{metrics[i].Accuracy.Mean}, {metrics[i].Accuracy.StandardError * 1.96}";
                Console.WriteLine(line);
                csv.AppendLine(line);
            }
`

**Comment by najeeb-kazmi** [comment] 2020-02-20 02:57
Duplicate of #4266

**Closed by najeeb-kazmi** 2020-02-20 02:57 UTC
Labels: P2, enhancement
