### ISSUE TITLE
FileNotFound error when saving the model.zip file on AML

### ISSUE THREAD

**Issue by JulioAlbinatiCortez** [dotnet/machinelearning#5116] opened 2020-05-11 21:07 UTC
### System information

- **OS version/distro**: Not sure, running on AML Compute.
- **.NET Version (eg., dotnet --info)**: .NET Core 2.0

### Issue

- **What did you do?**
I have an AML pipeline where I use ML.NET to train a LightGBM model and save results on a blob storage. This pipeline reads data from ADLS.
- **What happened?**
The training stage failed with an exception that suggests an I/O error (file not found).
- **What did you expect?**
This same pipeline have worked in the recent past. This is the first time I'm seeing this error.

### Source code / logs

Logs from the training stage:
_[1] 'Loading data for LightGBM' finished in 00:27:01.1484891.
[2] 'Training with LightGBM' started.
.***** Unexpected failure. Please refer to https://aka.ms/MLNetIssue to file an issue with details *****
***** Error log has been saved to '/tmp/TLC/Error_20200511_192219_facb0cb4-1e59-4354-b1c2-870a44ba1ca4.log', please refer to https://aka.ms/MLNetIssue to file an issue with details *****
===== Begin detailed dump =====
(1) Unexpected exception: Could not find file '/mnt/batch/tasks/shared/LS_root/jobs/devexperimentation/azureml/bdaad31a-ef2f-47cd-b99b-85119e487d7c/mounts/workspaceblobstore/azureml/bdaad31a-ef2f-47cd-b99b-85119e487d7c/ModelOutput/model.zip'., 'System.IO.FileNotFoundException'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.ML.Data.SimpleFileHandle.OpenReadStream() in /machinelearning/src/Microsoft.ML.Core/Data/IFileHandle.cs:line 193
   at Microsoft.ML.Tools.SavePredictorCommand.Run() in /machinelearning/src/Microsoft.ML.Data/Commands/SavePredictorCommand.cs:line 82
   at Microsoft.ML.Tools.Maml.MainCore(IHostEnvironment env, String args, Boolean alwaysPrintStacktrace) in /machinelearning/src/Microsoft.ML.Maml/MAML.cs:line 142
====== End detailed dump =====_

**Comment by antoniovs1029** [comment] 2020-05-12 04:11
Hi, @JulioAlbinatiCortez .

I don't know what could be causing this error, and the stack trace look somewhat odd to me. Can you please share the code you're trying to run and a sample dataset to try to reproduce this error?

> This same pipeline have worked in the recent past. This is the first time I'm seeing this error.
When was the last time it worked for you? Has anything changed in your environment since that last time? What version of ML.NET are you using, and have you recently updated that?

**Comment by antoniovs1029** [comment] 2020-06-02 22:22
Hi, I will close this issue, since we haven't gotten a reply to my last message. Please, feel free to reopen, if you are still facing this problem.

PS: Something noticeable about your issue, is the stacktrace, as it points that you're calling the `Microsoft.ML.Tools.Maml.MainCore`. "MAML" is a utility used internally by the ML.NET team to automate tests, and currently we don't publicly advertise or support its usage by external users. So I do wonder how did you got to call that tool? Maybe I'm missing something 😕 ❓

**Closed by antoniovs1029** 2020-06-02 22:22 UTC
Labels: loadsave, need info
