### ISSUE TITLE
how to pass dynamics created class or object in function In of TRow type

### ISSUE THREAD

**Issue by jigarhshah17** [dotnet/machinelearning#4586] opened 2019-12-18 14:00 UTC
https://github.com/dotnet/machinelearning/blob/290e0695b22cf9c6f49fcd222b10553b5a19a63a/src/Microsoft.ML.Data/Model/PredictionEngineExtensions.cs#L27

 MLContextRef.Model.CreatePredictionEngine(Of TRow, TDst)(loadedModel) 

how to pass dynamics created class or object in above function In of TRow type

**Comment by najeeb-kazmi** [comment] 2020-01-28 01:56
@jigarhshah17 This method in particular is not meant for public consumption. It is used internally by the following public API:
https://github.com/dotnet/machinelearning/blob/290e0695b22cf9c6f49fcd222b10553b5a19a63a/src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs#L312
https://github.com/dotnet/machinelearning/blob/290e0695b22cf9c6f49fcd222b10553b5a19a63a/src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs#L329


Let's imagine you trained a `model` on the [Iris](https://github.com/dotnet/machinelearning/blob/master/test/data/iris.txt) dataset, where the problem is multiclass classification.

You define your input and output classes like so:
```csharp
private class IrisInput
{
    public string Label { get; set; }
    public float SepalLength { get; set; }
    public float SepalWidth { get; set; }
    public float PetalLength { get; set; }
    public float PetalWidth { get; set; }
}

private class IrisPrediction
{
    [ColumnName("Data")]
    public string PredictedClass { get; set; }
}
```
You can then do prediction like this:
```csharp
var predictionFunc = mlContext.Model.CreatePredictionEngine<IrisInput, IrisPrediction>(model);

var prediction = predictionFunc.Predict(new IrisInput
{
    // Note that you do not need the input label to make a prediction. If you do include the input
    // label, it will be ignored for prediction purposes.
    SepalLength = 4.1f,
    SepalWidth = 0.1f,
    PetalLength = 3.2f,
    PetalWidth = 1.4f
});
```

I am closing this issue. Please feel free to reopen if something is not addressed.

**Closed by najeeb-kazmi** 2020-01-28 01:56 UTC
Labels: P3
