### ISSUE TITLE
Why I can't just pass file name to DataReader.Read method?

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1041] opened 2018-09-26 19:53 UTC
```
ConsoleEnvironment env = new ConsoleEnvironment();
var reader = TextLoader.CreateReader(env, row => (label: row.LoadText(0), image: row.LoadText(1));
var data = reader.Read("file.csv");
```
will force me to cast file name to MultifileSource. Can I just pass filename if I have only one file?

**Comment by shauheen** [comment] 2018-10-05 21:57
Duplicate of #1090

**Closed by shauheen** 2018-10-05 21:57 UTC
Labels: api
