### ISSUE TITLE
Unhandled Exception Value cannot be null. (Parameter 'libraryPath')

### ISSUE THREAD

**Issue by bhrnjica** [dotnet/machinelearning#4466] opened 2019-11-11 16:18 UTC
### System information

- **OS version/distro**:Windows 10
- **.NET Version (eg., dotnet --info)**: 3.0.1 and 2.1.8 
- **.NET Try Version**: Tool 'dotnet-try' (version '1.0.19553.4') and (version '1.0.19558.9')
### Issue
When I run training with LightGBM within Visual Studio evrything is ok. 
However, if I run the same code in .NET Juypter Notebook with version (`(version '1.0.19553.4')` or `(version '1.0.19558.9')`) got the following exception: 
```
Unhandled Exception Value cannot be null. (Parameter 'libraryPath')
```

- **What did you do?** 
Tried to execute the following code:
```csharp
// Define LightGbm algorithm estimator
IEstimator<ITransformer> lightGbm = mlContext.MulticlassClassification.Trainers.LightGbm();
//train the ML model
TransformerChain<ITransformer> model = dataPipeline.Append(lightGbm).Fit(trainData);
```

- **What happened?**
The exception is thrown.
- **What did you expect?**
Normal execution without Exception.
### Source code / logs
```Unhandled Exception
Value cannot be null. (Parameter 'libraryPath')
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at MLS.Agent.NativeAssemblyLoadHelper.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath) in F:\workspace\_work\1\s\MLS.Agent\NativeAssemblyLoadHelper.cs:line 47
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmInterface.DatasetCreateFromSampledColumn(IntPtr sampleValuePerColumn, IntPtr sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String parameters, IntPtr& ret)
   at Microsoft.ML.Trainers.LightGbm.Dataset..ctor(Double[][] sampleValuePerColumn, Int32[][] sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String param, Single[] labels, Single[] weights, Int32[] groups)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.CreateDatasetFromSamplingData(IChannel ch, Factory factory, Int32 numRow, String param, Single[] labels, Single[] weights, Int32[] groups, CategoricalMetaData catMetaData, Dataset& dataset)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.LoadTrainingData(IChannel ch, RoleMappedData trainData, CategoricalMetaData& catMetaData)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Submission#17.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

```

**Comment by harishsk** [comment] 2019-11-13 00:49
Can you please try adding this to your notebook?
```
#r "nuget:Microsoft.ML.LightGBM,1.4.0"
```

**Comment by eerhardt** [comment] 2019-11-13 15:26
@bhrnjica - can you attach the full notebook file?

cc @jonsequitur @colombod

**Comment by harishsk** [comment] 2019-11-13 17:38
Without the reference to the LightGBM nuget that I mentioned above, I did get an error, but a different error than what you have reported. The error that you are reporting implies that the code was unable to load the LightGBM native dll. That binary should have been downloaded as a dependent nuget of the Microsoft.ML.LightGBM package. 

So, if you have a reference to the Microsoft.ML.LightGBM package, you shouldn't be seeing the error. If not, can you please take a look at your <userdir>\.nuget\packages\ and let us know if you see the lightgbm folder and what versions have been downloaded?

Also, as @eerhardt suggested, it would be great if you could attach the full notebook.

**Comment by bhrnjica** [comment] 2019-11-13 19:51
Yes sure,
the complete notebook is located at https://github.com/bhrnjica/notebooks/blob/master/net_jupyter_notebook_part2.ipynb

**Comment by eerhardt** [comment] 2019-11-13 20:27
This is a known issue with using NuGet packages that contain native assets.

See 

https://github.com/dotnet/try/issues/594
https://github.com/dotnet/try/issues/350

To workaround it, move the 

```
#r "nuget:Microsoft.ML.LightGbm"
```

To be the first line in the notebook.

**Comment by eerhardt** [comment] 2019-11-13 20:29
Closing as a dupe of the above dotnet-try bugs. Let me know if the suggested workaround doesn't work. We are actively working on making this scenario (native assembly loading) better.

**Closed by eerhardt** 2019-11-13 20:29 UTC
