### ISSUE TITLE
FastTree uses lots of memory with dropout on

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#1781] opened 2018-11-29 19:53 UTC
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1

### Issue

- **What did you do?**
Ran FastTreeRegressor with DropoutRate > 0.

- **What happened?**
Consumed around 15 GB of memory. Memory usage increased linearly with # of trees

Running FastTreeRegressor with DropoutRate > 0 leads to much higher memory consumption than when DropoutRate = 0. It used approx 14 GB more for 200 trees, and ran into an out of memory exception for 500 trees. Perhaps there is a leak? (Turning on DropoutRate seemed to consistently cause memory footprint to rise significantly.)

**Comment by TomFinley** [comment] 2018-11-29 23:27
I don't think it's a leak. It achieves dropout by memorizing each score per document, per tree.

So, not really a "bug" per se. Not great, but expected and not a bug.

**Comment by daholste** [comment] 2018-11-30 04:01
really interesting -- thank you, Tom!

**Comment by shauheen** [comment] 2019-01-08 19:14
Closing this issue. @daholste please feel free to reopen if you have further questions.

**Closed by shauheen** 2019-01-08 19:14 UTC
Labels: enhancement
