### ISSUE TITLE
DataFrame.LoadCSV converts 289203891 to System.Single and the data is rounded to 289203900.

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [dotnet/machinelearning#6221] opened 2022-06-09 04:35 UTC
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: Microsoft.Data.Analysis 0.19.1
 - .NET Version: .NET 5.0

**Describe the bug**
DataFrame.LoadCSV converts 289203891 to System.Single and the data is rounded to 289203900.

I use the DataFrame.LoadCSV function to load the CSV file to create a data frame. The content in the CSV file is:

```
Instrument,Value,Date
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/16/2022 12:00:00 AM
TEST,289203891,5/13/2022 12:00:00 AM
```
Run the following code:

```
var df = DataFrame.LoadCsv("test.csv");
            Console.WriteLine(df);
            Console.WriteLine(df.Info());
```
The output is:
```
nstrumentValue     Date
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/16/2022 12:00:00 AM
TEST      289203900 5/13/2022 12:00:00 AM

Info      InstrumentValue     Date
DataType  System.StringSystem.SingleSystem.DateTime
Length (excluding null values)20        20        20
```

From the output, DataFrame.LoadCSV uses Single.System to store the 289203891 which causes the data to be rounded to 289203900.

**To Reproduce**
1. Create the test.csv file that contains the following data

```
Instrument,Value,Date
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/17/2022 12:00:00 AM
TEST,289203891,5/16/2022 12:00:00 AM
TEST,289203891,5/13/2022 12:00:00 AM
```
3. Run the following code with .NET 5.0

```
using System;
using Microsoft.Data.Analysis;
namespace ConsoleApp18
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var df = DataFrame.LoadCsv("test.csv");
            Console.WriteLine(df);
            Console.WriteLine(df.Info());
        }
    }
}
```
5. Check the output the 289203891 is rounded to 289203900

```
Hello World!
InstrumentValue     Date
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/17/2022 12:00:00 AM
TEST      289203900 5/16/2022 12:00:00 AM
TEST      289203900 5/13/2022 12:00:00 AM

Info      InstrumentValue     Date
DataType  System.StringSystem.SingleSystem.DateTime
Length (excluding null values)20        20        20

```

**Expected behavior**
The data in the DataFrame must not be rounded. 

**Screenshots, Code, Sample Projects**
```
using System;
using Microsoft.Data.Analysis;
namespace ConsoleApp18
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var df = DataFrame.LoadCsv("test.csv");
            Console.WriteLine(df);
            Console.WriteLine(df.Info());
        }
    }
}
```

**Additional context**
The application can load many CSV content so it is unable to determine the data types of columns in advance. I need to use the guessing feature in the DataFrame.LoadCSV to determine the correct data types.

**Comment by dakersnar** [comment] 2022-09-08 16:23
After some discussion, I've determined this is intended behavior. Numeric types are assumed to be System.Single unless otherwise specified by the user. If you intend to store that column as 32-bit integers, you can specify the types like so:

`var df = DataFrame.LoadCsv("test.csv", dataTypes: new Type[] { typeof(string), typeof(int), typeof(DateTime) });`

Let me know if that solves your issue. Closing this for now.

**Closed by dakersnar** 2022-09-08 16:23 UTC
Labels: loadsave, Microsoft.Data.Analysis
