### ISSUE TITLE
CrossValidation fails with a valid pipeline

### ISSUE THREAD

**Issue by EduardoGarcias** [dotnet/machinelearning#544] opened 2018-07-17 19:40 UTC
### System information

- **Windows 10 Home (1803) - 64bit**:
- **.NET Version 2.1.202**: 
- **WPF application with includes class libraries in .net 4.7 framework version**:

### Issue

It is not possible for me to perform a CrossValidation on a Pipline, which I use for training my model. The training is performed without any issues. Normal evaluation works correctly (using classes like BinaryClassificationEvaluator or RegressionEvaluator) but the CrossValidation ends with an error. The error is as follows:
> InvalidOperationException: No valid training instances found, all instances have missing features.

### Source code / logs

- Pipeline body is like:
`          
     
                new TextLoader(filePath).CreateFrom<ReopenedIssueData>(),
                new TextFeaturizer(Columns.Environment, Columns.Environment),
                new TextFeaturizer(Columns.Type, Columns.Type),
                new TextFeaturizer(Columns.ProjectName, Columns.ProjectName),
                new TextFeaturizer(Columns.AsigneeEmail, Columns.AsigneeEmail),
                new TextFeaturizer(Columns.ReporterEmail, Columns.ReporterEmail),
                new ColumnConcatenator(
                    Columns.Features,
                    Columns.Environment,
                    Columns.Type,
                    Columns.CommentsCount,
                    Columns.CommentsLenght,
                    Columns.ReporterCommentsCount,
                    Columns.ProjectName,
                    Columns.AsigneeEmail,
                    Columns.ReporterEmail),
                new FastTreeBinaryClassifier(),
                new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn=Columns.PredictedLabel   }
                    
`

- And the StackTrace is as follows:

>  at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.Run()
   at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAllNonMacros()
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
   at Microsoft.ML.Models.CrossValidator.CrossValidate[TInput,TOutput](LearningPipeline pipeline)
   at RepositoryAnalyser.MachineLearning.Services.TrainingModelEvaluator.CrossValidate[TData,TPrediction](LearningPipeline pipeline, MachineLearningMechanism mechanism, Int32 numOfFolds)

**Comment by jwood803** [comment] 2018-07-17 20:33
Hey, @EduardoGarcias! I'm just curious, how are you calling the cross validation code? I ran into an issue with it as well, but once I filled in the `Kind` property on it, it all works. Maybe try something like this?

```csharp
var crossValidator = new CrossValidator() { Kind = MacroUtilsTrainerKinds.SignatureRegressorTrainer };
```

**Comment by EduardoGarcias** [comment] 2018-07-18 05:48
Thank you for your response. Indeed I was calling the cross validator object without the `Kind` property filled, but unfortunately,  after the change, the error still occurs.

My present cross validation code is as follows:

            var crossValidator = new CrossValidator()
            {
                NumFolds = numOfFolds,
                Kind = MacroUtilsTrainerKinds.SignatureBinaryClassifierTrainer
            };
            var result = crossValidator.CrossValidate<TData, TPrediction>(pipeline);

**Comment by shauheen** [comment] 2018-07-18 13:05
Thanks @EduardoGarcias and @jwood803 . What are you using for the NumFolds? Is your code somewhere on GitHub that I could perhaps take a look?

**Comment by EduardoGarcias** [comment] 2018-07-18 14:00
NumFolds is an integer number, its value is 2 by default (also in this case).

Code is not accessible via github, but I can provide any details needed for solving the problem.

**Comment by Zruty0** [comment] 2018-07-20 15:54
@EduardoGarcias , this is an interesting problem, which is not obvious to me.
The error you mentioned could be caused by multiple reasons:
- Your training data is so small that one of the cross-validation folds ended up empty
- Your features contain missing values. 
- Your TextLoader specification doesn't match the file you're reading (which causes some features to become missing)

Maybe there's something else that I skipped, but these were my top thoughts.
Unfortunately, there's little else we can help with, if we can't see a sample of your `filePath` file and the definition of your `ReopenedIssueData` class.

**Comment by EduardoGarcias** [comment] 2018-07-21 15:35
@Zruty0  @shauheen @jwood803 

I've prepared a small console project, where it is possible to reproduce the error.
It can be found at: https://github.com/EduardoGarcias/CrossValidationIssueSample

**Comment by Zruty0** [comment] 2018-07-23 17:35
@EduardoGarcias , I downloaded your project, and I noticed that your data file `CrossValidationIssueSample/CrossValidationIssueSample/Data/test_generated.data` contains the UTF-8 BOM `EF BB BF` at the beginning of each line. 

This messes up our `TextLoader`, so it cannot parse the first column `Label` as a proper bool on all lines except the first one. You can see evidence of this in the standard error stream.

This means that the `TextLoader` will read a 'missing value' into `Label` column for all rows except the first one.

Cross-validation of one fold will 'succeed' (it will 'train' on one remaining example with a valid label), and the cross-validation of the other fold will fail, since there will be no valid examples. This is the ultimate exception message that you see.

I made a crude hack to strip away all the BOMs from the file, just to verify that it was the issue, and it was.

**Comment by EduardoGarcias** [comment] 2018-07-25 09:49
@Zruty0 
Solution you proposed is working perfectly, so the error is no longer valid in this case. Thank you a lot for your help and engagement.

Anyway, I think that it would be perfect to have an improvement for `TextLoader`, that the built-in conversion would be proceeded to change formats containing metadata like BOMs to their raw substitutes to avoid either such or similar issues in the future.

**Comment by Zruty0** [comment] 2018-07-25 15:37
@TomFinley has looked at this issue, and he can clarify if I'm saying the wrong thing. Basically, the BOM is legal at the very beginning of the UTF-encoded file. If BOMs appear in the middle of the file, the parser should not fail (for handling legacy data), but it is free to do one of the 'sensible' things:
- Treat the BOM as a 0-width unbreakable space.
- Treat the BOM as a 'nonsense character'.

As far as I can tell, our `TextLoader` is effectively choosing the 2nd option. While we could move to the 1st option, I would personally prefer to not tweak the handling of these edge cases, unless the current behavior is a bug.

I would also say that the amount of feedback is adequate: we print `stderr` messages that 'invalid value encountered' in lots of the lines in the file, as well as a message that 'all but one line had parser errors': these should alert the user to parsing issues. 

The only thing don't like in how we handle this case is that we finally crash with `all instances have missing features`. It should be `all instances have missing features` **`or labels`**.

Other than this, I would close this issue.

**Comment by Ivanidzo4ka** [comment] 2018-10-19 00:07
DRI RESPONSE: I'm considering this issue answered and intent to close it within next few days, unless some one objects to it.

**Closed** 2018-10-22 17:50 UTC
Labels: Answered
