### ISSUE TITLE
Structure of a regression tree

### ISSUE THREAD

**Issue by hrkrx** [dotnet/machinelearning#521] opened 2018-07-11 13:44 UTC
I want to visualize a regression tree.
So i got one form my trained model.

But now i am wondering how the object (RegressionTree from Microsoft.ML.Runtime.FastTree.Internal) is structured and how i can obtain a connected tree from that object.

Only for display purposes i have a class like this:

```
public class TreeNode
{
     public List<TreeNode> Children;
     public TreeNode Parent;
     public string Content;
     [...]
}
```

and i am struggling to connect the values of the arrays in RegressionTree to a TreeNode based tree.

Thank you for your time!

**Comment by hrkrx** [comment] 2018-07-12 12:54
I created a StackOverflow question for this, where my thoughts on this are documented. I think i got the answer myself so i will close this issue once i am sure.

https://stackoverflow.com/questions/51301772/structure-of-a-binary-tree

**Comment by Ivanidzo4ka** [comment] 2018-07-12 23:13
let say you get predictor from the model and this is ITreeEnsemble predictor
```
var treeEnsemble = predictor as ITreeEnsemble;
if (treeEnsemble == null)
{
    var calibratedPredictor = predictor as CalibratedPredictorBase;
    if (calibratedPredictor != null)
        treeEnsemble = calibratedPredictor.SubPredictor as ITreeEnsemble;
}
```
you can use this code to create list of decision trees:
```
            _trees = treeEnsemble.GetTrees() as ITree<VBuffer<Float>>[];
            var decisionTrees = new List<DecisionTreeData>();
            foreach (var tree in _trees)
            {
                var decisionTree = new DecisionTreeData();
                decisionTree.Structure = new TreeStructure(tree.LteChild, tree.GtChild);
                var interiorNodes = new List<NodeData>();
                for (var i = 0; i < tree.NumNodes; i++)
                {
                    var node = tree.GetNode(i, false, _featureNameCollection);
                    interiorNodes.Add(new NodeData
                    {
                        FeatureName = GetValue<string>(node.KeyValues, NodeKeys.SplitName),
                        SplitGain = GetValue<double>(node.KeyValues, NodeKeys.SplitGain),
                        ToolTipThreshold = GetValue<string>(node.KeyValues, NodeKeys.Threshold),
                        Threshold = GetValue<string>(node.KeyValues, NodeKeys.Threshold).Split(new[] { ' ' }, 2)[1],
                        GainValue = GetValue<double>(node.KeyValues, NodeKeys.GainValue),
                        PreviousLeafValue = GetValue<double>(node.KeyValues, NodeKeys.PreviousLeafValue),
                        Extras = GetValue<string>(node.KeyValues, NodeKeys.Extras),
                        NodeIndex = i,
                        IsFeatureIdSet = false
                    });
                }
                decisionTree.InteriorNodeData = interiorNodes.ToArray();

                var leafNodes = new List<NodeData>();
                for (var i = 0; i < tree.NumLeaves; i++)
                {
                    var node = tree.GetNode(i, true, _featureNameCollection);
                    leafNodes.Add(new NodeData
                    {
                        LeafValue = GetValue<double>(node.KeyValues, NodeKeys.LeafValue),
                        Extras = GetValue<string>(node.KeyValues, NodeKeys.Extras),
                        IsLeaf = true,
                        NodeIndex = ~i
                    });
                }
                decisionTree.LeafNodeData = leafNodes.ToArray();
                decisionTrees.Add(decisionTree);
            }

            _decisionTrees = decisionTrees.ToArray();
        }
```

Hope this would help.

**Comment by mjmckp** [comment] 2018-07-13 06:46
How do you do get the original `predictor` object in your example above?  Using the output of `pipeline.Train<Data, Prediction>()` doesn't work, is this even possible using public methods and interfaces?

**Comment by rauhs** [comment] 2018-07-13 11:08
Could we add a wiki to the project? This kind of code snippet is pretty useful. It could live in the wiki.

**Comment by Ivanidzo4ka** [comment] 2018-07-13 20:00
@mjmckp, oh it's easy (as long as you work on this project for few years)
save your model to file via WriteAsync
then:
```
            IPredictor predictor;
            using (var modelStream = new FileStream(modelFileName, FileMode.Open, FileAccess.Read))
                SavePredictorUtils.LoadModel(_env, modelStream, true, out predictor, out _schema);
            _featureNameCollection = FeatureNameCollection.Create(_schema);
```
you can modify it to save to memory stream if you want to.
_env = new TlcEnvironment();

Theoretically IPredictor object should be available through PredictionModel but since we plan to get rid of PredictionModel any way, I don't see sense to invest time in it. 

@rauhs  AFAIK we plan (for 1.0 release) to bring some kind of GUI, and I expect Tree visualizer to be part of it. Can be wrong tho.

We also have functionality to save Tree as CSharp code: https://github.com/dotnet/machinelearning/blob/3053f3df60b30ae237f34bf87e0ccfbebd0a88bb/src/Microsoft.ML.FastTree/FastTree.cs#L3198
it just not properly exposed.

**Comment by luksfarris** [comment] 2018-07-27 16:01
I'm getting the same error as you @mjmckp, let me know if you find any way around it, please

**Comment by WladdGorshenin** [comment] 2018-08-29 14:54
I'm getting the same error as @mjmckp and @luksfarris , any workarounds so far?

**Comment by Ivanidzo4ka** [comment] 2018-10-18 23:46
https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#i-want-to-look-at-my-models-coefficients
If you using MultiClass or Regression model onFit function will return you predictor with all functions I posted above.
For binary classification it currently doesn't return proper predictor and I open issue for that: https://github.com/dotnet/machinelearning/issues/1307

I'm considering this question answered, and plan to close it within next few days, unless anyone have objection.

**Closed** 2018-10-27 01:33 UTC
Labels: answered, enhancement, question
