### ISSUE TITLE
WeakReference<IHost> memory leak?

### ISSUE THREAD

**Issue by crvkumar** [dotnet/machinelearning#4914] opened 2020-03-04 01:32 UTC
### System information

- **ML.NET Version**: 1.4.0

### Issue

- **What did you do?**

1. Created a pipeline of ImageLoadingEstimator + ImageResizingEstimator + ImagePixelExtractingEstimator + OnnxScoringEstimator.
2. Create a ITransformer object by fitting the pipeline.
3. Performed ITransformer.Transform multiple times.

PS: Creating a PredictionEngine and performing PredictionEngine.Predict seems to lock the image as mentioned in issue [4585](https://github.com/dotnet/machinelearning/issues/4585 )

- **What happened?** 

WeakReference<IHost> objects seems to accumulate.

The number of objects does not change even after performing GC.Collect()

Is this possibly a memory leak?
The application is built is Release configuration.

![image](https://user-images.githubusercontent.com/2994809/75835713-f44f3a80-5e02-11ea-8454-abea45097ecc.png)

**Comment by mstfbl** [comment] 2020-03-04 06:00
Hey @crvkumar , thank you for letting us know about this possible memory leak. Could you please share with us your code with which you observed this behavior? I will run your code and see if I see an accumulation of WeakReference objects as well as its impact on memory.

**Comment by crvkumar** [comment] 2020-03-05 04:41
Hello @mstfbl. Thanks for the response.
Created a sample code reproducing this behavior in the below repo. Please check.

https://github.com/crvkumar/ML.NETMemoryLeakSample

**Comment by mstfbl** [comment] 2020-03-10 01:28
Hi @crvkumar , I ran the sample code you linked in Visual Studio 2019 with OnnxTransformer v1.3.1. I waited at the 2 parts of the code where the first and second snapshots are made. I did not see a memory leak when I ran it in Debug and Release modes, where process memory stayed stable at 61-62 MB. I also did not see any odd increases in the amount of WeakReference objects. Thus I was not able to reproduce your issue. 

Perhaps there were other factors influencing the results you got. Please try running it again and let us know if you consistently see a memory leak. Thanks!

**Comment by crvkumar** [comment] 2020-03-10 01:47
Hi @mstfbl. Thanks for checking the issue.

I am consistently getting the same results. I have attached a video for your reference.
I was using OnnxTransformer 1.4.0 but versioning down to 1.3.1 didn't change the behavior either.

https://github.com/crvkumar/ML.NETMemoryLeakSample/blob/master/MemoryLeakDemo%20-%20Microsoft%20Visual%20Studio%203_10_2020%2010_39_39%20AM.mp4

**Comment by mstfbl** [comment] 2020-03-10 02:06
Hi @crvkumar ,
I see, indeed in your case there is an increase of memory within a short time. I have uploaded my own demonstration showing no increase during one snapshot, and a small but expected increase between the first and second snapshots (The point in time when I iterate from the 1st to the 2nd snapshot is during the middle point of the video, unfortunately the terminal is not shown in this video).

https://github.com/mstfbl/machinelearning/blob/memoryleakinquirydemonstration/demonstration/MemoryLeakDemo%20-%20Microsoft%20Visual%20Studio%20Preview%202020-03-09%2018-58-33.mp4

**Comment by crvkumar** [comment] 2020-03-10 02:12
Hello @mstfbl Thank you. May I know what version of onnxruntime are you using.?
I guess ML.NET only supports 0.5.1.

**Comment by mstfbl** [comment] 2020-03-10 02:19
Correct, I'm running OnnxRuntim v0.5.1 and OnnxTransformer v1.3.1.

**Comment by crvkumar** [comment] 2020-03-10 02:23
May I know how could you run the project in "Any CPU" config? Does the project is set in "x64"?

**Comment by mstfbl** [comment] 2020-03-10 02:40
Of course, the "Any CPU" config on my computer is just set to "x64", so it is effectively running in "x64".

Also, I'd like to make an addition to my earlier comment. We currently support OnnxRuntime 1.0 as seen in [this PR ](https://github.com/dotnet/machinelearning/commit/7b2478c5c47d76d69ed11d0fb2de2f43136438a0#diff-a982ad13ab5a78e84c83241d709256b1) for ML.NET 1.5.0-preview.

**Comment by crvkumar** [comment] 2020-03-10 02:41
OK. Thank yoou.
Do you have any idea why the behavior is different in the two machines? Do you have any pointers where to look?

**Comment by strikene** [comment] 2020-03-22 09:08
I have the same problem with the use of GC memory is still going crazy, I use 1.50preview2 and 1.4 
By the way, even without image prediction, a mere multi-classification of text would leak.
The first picture was when I started the application.
![f](https://user-images.githubusercontent.com/62022463/77246133-282dbb00-6c5f-11ea-895d-3938163323f5.png)

**Comment by mstfbl** [comment] 2020-03-26 18:33
Hi @crvkumar and @strikene ,
Thank you for following up on this. We're still working on reproducing this issue locally, and will get back to you soon.

**Comment by mstfbl** [comment] 2020-03-28 00:48
Hi @strikene ,

I'm attempting to run the sample code you've written. Do you have the dataset where `Path` is pointing?

**Comment by strikene** [comment] 2020-03-28 06:47
> 嗨@strikene，
> 
> 我正在尝试运行您编写的示例代码。您是否有`Path`指向的数据集？



> Hi @strikene ,
> 
> I'm attempting to run the sample code you've written. Do you have the dataset where `Path` is pointing?

Path = "C:\MLModed.zip"

**Comment by mstfbl** [comment] 2020-03-30 07:47
Hi @strikene , I meant, do you have a sample of the actual dataset of what you are trying to classify? For example, the zip file that `Path` points to.

**Comment by mstfbl** [comment] 2020-03-31 00:51
Hey guys,
I think I found the root cause of the issue. The accumulation of the WeakReference<IHost> objects stem from this `_children` list here:

https://github.com/dotnet/machinelearning/blob/6b2d1a5330bf2f73253edf5895baec367dd329a6/src/Microsoft.ML.Core/Environment/HostEnvironmentBase.cs#L347-L348

Between each iteration, this `_children` list is not cleaned, and instead WeakReference objects accumulate, and the C# garbage collector does not clean it up as the comment above it says it does.

**Comment by crvkumar** [comment] 2020-03-31 00:57
Thanks for following up @mstfbl . Will there be any fix/modifications for this subsequently?

Also why does this not occur in your environment?

**Comment by mstfbl** [comment] 2020-03-31 01:05
Of course @crvkumar ! I'm currently working on a fix for this, and will push out a PR when it's ready.
This memory accumulation does happen in my environment, but it's in the order of 8-12 kilobytes.

**Comment by crvkumar** [comment] 2020-03-31 01:07
Thank you @mstfbl. Yes, the leak seems to be small but adds up to a considerable size over few hours of continuous operation.
Thanks for your support.

**Comment by strikene** [comment] 2020-03-31 12:02
> Hi @strikene , I meant, do you have a sample of the actual dataset of what you are trying to classify? For example, the zip file that `Path` points to.
[20200102MLModel.zip](https://github.com/dotnet/machinelearning/files/4408875/20200102MLModel.zip)

**Comment by eerhardt** [comment] 2020-04-01 18:00
> the leak seems to be small but adds up to a considerable size over few hours of continuous operation.

I noticed this as well debugging #4981. I sent ~2,000 requests to an Azure Function, and in the course of about 40 seconds there were 48,200 of these `WeakReference` objects created, which added up to over 1 MB. Leaking that much memory on a production server is going to cause issues.

![image](https://user-images.githubusercontent.com/8291187/78170118-16df6e00-7418-11ea-9b4f-89f45fc68151.png)


> Between each iteration, this _children list is not cleaned, and instead WeakReference objects accumulate, and the C# garbage collector does not clean it up as the comment above it says it does.

Note that the `IHost` objects themselves will get garbage collected. The objects that are accumulating are the `WeakReference` objects themselves, which can't get garbage collected, because they are put in the `List` and never removed.

We need to remove these from the List at some point, preferrably when the IHost is no longer needed.

**Closed** 2020-04-04 00:18 UTC
Labels: P1, bug, question
