### ISSUE TITLE
Provide sample and documentation for PredictionFunction object-pooling for ASP.NET applications

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#1789] opened 2018-11-30 19:08 UTC
This is the concrete work item from discussions in #1718.

Motivation:
Majority of .NET Core apps use ASP.NET Core. In order to get the best developer experience we should provide a sample that implements object pooling approach for PredictionFucntion (which is not trivial) and also document it in docs.microsoft.com.

Based on feedback from users, we might add this functionality to ML.NET.

**Comment by CESARDELATORRE** [comment] 2018-11-30 19:18
👍 Adding also @JRAlexander since I'll work with him for the documentation at docs.microsoft.com in order to be aligned.

**Comment by CESARDELATORRE** [comment] 2019-03-04 18:11
I created a sample showing Object Pooling for the PredictionEngine targeting high scalable web apps, here:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopDashboard

@luisquintanilla is also working on a Tutorial for this scenario.

So, I'm closing this issue.

We might want to discuss how to simplify this scenario in the future, though..

**Closed by CESARDELATORRE** 2019-03-04 18:11 UTC
Labels: documentation
