### ISSUE TITLE
how we draw tree using fast tree algorithm?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4275] opened 2019-10-02 04:08 UTC
as per suggestion given by @eerhardt, following link to @ganik @codemzs or @yaeldekel 
https://github.com/dotnet/machinelearning/issues/4264
@ganik -  i have prepared sample on this below link.
this is Visualize sickit-learn decision trees with d3.js
http://bl.ocks.org/fractalytics/raw/495b63cf671b4c487bc40801366384e0/

we do not know python script but we know C#. so that please helps us to draw above tree using fasttree ml.net using score,weights,bias.
if any sample is their please share with us.

**Comment by yaeldekel** [comment] 2019-10-02 11:53
Hi @nighotatul, the visualization in the link above is really cool.
ML.NET does not have any visualization tools for decision trees, but as @eerhardt mentioned, the trained FastTree/LightGBM models contain a property of type `RegressionTreeEnsemble` that you can use to traverse the trees and collect information about them. This looks something like this:
Assume you have a float array called `example` containing the feature vector.

```
            foreach (RegressionTree tree in ensemble.Trees)
            {
                // This is the root.
                int node = 0;
                while (node >= 0)
                {
                    float fv = example[tree.NumericalSplitFeatureIndexes[node]];
                    if (fv <= tree.NumericalSplitThresholds[node])
                        node = tree.LeftChild[node];
                    else
                        node = tree.RightChild[node];
                }

            }
```
In each step, the feature you are splitting on is `tree.NumericalSplitFeatureIndexes[node]`, and the threshold for the split is `tree.NumericalSplitThresholds[node]`.

Please let us know if this helps or if you have additional questions about it.

**Comment by nighotatul** [comment] 2019-10-07 10:36
@yaeldekel :-

Hi we run the code but how we can extract feature and value based on node value

as we are getting some positive value and negative value of node variable

here little bit we added code for feature collection and little bit my Rnd

but still we are not achieve our goal ?


DataViewSchema.Column? columnOrNull = regressionTransformer.Schema.GetColumnOrNull("Features");
                            VBuffer<ReadOnlyMemory<char>> slotNames = new VBuffer<ReadOnlyMemory<char>>();
                            if (columnOrNull.HasValue)
                                columnOrNull.GetValueOrDefault().GetSlotNames(ref slotNames);

                            IList<string> featureNameCollection = (IList<string>)slotNames.Items(false).Select<KeyValuePair<int, ReadOnlyMemory<char>>, string>((Func<KeyValuePair<int, ReadOnlyMemory<char>>, string>)(kv => kv.Value.ToString())).ToList<string>();

// This is the root.
                            int node = 0;
                            while (node >= 0)
                            {
                                float fv = tree.NumericalSplitFeatureIndexes[node];
                                if (fv <= tree.NumericalSplitThresholds[node])
                                    node = tree.LeftChild[node];
                                else
                                    node = tree.RightChild[node];


                                if (node < 0)//leaf value
                                {

                                   // FloatUtils.ToRoundTripString(tree.LeafValues(~node))
                                }
                                else
                                {

                                    var KeyValues = GetNode(node, false, featureNameCollection.ToArray(), tree);

                                }
                                // var featureValue=  !tree.CategoricalSplitFlags[node] ? featureNameCollection[tree.NumericalSplitFeatureIndexes[node]] : featureNameCollection[tree.GetCategoricalSplitFeaturesAt(node)[0]];
                            }

public INode GetNode(int nodeId, bool isLeaf, string[] featuresNames,RegressionTree tree)
        {
            var keyValues = new Dictionary<string, object>();
            if (isLeaf)
            {
                keyValues.Add("LeafValue", tree.LeafValues[nodeId]);
            }
            else
            {
                if (featuresNames != null)
                {

                    if (tree.CategoricalSplitFlags[nodeId])
                    {
                        string featureList = string.Join(" OR \n",
                            tree.GetCategoricalSplitFeaturesAt(nodeId).Select(feature => featuresNames[feature]));

                        keyValues.Add("SplitName", featureList);
                    }
                    else
                        keyValues.Add("SplitName", featuresNames[tree.NumericalSplitFeatureIndexes[nodeId]]);

                }
                keyValues.Add("Threshold", string.Format("<= {0}", tree.NumericalSplitThresholds[nodeId]));
                if (tree.SplitGains != null)
                    keyValues.Add("SplitGain", tree.SplitGains[nodeId]);
                //if (this.tree.GainPValues != null)
                //    keyValues.Add("GainValue", this.tree.GainPValues[nodeId]);
                //if (this.tree.PreviousLeafValues != null)
                //    keyValues.Add(NodeKeys.PreviousLeafValue, this.tree.PreviousLeafValues[nodeId]);
            }


            return new TreeNode(keyValues);
        }

when we will get something following like below i.e ==,> and <= 

following code require for json generation of tree but we will not get how to represent it with 

your logic


I just added my rnd here please help us

 StringBuilder output = new StringBuilder();

var leftnodeIndices=(IReadOnlyList<int>)((IEnumerable<int>)tree.LeftChild).ToArray<int>()

var rightnodeIndices=(IReadOnlyList<int>)((IEnumerable<int>)tree.RightChild).ToArray<int>()

for (int nodeIndex1 = 0; nodeIndex1 < ((IReadOnlyCollection<int>)leftnodeIndices).Count; ++nodeIndex1)
                            {
                                int nodeIndex2 = leftnodeIndices[nodeIndex1];
                                if (nodeIndex2 == 0)
                                    break;
                                output.Append(this.NodeAsText(nodeIndex1) + " -> ");
                                if (nodeIndex2 > 0)
                                    output.Append(this.NodeAsText(nodeIndex2) ?? "");
                                else
                                    output.Append(this.LeafAsText(~nodeIndex2) ?? "");
                                output.Append(" [ label = " + "False" + " ];");
                                output.AppendLine();
                            }
//same loop for right rightnodeIndices

private string NodeAsText(int nodeIndex)
{


stringBuilder.Append(string.Format("\"{0} == {1}\\n", (object)featureName, featureValue));

stringBuilder.Append(string.Format("\"{0} > {1}\\n", (object)featureName, featureValue));

stringBuilder.Append(string.Format("\"{0} < {1} <= {2}\\n", obj1, (object)featureName, featureValue));

stringBuilder.Append(string.Format("Gain: {0}\\nP-value: {1}\\nPrediction: {2}\"", this.tree.SplitGains[nodeIndex], ?,? ));
return str
}

private string LeafAsText(int leafIndex)
        {
            StringBuilder stringBuilder = new StringBuilder();
            double num1 = this.tree.LeafValues[leafIndex];
                        stringBuilder.Append(string.Format("\"Leaf: {0}\\nPrediction: {1}\"", (object)leafIndex, (object) ?));
            string str = stringBuilder.ToString();
           
            return str;
        }

**Comment by yaeldekel** [comment] 2019-10-07 13:37
Hi @nighotatul,
In a FastTree model, every internal node in a tree is associated with the index of the feature the split is performed on (which is stored in `tree.NumericalSplitFeatureIndexes[node]`) and the threshold of the split (which is stored in `tree.NumericalSplitThresholds[node]`). Every leaf node is associated with a leaf value (which is stored in `tree.LeafValues[~node]`). If you would like to have the internal nodes associated with feature names, then your code above is doing the correct thing:
```
DataViewSchema.Column? columnOrNull = regressionTransformer.Schema.GetColumnOrNull("Features");
VBuffer<ReadOnlyMemory> slotNames = new VBuffer<ReadOnlyMemory>();
if (columnOrNull.HasValue)
columnOrNull.GetValueOrDefault().GetSlotNames(ref slotNames);
```
The `VBuffer`<ReadOnlyMemory<char>> type has a `GetValues()` method that returns a `ReadOnlySpan<ReadOnlyMemory<char>>` and you can use that to find the feature name given the feature index.

Please let me know if this answers your question, since I am not sure I understood it correctly.

**Comment by nighotatul** [comment] 2019-10-07 13:57
@yaeldekel - hear we just added prototype of code.how we can extract feature and their value as per node? also please helps us that how we can implement nodeastext function because its only prototype but we not implemented yet?
StringBuilder output = new StringBuilder();

var leftnodeIndices=(IReadOnlyList)((IEnumerable)tree.LeftChild).ToArray()

var rightnodeIndices=(IReadOnlyList)((IEnumerable)tree.RightChild).ToArray()

for (int nodeIndex1 = 0; nodeIndex1 < ((IReadOnlyCollection)leftnodeIndices).Count; ++nodeIndex1)
{
int nodeIndex2 = leftnodeIndices[nodeIndex1];
if (nodeIndex2 == 0)
break;
output.Append(this.NodeAsText(nodeIndex1) + " -> ");
if (nodeIndex2 > 0)
output.Append(this.NodeAsText(nodeIndex2) ?? "");
else
output.Append(this.LeafAsText(~nodeIndex2) ?? "");
output.Append(" [ label = " + "False" + " ];");
output.AppendLine();
}
//same loop for right rightnodeIndices

private string NodeAsText(int nodeIndex)
{

stringBuilder.Append(string.Format(""{0} == {1}\n", (object)featureName, featureValue));

stringBuilder.Append(string.Format(""{0} > {1}\n", (object)featureName, featureValue));

stringBuilder.Append(string.Format(""{0} < {1} <= {2}\n", obj1, (object)featureName, featureValue));

stringBuilder.Append(string.Format("Gain: {0}\nP-value: {1}\nPrediction: {2}"", this.tree.SplitGains[nodeIndex], ?,? ));
return str
}

private string LeafAsText(int leafIndex)
{
StringBuilder stringBuilder = new StringBuilder();
double num1 = this.tree.LeafValues[leafIndex];
stringBuilder.Append(string.Format(""Leaf: {0}\nPrediction: {1}"", (object)leafIndex, (object) ?));
string str = stringBuilder.ToString();

        return str;
    }

**Comment by luisquintanilla** [comment] 2022-10-07 16:50
Thanks for the question. I see an answer was provided here as well as #4317. Closing.

**Closed by luisquintanilla** 2022-10-07 16:50 UTC
Labels: P2
