### ISSUE TITLE
LDA Get Words for Topics

### ISSUE THREAD

**Issue by hobbsa** [dotnet/machinelearning#4322] opened 2019-10-10 19:49 UTC
### System information

- **Win10
- **.NET 4.7.2
- **ML.NET 1.3.1

I am trying to get the top N words for each topic after an LDA Transform but cannot seem to figure out how to do.  I've used Infer.Net and it returns the topics and top 20 words, is there a way to do it in ML.NET using the LDA Xform?  I've used relfection to look through almost everything in the xformer but cannot seem to find anything that would work?

The goal is to use the top N words to label a topic for display and to further determine if we need more/less topics based on repeating words.

**Comment by codemzs** [comment] 2019-10-10 19:52
@justinormont has a lot of experience in text analysis and can probably answer this

**Comment by justinormont** [comment] 2019-10-10 21:29
This has been a long standing issue. I don't think we expose an API to get the actual topics. 

The best you can do until then is unzip the model and inspect there.

For a while, there was an OnFit() in the older PigSy API, which would return the raw model which had its topics. But this is gone.

Related:
* https://github.com/dotnet/machinelearning/issues/3092
* https://github.com/dotnet/machinelearning/issues/2197

**Comment by antoniovs1029** [comment] 2020-01-09 01:10
> The best you can do until then is unzip the model and inspect there.

For the record, it seems that it is no longer possible to do this. Back in TLC, when enabling the "Output Topic Word Summary" option for LightLDA Transformer in the GUI, a file named `word_topic_summary.txt` was included inside the `model.zip` generated by the experiment; this file included the main words in each topic.

In ML.NET there's no public API to enable the [OutputTopicWordSummary ](https://github.com/dotnet/machinelearning/blob/0435f6b3ae976967b532e164df50e71e56a22d07/src/Microsoft.ML.Transforms/Text/LdaTransform.cs#L106) option, so saving the model into disk doesn't include such a file, and thus unzipping the model doesn't help.

Nonetheless, the `OutputTopicWordSummary ` option is available through an entrypoint graph (using `'OutputTopicWordSummary': true` in a `LightLda` node), through MAML (using `summary=+` in a `LdaTransform`) and through NimbusML (directly using the `output_topic_word_summary` parameter in the [LightLda class](https://docs.microsoft.com/en-us/python/api/nimbusml/nimbusml.feature_extraction.text.lightlda?view=nimbusml-py-latest)). Problem is that when enabling that option in any of those tools, the `word_topic_summary.txt` isn't included inside the model... and this seems like a bug to me, since that should be the expected behavior (which was the behavior back in TLC), and actually it seems that _nothing_ changes if those options are enabled.

After quickly looking at TLC code, and comparing it to current ML.NET code, it looks like the methods related to creating the `word_topic_summary.txt` file didn't make it into ML.NET, and several things have changed since, so it isn't very straightforward to get that functionality into ML.NET. In despite of this, in ML.NET there's [this variable](https://github.com/dotnet/machinelearning/blob/0435f6b3ae976967b532e164df50e71e56a22d07/src/Microsoft.ML.Transforms/Text/LdaTransform.cs#L633) in the LdaTransform that actually holds the string "word_topic_summary.txt", but this variable isn't actually never used anywhere (whereas in the TLC code that same variable is, of course, used to save the file in the `model.zip`).

In general, I think it would be a good idea to try to re-implement the functionality of creating this `word_topic_summary.txt` file inside the serialized model. After discussing it with @justinormont , it seems that it might be better to explore other alternatives instead of printing that file, because having to look into a serialized model wasn't very useful even back in TLC. In any case, it still remains a problem that there's no straightforward way of getting the words of the topics in ML.NET, and that the other options in the other APIs aren't doing anything and are misguiding to users.

**Comment by najeeb-kazmi** [comment] 2020-01-30 23:41
I would categorize this as P1 since this is existing functionality not working as advertised.

**Comment by frank-dong-ms** [comment] 2020-07-01 19:54
fix has been merged, close this issue

**Closed by frank-dong-ms** 2020-07-01 19:54 UTC
Labels: P1, enhancement, loadsave
