### ISSUE TITLE
Migration of Code Documentation

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#160] opened 2018-05-15 18:39 UTC
There have been many questions both in issues and PRs that could have been addressed with some existing as-yet unmigrated documentation. (Not all questions, but a significant number.) People are curious, that's great.

Note that this is not MSDN-style API documentation, but more ad hoc documents. I believe there is a shared understanding that documents like this, not MSDN-style docs but the more ad hoc docs, should be checked in next to the code. Let me know if not.

This will not be a straight copy job though and should be done with due care, for the following reasons:

1. some docs refer to the prior internal name for ML.NET (though to be fair I've noticed the code does too in places 😛) so that ought to be changed,
2. it appeals to historical perspectives or prior states of code that are invisible to people, which is awkward. This is hard, you can't just *delete* that stuff, because the point of the code docs is to explain exactly why something is engineered in a certain way, and that discussion is helped enormously if you explain why a deceptively "easier" way of doing task X, Y, or Z was deemed unacceptable.
3. it sometimes contextualizes the presence of this or that aspect of the code as being something that exists to solve an existing use-case, and not all those use-cases are open sourced.
4. While much of it is already in `.md`, some older docs are in other formats and will require some attention to migrate them.

Would appreciate discussion from @asthana86 , @eerhardt , @GalOshri , @glebuk , and @shauheen specifically on this topic. (To clarify all are welcome, just mentioning to make sure it gets flagged for them. 😄)

**Comment by GalOshri** [comment] 2018-05-16 05:42
This is great.

Additionally, it would be nice to include some additional information on how learners and transforms work in ML.NET (using the contribution tutorials). Although these can be migrated after the core IDV docs.

**Comment by TomFinley** [comment] 2018-05-17 17:34
Hi @GalOshri ... I'm sorry to say I won't make you happy on the tutorials. While I agree that they're practically quite useful in that it is one of the few things to treat in (excruciating) detail exactly how one goes about writing a component and how our infrastructure works from beginning to bitter end, *that* one will require considerably more work to adapt, because of course I am throughout the tutorial relying on existing idioms for invoking these, that are not true in the "new" ML.NET API. (And that are under considerable flux.)

**Comment by GalOshri** [comment] 2018-05-18 15:46
Thanks @TomFinley! I think it's fine if they are not migrated immediately, but we should try to do that once there is a little less flux.

**Comment by JRAlexander** [comment] 2018-08-06 21:59
You could also migrate these to the [dotnet/docs machinelearning repo](https://github.com/dotnet/docs/tree/master/docs/machine-learning). This would have several advantages, including rendering in Docs.microsoft.com, localization, and editing.

**Comment by shmoradims** [comment] 2019-05-21 19:33
Related to #1831

**Comment by codemzs** [comment] 2019-06-30 02:29
closing since it is a duplicate of #1831

**Closed by codemzs** 2019-06-30 02:29 UTC
Labels: P2, documentation
