### ISSUE TITLE
AutoML Fails due to FastTree GetProcessInformation UWP

### ISSUE THREAD

**Issue by Jenscaasen** [dotnet/machinelearning#4233] opened 2019-09-20 09:36 UTC
### Issue

- **What did you do?**
I used AutoML for a Forecast problem in an UWP App. newest version of ML.NET. Letting the training run for more than 2 Minutes. Even when trying to not include trainers named "*Tree*" in the "RegressionExperimentSettings" it still arises. No idea why it would try to get ProcessInformation. Can you please remove that "GetProcessInfos" from FastTree?

- **What happened?**
This Exception arises: 

 ```
  at System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(Predicate`1 processIdFilter)
   at System.Diagnostics.ProcessManager.GetProcessInfo(Int32 processId, String machineName)
   at System.Diagnostics.Process.EnsureState(State state)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.PrintMemoryStats(IChannel ch)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.TrainCore(IChannel ch)
   at Microsoft.ML.Trainers.FastTree.FastForestRegressionTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.AutoML.SmacSweeper.FitModel(IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.SmacSweeper.ProposeSweeps(Int32 maxSweeps, IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.PipelineSuggester.SampleHyperparameters(MLContext context, SuggestedTrainer trainer, IEnumerable`1 history, Boolean isMaximizingMetric)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IEnumerable`1 trainerWhitelist)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, String labelColumnName, String samplingKeyColumn, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at MLAtHome.Helpers.AutoMLHelper.<BuildTrainEvaluateAndSaveModel>d__8.MoveNext() in C:\Users\caasen\source\repos\MLAtHome\MLAtHome\Helpers\AutoMLHelper.cs:line 70
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[...]
```

### Source code / logs

```
//Excluding "FastTree" here in the settings
     RegressionExperiment experiment=  mlContext.Auto().CreateRegressionExperiment(experimentSettings);
            
            ExperimentResult<RegressionMetrics> experimentResult = experiment.Execute(myview, Statics.CurrentModel.LabelName, progressHandler: progressHandler);
```

**Comment by justinormont** [comment] 2019-09-20 18:36
This is an error in the SMAC sweeper, which uses a tree in the background for predicting which hyperparameters sets to try next. 

Hence even when the trees are disabled in the `RegressionExperimentSettings`, there are trees used in the AutoML experiment for the hyperparameter optimization.

I'm not sure exactly what in FastTree is throwing, but it's within `PrintMemoryStats()`:
https://github.com/dotnet/machinelearning/blob/d0b3f86b1d048612f2b255e52822ba37ca390b6a/src/Microsoft.ML.FastTree/FastTree.cs#L437-L462

I'm guessing this is a duplicate of: https://github.com/dotnet/machinelearning/issues/2444 (FastTree does not work in UWP)

@eerhardt, @codemzs: Do you see any quick solutions? Perhaps the [try/catch recommended](https://github.com/dotnet/machinelearning/issues/2444#issuecomment-466141405) by danmosemsft.

**Comment by justinormont** [comment] 2019-09-20 18:46
@Jenscaasen: For a short term workaround, you can stop AutoML at 68 iterations (I may be off by a couple). For iteration 9 to ~68, AutoML is warming up the hyperparameter space using random exploration. Beginning at iteration ~68, SMAC is used for hyperparameter optimization.

For this custom early stopping at iteration 68, you would add a `RegressionExperimentProgressHandler()` to monitor the current iteration number and stop just before SMAC begins.

**Comment by eerhardt** [comment] 2019-09-20 18:54
Unfortunately the FastTree issue isn't the only one you will encounter. I wouldn't recommend using ML.NET in UWP at the moment, because there are other UWP bugs that are going to block you.

Have you tried building your app in `Release` mode?

See the discussion here https://github.com/dotnet/machinelearning/issues/2252#issuecomment-470126677.

Instead, I would recommend using a WPF app on .NET Core 3.0. You can still submit these apps to the App Store.

**Comment by Jenscaasen** [comment] 2019-09-21 06:27
Thank you for your replys! 
As for try catching and stopping the search prematurely: that would not result in a let's say 1 hour trained model, right? In the case i am working on the user can choose the training time, limiting him to something between 1 second and 1 minute does not sound good (but I still appreciate the suggestions). 

Is there an estimation when UWP will be supported by ML.net? I like the platform with its design principles and the easy-to-market option by using the Microsoft store. 

As i see in the code dump: the get process Infos only gets executed with "AllowGC". Can i make that be false? 

Also I will look into whether WPF is a good replacement for UWP

**Comment by eerhardt** [comment] 2019-09-26 19:29
Closing as a duplicate of https://github.com/dotnet/machinelearning/issues/2444.

**Closed by eerhardt** 2019-09-26 19:29 UTC
Labels: UWP
