### ISSUE TITLE
How to use String as a Predicted Column

### ISSUE THREAD

**Issue by jt4000** [dotnet/machinelearning#4373] opened 2019-10-24 12:28 UTC
Goal:
Make a prediction on PaymentType. The target name or predicted column is a string value.

Problem:
I retrieve a error message that is "ArgumentOutOfRangeException: Training label column 'Label' type isn't suitable for regression: Text. Type must be R4 or R8. Parameter name: data"

Whar part from the source code am I missing?

Thank you!

Data:
https://github.com/dotnet/machinelearning/blob/master/test/data/taxi-fare-train.csv
https://github.com/dotnet/machinelearning/blob/master/test/data/taxi-fare-test.csv

Info:  
*Win 10
*Using .net Core 2.0 framework

Code:

```csharp
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Models;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using System;
using System.Threading.Tasks;

namespace TaxiFarePrediction
{
    class Program
    {
        const string _datapath = @".\Data\taxi-fare-train.csv";
        const string _testdatapath = @".\Data\taxi-fare-test.csv";
        const string _modelpath = @".\Data\Model.zip";

        static async Task Main(string[] args)
        {
            PredictionModel<TaxiTrip, TaxiTripFarePrediction> model = await Train();
            Evaluate(model);

            var prediction = model.Predict(TestTrips.Trip1);
            Console.WriteLine("Predicted fare: {0}", prediction.PaymentType);

            Console.ReadLine();
        }

        static async Task<PredictionModel<TaxiTrip, TaxiTripFarePrediction>> Train()
        {
            // Create learning pipeline
            var pipeline = new LearningPipeline
            {
                // Load and transform data
                new TextLoader(_datapath).CreateFrom<TaxiTrip>(separator: ','),

                 // Labeling
                new ColumnCopier(("PaymentType", "Label")),

                // Feature engineering
                new CategoricalOneHotVectorizer("VendorId",
                    "RateCode",
                    "PaymentType"),

                 // Combine features in a single vector
                new ColumnConcatenator("Features",
                    "VendorId",
                    "RateCode",
                    "PassengerCount",
                    "TripDistance",
                    "FareAmount"),

                // Add learning algorithm
                new FastTreeRegressor()
            };

            // Train the model
            PredictionModel<TaxiTrip, TaxiTripFarePrediction> model = pipeline.Train<TaxiTrip, TaxiTripFarePrediction>();

            // Save the model to a zip file
            await model.WriteAsync(_modelpath);

            return model;
        }

        private static void Evaluate(PredictionModel<TaxiTrip, TaxiTripFarePrediction> model)
        {
            // Load test data
            var testData = new TextLoader(_datapath).CreateFrom<TaxiTrip>(useHeader: true, separator: ',');

            // Evaluate test data
            var evaluator = new RegressionEvaluator();
            RegressionMetrics metrics = evaluator.Evaluate(model, testData);

            // Display regression evaluation metrics
            Console.WriteLine("Rms=" + metrics.Rms);
            Console.WriteLine("RSquared = " + metrics.RSquared);
        }
    }
}

```

---------------------------------------------------------------------

```csharp
namespace TaxiFarePrediction
{
    static class TestTrips
    {
        internal static readonly TaxiTrip Trip1 = new TaxiTrip
        {
            VendorId = "VTS",
            RateCode = "1",
            PassengerCount = 1,
            TripDistance = 10.33f,
            PaymentType = "", 
            FareAmount = 7,
            //FareAmount = 0 // predict it. actual = 29.5
        };
    }
}
```

---------------------------------------------------------------------
```csharp

using Microsoft.ML.Runtime.Api;

namespace TaxiFarePrediction
{
    public class TaxiTrip
    {
        [Column("0")]
        public string VendorId;

        [Column("1")]
        public string RateCode;

        [Column("2")]
        public float PassengerCount;

        [Column("3")]
        public float TripTime;

        [Column("4")]
        public float TripDistance;

        [Column("5")]
        public string PaymentType;

        [Column("6")]
        public float FareAmount;
    }

}

```

-------------------------------------------------

```csharp
using Microsoft.ML.Runtime.Api;

namespace TaxiFarePrediction
{
    public class TaxiTripFarePrediction
    {

        /*
        [ColumnName("Score")]
        public float FareAmount;

        */
        [ColumnName("Score")]
        public string PaymentType;
    }
}

```

-------------------------------------

![ml1](https://user-images.githubusercontent.com/14993569/67485473-613f1080-f66a-11e9-8c8a-c85b8355585c.png)
![ml2](https://user-images.githubusercontent.com/14993569/67485474-613f1080-f66a-11e9-8442-05e08c37407f.png)

**Comment by gvashishtha** [comment] 2019-11-01 16:12
Hi there! Sounds like the problem you're describing is Multiclass Classification, not regression. Regression is generally for predicting some numerical output (like the actual fare amount, [as we do in this tutorial](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Regression_TaxiFarePrediction)). To learn more about Multiclass Classification in ML.NET, [check out this tutorial](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)

**Comment by najeeb-kazmi** [comment] 2020-01-28 00:34
Hi @jt4000, as @gvashishtha mentioned, it looks like you are trying to do a multiclass classification with `PaymentType` as your label. You will have to apply the appropriate conversion to this column (convert it's type to `Key` as multiclass trainers expect a label of Key type, and rename it to `Label`) and use a multiclass classification trainer. You can do this like so:

```csharp
var mlContext = new MLContext();

var data = mlContext.Data.LoadFromTextFile<TaxiTrp>(_datapath);

var pipeline = 
    // Simultaneously convert type to key and rename to "Label"
    mlContext.Transforms.Conversion.MapValueToKey("Label", "PaymentType")
    // One-hot encoding for categorical columns
    .Append(mlContext.Transforms.Categorical.OneHotEncoding(
        new[]
        {
            new InputOutputColumnPair("VendorId"),
            new InputOutputColumnPair("RateCode")
            // note that you do not vectorize the PaymentType column as this is
            // not a correct conversion for a multiclass label
        }))
    // Concatenate columns into one feature vector
    .Append(mlContext.Transforms.Concatenate("Features", new[]
        { "VendorId", "RateCode", "PassengerCount", "TripDistance", "FareAmount" }))
    // Add a multiclass trainer
    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy())
    // The trainer takes a label of Key type and produces a "PredictedLabel" of Key type.
    // Add a Key to Value conversion on the "PredictedLabel" so that the original values
    // can be recovered.
    .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

var model = pipeline.Fit(data);
```

Note that the `LearningPipeline` API has been depricated in favor of the `Estimator`/`TransformerChain` API.

Please refer to the links provided by @gvashishtha as well as samples for all our multiclass trainers [here](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification).

I am closing this issue since this answers your question. Please feel free to reopen if this leaves something unaddressed.

**Closed by najeeb-kazmi** 2020-01-28 00:34 UTC
Labels: P3
