### ISSUE TITLE
Bias value gets changed every run at 100th place

### ISSUE THREAD

**Issue by AshishMoradiya** [dotnet/machinelearning#3780] opened 2019-05-27 00:09 UTC
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 4.6.1

### Issue

- **What did you do?** I run sample code on given document (Using full data as Traning data)

- **What happened?** Bias value gets changed every run at 100th place
1st try result -
2nd try result -
3rd try result -

- **What did you expect?**
Same value, because of using same sample data at every run.

### Source code / logs
Sample code I tried - https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-machine-learning-model-ml-net

`HousingData[] housingData = new HousingData[]
            {
                new HousingData
                {
                    Size = 600f,
                    HistoricalPrices = new float[] { 100000f ,125000f ,122000f },
                    CurrentPrice = 170000f
                },
                new HousingData
                {
                    Size = 1000f,
                    HistoricalPrices = new float[] { 200000f, 250000f, 230000f },
                    CurrentPrice = 225000f
                },
                new HousingData
                {
                    Size = 1000f,
                    HistoricalPrices = new float[] { 126000f, 130000f, 200000f },
                    CurrentPrice = 195000f
                },
                new HousingData
                {
                    Size = 850f,
                    HistoricalPrices = new float[] { 150000f,175000f,210000f },
                    CurrentPrice = 205000f
                },
                new HousingData
                {
                    Size = 900f,
                    HistoricalPrices = new float[] { 155000f, 190000f, 220000f },
                    CurrentPrice = 210000f
                },
                new HousingData
                {
                    Size = 550f,
                    HistoricalPrices = new float[] { 99000f, 98000f, 130000f },
                    CurrentPrice = 180000f
                }
            };

            MLContext mlContext = new MLContext();
            IDataView trainingData = mlContext.Data.LoadFromEnumerable(housingData);

            // Define Data Prep Estimator
            // 1. Concatenate Size and Historical into a single feature vector output to a new column called Features
            // 2. Normalize Features vector
            IEstimator<ITransformer> dataPrepEstimator =
                mlContext.Transforms.Concatenate("Features", "Size", "HistoricalPrices")
                    .Append(mlContext.Transforms.NormalizeMinMax("Features"));

            // Create data prep transformer
            ITransformer dataPrepTransformer = dataPrepEstimator.Fit(trainingData);

            // Apply tranforms to training data
            IDataView transformedTrainingData = dataPrepTransformer.Transform(trainingData);

            var UserDefinedColumnSdcaEstimator = mlContext.Regression.Trainers.Sdca(labelColumnName: "CurrentPrice", featureColumnName: "Features");
            // Define StochasticDualCoodrinateAscent regression algorithm estimator
            var sdcaEstimator = mlContext.Regression.Trainers.Sdca();

            // Build machine learning model
            var trainedModel = sdcaEstimator.Fit(transformedTrainingData);

            var trainedModelParameters = trainedModel.Model as LinearRegressionModelParameters;
            var bias = trainedModelParameters.Bias;`

**Comment by frank-dong-ms** [comment] 2020-06-04 03:29
@AshishMoradiya  Thanks for using ML.NET, the randomness of bias you observe is by design. If you want to remove the randomness you can use below setting of SDCA:

var sdcaEstimator = mlContext.Regression.Trainers.Sdca(new SdcaRegressionTrainer.Options()
            {
                NumberOfThreads = 1,
                Shuffle = false,
                // add certain max iteration number to avoid training to run forever
                MaximumNumberOfIterations = 20
            });

I will close this issue, feel free to reopen if necessary.

**Closed by frank-dong-ms** 2020-06-04 03:29 UTC
Labels: P1, bug, regression
