### ISSUE TITLE
Installing ML.NET on target framework .NET Framework=4.7.2 (Latest) Fails via Nuget

### ISSUE THREAD

**Issue by airduster** [dotnet/machinelearning#290] opened 2018-06-02 15:37 UTC
### System information

- **OS Windows 7**:
- **.NET 4.7.2 (Latest)**: 
- **Visual Studio 2015 (x64)**: 

### Issue

- **What did you do:**

 Attempting to install Microsoft.ML package via Nuget on project that has .NET targetframework = 4.7.2 (latest)

- **What happened?: '**

package install failed with the following message 

Could not install package 'Microsoft.ML 0.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

- **What did you expect?:**
The documentation indicates this can be installed on netcore **or .NET Framework.** Am I doing something wrong? To Verify I manually downloaded the Microsoft.ML package from nuget and in "Microsoft.ML.nuspec" under target frameworks only netcore 2.0 is listed for v0.1.0 of ML.NET

**Comment by danmosemsft** [comment] 2018-06-04 19:40
I would expect this to work, indeed I tried it back in original release. @eerhardt  any thoughts?

**Comment by eerhardt** [comment] 2018-06-04 19:44
The issue is `Visual Studio 2015`.

Unfortunately v0.1.0 of Microsoft.ML didn’t support VS 2015 (because Microsoft.ML v0.1 didn't support packages.config).  We’ve fixed it with the latest daily builds, and the fix will be in the next version v0.2, which will be coming shortly (hopefully in the next week).

You can try the latest daily builds by adding the following NuGet feed to your NuGet Package Manager settings:

                https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

Also, please note that Microsoft.ML targets netstandard2.0.  In order to work with a netstandard2.0 package in VS 2015, you will need to install the following:

1.	The latest NuGet VSIX for VS 2015 (v3.6.0 as of this writing) from https://www.nuget.org/downloads
2.	The .NET Standard Build Support extension from https://aka.ms/netstandard-build-support-netfx

**Comment by Ivanidzo4ka** [comment] 2018-10-18 16:52
DRI RESPONSE:
I'm intent to close this thread in few days, if no one reply to it.

**Comment by eerhardt** [comment] 2018-10-18 17:14
This has been fixed for a while. We can close it now. Please open a new issue (with repro steps and environment/version information) if anyone is having issues installing the Microsoft.ML NuGet package.

**Closed by eerhardt** 2018-10-18 17:14 UTC
Labels: Answered, Build
