### ISSUE TITLE
Model is predicting null when a user used CustomModel in TensorFlow Image Classification

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning#3751] opened 2019-05-21 00:11 UTC
User has reported issue in Machine Learning samples https://github.com/dotnet/machinelearning-samples/issues/468 

 I have used the custom model and labels.txt provided by user in [TensorFlow image classification sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow) and changed the model pipeLine for Tensor input and output as shown below.

```
var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "Placeholder", imageFolder: imagesFolder, inputColumnName: nameof(ImageNetData.ImagePath))
                           .Append(mlContext.Transforms.ResizeImages(outputColumnName: "Placeholder", imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: "Placeholder"))
                           .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "Placeholder", interleavePixelColors: ImageNetSettings.channelsLast, offsetImage: ImageNetSettings.mean))
                           .Append(mlContext.Model.LoadTensorFlowModel(modelLocation).
                           ScoreTensorFlowModel(outputColumnNames: new[] { "loss" },
                                               inputColumnNames: new[] { "Placeholder" }, addBatchDimensionInput: true));
```

While predicting an image using the prediction engine, the model is not predicting anything and its giving predictedLabels value as null.

`var probs = model.Predict(sample).PredictedLabels;`

![image](https://user-images.githubusercontent.com/22335043/58059536-38967600-7b22-11e9-91e2-ec6263e3ceba.png)

Could any one let me know why the model is not predicting any label?

**Comment by developervariety** [comment] 2019-05-22 00:53
I don't want to say the cause is a Azure update, but I believe it is.

This [project](https://github.com/CESARDELATORRE/TensorFlowImageClassificationWebAPI) uses a custom model that works with v0.7-latest (tested myself). It's a model that was produced months ago from the looks of it.

It's possible an update has caused incompatibilities with ML.NET. If there's anything I could do just tag me, thank you for your work guys.

**Comment by prathyusha12345** [comment] 2019-05-22 00:58
@developervariety I tested the model in latest ML.Net 1.0.0 sample  [ TensorFlow image classification sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow) and getting the exception. 

There must be some issue with the API that it is not accepting the custom model other than inception graph

**Comment by developervariety** [comment] 2019-05-22 01:06
I don't understand how Cesar's model works in ML.NET v0.7, but later models built don't work with ML.NET v0.7-latest.

I'll try to investigate what I can dig up and fix it if I could.

**Comment by zeahmed** [comment] 2019-05-22 21:17
@prathyusha12345, I ran the original sample and it works fine. Can you please share me you model and data file if possible so that I can repro this at my end?

**Comment by developervariety** [comment] 2019-05-22 21:20
@zeahmed

The model used is a custom model exported from Azure Custom Vision. 

It can be found on the issue referenced from the samples.

**Comment by zeahmed** [comment] 2019-05-22 22:14
@developervariety, please set `addBatchDimensionInput: false` because this model has input with fully specified shape [?, 224, 224, 3] which is against inception model which does not have fully specified shape fro the input.

**Comment by zeahmed** [comment] 2019-05-22 22:59
Please update me if it works for you so that I can close the bug.

**Comment by prathyusha12345** [comment] 2019-05-22 23:17
@zeahmed If it works for @developervariety you can close the issue.

**Comment by developervariety** [comment] 2019-05-23 02:02
I updated my ML.NET version 1.0.0 for testing, and it is still only returning one model. Whenever I rearrange the `labels` file, the model is different each time..

**Comment by zeahmed** [comment] 2019-05-23 19:27
I don't get you regarding your comment???
>> it is still only returning one model

You are getting different prediction every time because of the `GetBestLabel(labels, imageLabelPredictions);` method. It takes labels as input which are different every time you rearrange labels.

**Comment by developervariety** [comment] 2019-05-23 22:00
Then how come the prediction is no where near correct unless I use it on Azure?

I'll rearrange it how Azure gave them to me, but it only returns one model if I don't rearrange them for testing. The score is almost always 1 which is just bizarre.

This issue is not solved from my end from the looks of it.

**Comment by zeahmed** [comment] 2019-05-24 00:04
@developervariety, Can you please share you complete project and model? I am not able understand your scenario. Please explain it in more detail so that I can suggest appropriate solution.

**Comment by zeahmed** [comment] 2019-05-29 01:12
I feel the original problem that issue was created for has been answered. I am going to close this issue.

@developervariety, if you are still having problem you can open another issue with appropriate details.

**Closed by zeahmed** 2019-05-29 01:12 UTC
Labels: P0
