### ISSUE TITLE
ONNX Model Evaluation in ML.Net not working

### ISSUE THREAD

**Issue by ladodc** [dotnet/machinelearning#5343] opened 2020-08-12 11:37 UTC
### System information

- Win10
- .NET Core 3.1

### How can I evaluate ONNX Model in ML.Net
I am loading already trained ONNX Model with ApplyOnnxModel then produce predictions based on my data(IDataView) and afterward I am going to evaluate the results with mlContext.BinaryClassification.Evaluate. That does not work. Becouse he expects scoreColumn as single float and not float[]. But ONNX Model returns always results in Vector<Single, -1, 1>. 
On evaluating I got exception: 

> System.ArgumentOutOfRangeException
Schema mismatch for score column 'Score': expected Single, got Vector<Single, 1, 1> (Parameter 'schema')

As you can see in the following model. Output Parameter are vectors float32[-1,1] but BinaryClassification.Evaluate expect single float. Is there any workaround. Or it is not possible to evaluate ONNX Model with ML.Net.

[model.zip](https://github.com/dotnet/machinelearning/files/5062377/model.zip)

### Source code / logs

```
var pipeline = mlContext.Transforms.ApplyOnnxModel(modelFile: this.ModelFile, inputColumnNames: new string[] { "day","hour","name","worker","temperature","vibration"},
                    outputColumnNames: new[] { "Probability.output", "PredictedLabel.output","Score.output" });

IDataView predictions = model.Transform(dataView);
var metrics = mlContext.BinaryClassification.Evaluate(predictions, labelColumnName: labelColumnName, scoreColumnName: "Score", probabilityColumnName: "Probability", predictedLabelColumnName: "PredictedLabel");
```

**Comment by antoniovs1029** [comment] 2020-08-12 16:24
Hi, @ladodc .
I think `mlContext.BinaryClassification.Evaluate` can be used with _any_ `IDataView` that has a label column, a score column and a predicted label column, so it should work with an onnx model. The only thing is that, as you noted, the Score column is expected to be a Single and not a Vector, so ideally your onnx model should output a Single and not a Vector.

So I think that a valid workaround for this is to use a `CustomMappingTransformer` after applying the onnx model, but before calling evaluate. The `CustomMappingTransformer` lets users to apply custom functions to a data view. In your case, you'd want to extract the value from the vector and store it into a `float` column, and then use that `float` column as `scoreColumnName` for Evaluate.

An example on how to use `CustomMappingTransformer` with an onnx model can be found [here](https://github.com/dotnet/machinelearning/issues/4795#issuecomment-613276360). Notice that the example is more complicated than your case, as it's trying to reshape arrays before using them as input of an onnx model. In your case, you'd want to use the `CustomMappingTransformer` after applying the onnx model, and only to extract the value inside the vector into a float column.

Please, let us know if this workaround works for you.

**Comment by ladodc** [comment] 2020-08-13 10:42
Hi Antonio, 
I have tried your solution. But I got another Exception.

> [E:onnxruntime:, sequential_executor.cc:309 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Identity node. Name:'Identity5' Status Message: C:\agent\_work\1\s\include\onnxruntime\core/framework/op_kernel.h:88 onnxruntime::OpKernelContext::Input Missing Input: Fehler

Please, take a look at my example. You can run it and you should get the same exception.
[TestCustomMapping.zip](https://github.com/dotnet/machinelearning/files/5068541/TestCustomMapping.zip)

What I am doing wrong?

**Comment by antoniovs1029** [comment] 2020-08-13 22:59
I haven't ran it. But have you tried adding "Fehler" to your list of inputColumnNames?
I don't think it's necessary, since you're not asking for Fehler.output on your outputs, but simply looking at your exception message and at your code, it's the first thing that comes to my mind. I'll later try take a closer look to this.

**Comment by ladodc** [comment] 2020-08-14 05:41
You are right. Thanks. I have looked at input schema, where the column "Fehler" was involved. Input columns on ApplayONNXModel I haven´t seen.  
But anyway why ApplyONNXModel needs inputColumnNames. If I use ONNXRuntime InferenceSession you can read input schema like this:
```
using (var session = new InferenceSession(this.ModelFile))
            {                
                var inputMeta = session.InputMetadata;
```
I think ApplyONNXModel use intern ONNXRuntime library also.

**Comment by antoniovs1029** [comment] 2020-08-15 06:17
Glad to hear the problem is solved.

Yes, OnnxTransformer is pretty much a wrapper around OnnxRuntime. Also, please notice that there are several `ApplyOnnxModel` overloads:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.onnxcatalog.applyonnxmodel?view=ml-dotnet

Many of them don't require you to provide the input names, and in these cases OnnxTransformer actually infers the names directly from your model.

-----

Since your original issue with using `Evaluate` with Onnx has been resolved, I'll close this now.

**Closed by antoniovs1029** 2020-08-15 06:17 UTC
Labels: P3, onnx, question
