### ISSUE TITLE
How to Add Date column in the Input Class

### ISSUE THREAD

**Issue by asif48** [dotnet/machinelearning#4980] opened 2020-03-28 10:21 UTC
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:  VS 2019

### Issue

- **What did you do?** I tried to modify the TaxiFairExample ; Just copied the  code and include few fields 
1) Date 
2) Punctured 
to predict whether the taxi would likely to punctured in the coming date.

- **What happened?**
When I included Date column in the class and try to debug the code ; following errors rises

System.ArgumentOutOfRangeException: 'Could not determine an IDataView type for member Date
Parameter name: rawType'

![IDataView type for member Date](https://user-images.githubusercontent.com/7997380/77820851-31a79f00-7107-11ea-87d1-e6576edc073e.png)

- **What did you expect?**
I just expect to predict whether the Taxi is likely to puncture or not in the given date 
### Source code / logs

```
 public class ItemStock
    {
        [Column("0")]
        public string CarID;

        [Column("1")]
        public float LocID;

        [Column("2")]
        public DateTime Date;

        [Column("3")]
        public float Punctured;
    }

    public class itemStockQtyPrediction
    {
        [ColumnName("Score")]
        public float Punctured;
    }
```
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by antoniovs1029** [comment] 2020-03-31 05:01
Hi. I am not sure which `TaxiFairExample` are you referring to. Can you please share your code including all the changes you made an a sample dataset to reproduce the issue?

In general, DateTime columns should work similarly to other types. For instance, the following snippet works without any problem:

```C#
using System;
using Microsoft.ML;

namespace Bugs
{
    class Input
    {
        public DateTime date;
        public string label;
        public float num;
    }

    class Program
    {
        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext(1);
            var dataList = new Input[] {
                new Input { date = new DateTime(1970, 1, 1), label = "A", num = 2.0f },
                new Input { date = new DateTime(1970, 1, 3), label = "A", num = float.NaN },
                new Input { date = new DateTime(1970, 1, 5), label = "A", num = 5.0f },
                new Input { date = new DateTime(1970, 1, 7), label = "A", num = float.NaN },
                new Input { date = new DateTime(1970, 1, 8), label = "A", num = float.NaN }
            };

            var data = mlContext.Data.LoadFromEnumerable(dataList);
            var preview = data.Preview();
        }
    }
}
```

**Comment by antoniovs1029** [comment] 2020-03-31 05:08
Other samples that include working with DateTime columns are the following:
[DataViewEnumerable Sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/DataViewEnumerable.cs)

[ConvertTypeMulticolumn Sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/ConvertTypeMultiColumn.cs)

[DateTime Featurizer Sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Featurizers/DateTimeTransformer.cs)

**Comment by asif48** [comment] 2020-04-09 12:21
Hi antoniovs1029 !
Apologizing for being late...Can you share the link of Bug Detection solution or any that has date involvement in the processing...

Inconvenience Regretted...

**Comment by antoniovs1029** [comment] 2020-04-09 17:20
I am still not sure what `TaxiFairExample` are you referring to. Can you please share your code and sample dataset to know what your use case is?

On the other hand, if you want to predict if a Taxi is likely to puncture or not in a _future_ date then you might want to take a look to the Forcasting samples. I believe those samples don't use DateTime though, so it might be useful for your case:

[Forcasting with Regression](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales)

[Forcasting with TimeSeries](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales)

**Comment by asif48** [comment] 2020-04-09 17:41
I have used these examples, the accuracy of Regression is somewhat acceptable but the accuracy of Time Series is quite vague. I have posted question regarding its accuracy here

https://github.com/dotnet/machinelearning-samples/issues/799

I would be glad if you can reply to this thread.
Thanking for your cooperation!

**Comment by antoniovs1029** [comment] 2020-04-09 17:47
In the meantime, is your original question on how to use DateTime columns as input resolved?

**Comment by asif48** [comment] 2020-04-09 17:48
no not resolved...I am trying to find the code (its a week before I worked at it)...I will let you know...

**Comment by asif48** [comment] 2020-04-09 19:10
Hi antoniovs1029 ...
The solution was not TaxiFairExample instead it was  [MLNetSotck](https://www.codeproject.com/Articles/1256360/Getting-Started-with-Machine-Learning-DotNet-ML-NE) (My apologizing plz)...

The csv to train the model is as below. (Car got punctured on alternate days of the month on a location 1)
![CarCSV](https://user-images.githubusercontent.com/7997380/78930884-43515500-7abe-11ea-97f2-3fa6d4331140.png)

The prediction class has the following values :

![PredictionClass](https://user-images.githubusercontent.com/7997380/78931315-3123e680-7abf-11ea-8917-f3eb7679a4a6.png)
 
The error I got is as below: (This error is quite different from the one I posted in my first post might be because I changed the format of the date) 

![Datetime exception](https://user-images.githubusercontent.com/7997380/78931398-587ab380-7abf-11ea-8627-e593befa5ccd.png)

Plz help...

**Comment by antoniovs1029** [comment] 2020-04-09 19:25
Can you please send a .zip containing the model and sample dataset so I can see more info, such as how you're loading the data, what kind of trainer are you using and the like?

**Comment by asif48** [comment] 2020-04-09 19:30
yes sure...
but I dont know to upload a zip to github...can you send me ur email...?

**Comment by antoniovs1029** [comment] 2020-04-09 19:31
you can simply drag and drop the file inside the comment text box in github, or you can upload it elsewhere and share the link in here 😄

**Comment by asif48** [comment] 2020-04-09 19:39
Thanks ...

Meanwhile I have done one change in the attached project ...I have converted DateTime to string and now it has started to predict the result. The train data has the Punctured value in the form of 0 and 1 but the prediction is 0.5 (ceiling function will not work)...

I need the result in the form of 0 and 1.

[MLNETCar.zip](https://github.com/dotnet/machinelearning/files/4458243/MLNETCar.zip)

**Comment by asif48** [comment] 2020-04-12 10:40
antoniovs1029 if you are there?

**Comment by antoniovs1029** [comment] 2020-04-16 02:10
Hi, @asif48

So I took a look into your code, and I noticed that you're using ML.NET version 0.4.0. We don't advice using ML.NET's versions that were released before version 1; in general, there were different bugs, and the API was pretty unstable at the time, and it changed a lot before the realease of version 1. So please, use a version that is equal or greater than version 1 (ideally, we'll always recommend using the latest version, which is now 1.5.0-preview2). Notice that after the release of v1.0, the API has been very stable, and any code you create after it should still be executable with newer versions of ML.NET. Notice as well that code that was created with versions of ML.NET lower than 1.0, won't be able to run with ML.NET versions >= 1.0.

I have taken the liberty to take your code, simplify it, and update it to ML.NET version 1.5.

Notice that to solve the exception you got on your last post ("Column 'Features' has invalid source types") I had to actually use OneHotEncoding on input columns DateTime and CarID. In general you can't have a features vector that has different types such as 'string' and 'float'... OneHotEncoding maps the strings into numerical values that can be concatenated with the other floats.

Also, regarding your observation of getting "0.5" out of your regression model, notice that this is expected, since regression maps input to continuous values, and in your dataset your label "Punctured" has only values 1 and 0. I don't know what the "Punctured" label represents, but if it can only be "0" or "1" I would recommend using a Binary classification trainer instead of a regression one. Also, I would recommend doing some other preprocessing to your input feature, particullarly on your DateTime column, because reading it only as a "string" won't give you any good classifier. I will clear up your question on loading datetime columns on my next post.

Meanwhile, here is the updated version of your code:

```C#
using System;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace is4980myrepro
{
    public class ItemStock
    {
        [LoadColumn(0)]
        public string CarID;

        [LoadColumn(1)]
        public float LocID;

        [LoadColumn(2)]
        public string DateTime;

        [LoadColumn(3)]
        public float Punctured;
    }

    public class itemStockQtyPrediction
    {
        [ColumnName("Score")]
        public float PredictedPunctured;
    }

    class Program
    {
        static void Main(string[] args)
        {

            var TrainDataPath = @"C:\Users\anvelazq\Downloads\MLNETCar\MLNETCar\MLNETStock\Data\CarTrain.csv";
            var TestDataPath = @"C:\Users\anvelazq\Downloads\MLNETCar\MLNETCar\MLNETStock\Data\CarTest.csv";

            var mlContext = new MLContext();
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<ItemStock>(TrainDataPath, hasHeader: true, separatorChar: ',');
            IDataView testDataView = mlContext.Data.LoadFromTextFile<ItemStock>(TestDataPath, hasHeader: true, separatorChar: ',');

            var pipeline = mlContext.Transforms.CopyColumns("Label", "Punctured")
                .Append(mlContext.Transforms.Categorical.OneHotEncoding("DateTime", "DateTime"))
                .Append(mlContext.Transforms.Categorical.OneHotEncoding("CarID", "CarID"))
                .Append(mlContext.Transforms.Concatenate("Features", "CarID", "LocID", "DateTime"))
                .Append(mlContext.Regression.Trainers.FastTree());

            var transformer = pipeline.Fit(trainingDataView);

            var metrics = mlContext.Regression.Evaluate(transformer.Transform(testDataView), labelColumnName: "Label", scoreColumnName: "Score");

            Console.WriteLine($"Rms = {metrics.RootMeanSquaredError}");

            Console.WriteLine($"RSquared = {metrics.RSquared}");

            var predictionEngine = mlContext.Model.CreatePredictionEngine<ItemStock, itemStockQtyPrediction>(transformer);

            Console.WriteLine(" ");
            Console.WriteLine("-------First Prediction Vale : ----------------");
            Console.WriteLine(" ");
            var stock1 = new ItemStock() { CarID = "c100", LocID = 1, DateTime = "1-Jan", Punctured = 0 };
            var prediction = predictionEngine.Predict(stock1);
            Console.WriteLine("Car ID  {0}", stock1.CarID);
            Console.WriteLine("Predicted Stock: {0} ", prediction.PredictedPunctured);
        }
    }
}
```

**Comment by antoniovs1029** [comment] 2020-04-16 02:12
Returning to your original issue (about loading DateTime columns from a .csv file). If I run your code as-is (with ML.NET version 0.4) I do get the exception you were getting. But I don't get that exception in ML.NET 1.5. So the following code will run with no exceptions:

```C#
    public class ItemStock
    {
        [LoadColumn(0)]
        public string CarID;

        [LoadColumn(1)]
        public float LocID;

        [LoadColumn(2)]
        public DateTime DateTime;

        [LoadColumn(3)]
        public float Punctured;
    }

    class Program
    {
        static void Main(string[] args)
        {

            var TrainDataPath = @"C:\Users\anvelazq\Downloads\MLNETCar\MLNETCar\MLNETStock\Data\CarTrain.csv";

            var mlContext = new MLContext();
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<ItemStock>(TrainDataPath, hasHeader: true, separatorChar: ',');
            var preview = trainingDataView.Preview(); // The DateTime column is loaded without throwing exceptions
        }
    }
```

(if you're not familiar with the "Preview" method, you simply need to add a breakpoint after it's called, and debug the code above, to see the contents of the dataView in the "preview" object).

Now, I noticed there are 2 different `CarTrain.csv` files in your project (one in `\MLNETCar\MLNETCar\MLNETStock\Data` and the other one in `\MLNETCar\MLNETCar\MLNETStock\bin\Debug\Data`). One has the DateTime column in format "1/1/2020", and the other has the format "1-Jan". The first one (with format dd/mm/yy) will work without problems with the code above. The second one will run the code above without throwing exceptions, but "1-Jan" will be mapped to a DateTime object with "1/1/2001" as date, "2-Jan" will be mapped to "1/1/2002", "3-Jan" to "1/1/2003" and so on.

Unfortunately you can't pass options to the LoadFromTextFile method telling it how to parse DateTime. So to solve that problem it will be necessary to load the DateTime column as an string and then use a `CustomMappingTransformer` to map those strings to DateTime objects with the correct dates as follows:

```C#
using System;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace is4980myrepro
{
    public class ItemStock
    {
        [LoadColumn(0)]
        public string CarID;

        [LoadColumn(1)]
        public float LocID;

        [LoadColumn(2)]
        public string DateTime;

        [LoadColumn(3)]
        public float Punctured;
    }

    public class CustomInput
    {
        public string DateTime;
    }

    public class CustomOutput
    {
        public DateTime DateTime;
    }

    class Program
    {
        static void Main(string[] args)
        {

            var TrainDataPath = @"C:\Users\anvelazq\Downloads\MLNETCar\MLNETCar\MLNETStock\bin\Debug\Data\CarTrain.csv";

            Action<CustomInput, CustomOutput> parseDateTime = (input, output) =>
            {
                output.DateTime = DateTime.ParseExact(input.DateTime, "d-MMM", null);
            };

            var mlContext = new MLContext();
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<ItemStock>(TrainDataPath, hasHeader: true, separatorChar: ',');
            var customTransformer = mlContext.Transforms.CustomMapping(parseDateTime, null).Fit(trainingDataView);
            IDataView parsedDataView = customTransformer.Transform(trainingDataView);
            var preview = parsedDataView.Preview(); // The DateTime column is loaded correctly even in format "1-Jan"
        }
    }
}
```
To learn more about the `CustomMappingTransformer` refer to https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.custommappingcatalog.custommapping?view=ml-dotnet

I will close this issue, since these two last code snippets should answer your question on how to load DateTime columns from CSV.

PS: Notice that in the last 2 snippets it will load the DateTime column as DateTime objects, so I don't think you'll be able to concatenate those into the Feature column (as i mentioned on my previous post, you might need to map those object into numbers). You can do this mapping using the CustomMappingTransformer above. I'd recommend only taking the "day" from the input DateTime string, and convert it into an int. But you might want to experiment with this and see how to map this to get better results in your prediction.

**Closed by antoniovs1029** 2020-04-16 02:12 UTC
Labels: P3, question
