### ISSUE TITLE
Taxi Fare value prediction tutorial ModelOutput does not have the prediction value property!

### ISSUE THREAD

**Issue by khteh** [dotnet/machinelearning#5522] opened 2020-12-02 06:05 UTC
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:
```
C:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  1.0.0-preview1-002702 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010046 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010050 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Issue

- **What did you do?**
I try to create a Value Prediction for taxi fare based on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/next
- **What happened?**
Generated `ModelOutput` class does not have the `fare_amount` property which is the predicted value. It only contains the `Score` property.
- **What did you expect?**
`ModelOutput` class should contain the `fare_amount` property which is the predicted taxi fare value.
### Source code / logs

No source code. It's very straight forward from following the tutorial steps and you will see it immediately at the `Coding` stage of the pipeline.

**Comment by mstfbl** [comment] 2020-12-15 17:59
Hi @khteh, thank you for opening this issue. There are multiple taxi fare value prediction samples in out [dotnet/machinelearning-samples](https://github.com/dotnet/machinelearning-samples/tree/master/samples) repo. Which exact taxi fare sample are you referring to where you're seeing this issue? Thanks.

**Comment by khteh** [comment] 2020-12-16 04:30
@mstfbl I provided the URL in the issue! The model is in the "Download the Taxi Fare dataset".

**Comment by mstfbl** [comment] 2020-12-16 11:51
@khteh You provided a link for our "Next steps" page, and not to the exact sample you're having an issue with. After looking through our examples, I assume you are seeing this issue in [this ](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Regression_TaxiFarePrediction)specific regression taxi fare prediction sample. I'm currently investigating this sample.

**Comment by mstfbl** [comment] 2020-12-16 16:18
@khteh There are three taxi fare prediction samples in dotnet/machinelearning-samples that I can see:

- [Regression_TaxiFarePrediction](https://github.com/dotnet/machinelearning-samples/blob/c3d984e790ad73c2d3c2e646290335c2a86dfc2a/samples/csharp/getting-started/Regression_TaxiFarePrediction/README.md)
- [Regression_AutoML](https://github.com/dotnet/machinelearning-samples/tree/2a86b9aac3af9c4eeab7655e7869f02132c0de57/samples/csharp/getting-started/Regression_AutoML)
- [AdvancedExperiment_AutoML](https://github.com/dotnet/machinelearning-samples/tree/5831bdd9bea8e42e1d3e4967486653a5df1abe4c/samples/csharp/getting-started/AdvancedExperiment_AutoML)

I have reviewed these three samples, and did not find any unexpected issues and/or missing taxi fare predictions. I can't help you more if you don't make it clear which sample and where exactly you're not seeing `fare_amount`. Thanks.

**Comment by jwood803** [comment] 2020-12-16 17:43
@mstfbl @khteh If I may, I believe I can help out with this issue.

My understanding is that the model output doesn't have a property called `fare_amount`. This is because we only supply the `fare_amount` in the input as the label. The model outputs its own property that is the `Score` property. You can definitely rename this to `FareAmount` or anything else that you'd like but in that case it will need the `[ColumnName("Score")]` attribute on it.

Feel free to correct my understanding, of course. 😄

**Comment by khteh** [comment] 2020-12-17 04:26
@jwood803 I don't think so. Isn't "label" a prediction target which is an output? What does "Score" mean in the output model? Why does the "Text classification" tutorial have the `label` property in the model output in addition to the "Score" property which is not used in that case?

**Comment by antoniovs1029** [comment] 2020-12-28 21:57
Hi, @khteh . In ML.NET it's common practice to name "Label" the column in your INPUT DataView from where your model is meant to take the ground truth, and which the model will try to predict. So "Label" isn't an output of the model. The outputs in ML.NET are typically named "Score" (for continuous values, like in regression), "PredictedLabel" (for discrete values, such as in Classification), "Probability" (for continuous values between 0 and 1 that represent a confidence in the PredictedLabel).

So as mentioned by @jwood803 , in all the docs that @mstfbl pointed above, the output of the model is located in the FareAmount property, as it has the `[ColumnName("Score")`. Notice that the 3 samples mentioned above, deal with a Regression problem.

**Comment by khteh** [comment] 2021-01-04 01:45
@antonfirsov The problem here is that in the text classification tutorial, there is `Prediction` property with attribute `[ColumnName("PredictedLabel")]` besides the `Score` property. However, in the taxi fare tutorial, there is only `Score` property.  So `Prediction` property value can be used as output of the application and I don't know what's the use of `Score` property in text classification! In addition, for your record, no, there is no `FareAmount` property in the taxi fare tutorial. There is only one `Score` property without any attribute at all!

Why is this issue closed!?!

/open

**Comment by antoniovs1029** [comment] 2021-01-05 03:42
The Taxi fare tutorials have this C# `FareAmount` property defined, with the `ColumnName` attribute renaming it to "Score". This means that internally in ML.NET the Score column in a `IDataView` will be mapped to the C# property `FareAmount` in the output of a `PredictionEngine`.

https://github.com/dotnet/machinelearning-samples/blob/c3d984e790ad73c2d3c2e646290335c2a86dfc2a/samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/DataStructures/TaxiTripFarePrediction.cs#L7-L8

I'm not sure which text classification tutorial you're referring to, but it might be this one (or similar to this one):

https://github.com/dotnet/machinelearning-samples/blob/c3d984e790ad73c2d3c2e646290335c2a86dfc2a/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/DataStructures/SentimentPrediction.cs#L10-L17

The output of this model is `Score`, `Probability` and `PredictedLabel`, because on this scenario the model is a binary classification model. In contrast, on the taxi fare scenario it's a regression model. As I mentioned [above](https://github.com/dotnet/machinelearning/issues/5522#issuecomment-751876787), different models have different outputs.

Please, close this issue if this answers your question.

**Comment by khteh** [comment] 2021-01-06 00:57
The text classification tutorial I followed is https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro and it doesn't have the `Probability` property at all as you mentioned.

The value prediction tutorial I followed is at the end of the https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro where I downloaded the `.tsv` from https://raw.githubusercontent.com/dotnet/machinelearning-samples/master/samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/Data/taxi-fare-train.csv and it doesn't have anything at all except the `Score` property without any attribute.

The tutorials do NOT have any reference to any source code repository. I just use the model builder and the `.tsv` provided / referenced by the tutorials.  Providing the source repositories in your answer doesn't help as I do NOT use the source code directly. The model builder does not generate code as expected!

**Comment by antoniovs1029** [comment] 2021-01-06 02:27
I see.

Can you share the output that you get from ModelBuilder with these input datasets, so that we can better explain?

Please notice that this github repository is for ML.NET (the source code library), and issues and questions about Model Builder (the Visual Studio extension) should go here:
https://github.com/dotnet/machinelearning-modelbuilder/issues

I'm tagging the ModelBuilder team so that they can move this issue to that repository: @LittleLittleCloud @briacht 
It seems to me this is a ModelBuilder issue in the sense that it's not clear to the user what's the output they're getting and how to relate it to the ML.NET concepts of Score and Predicted Label.

**Comment by khteh** [comment] 2021-01-06 02:31
Why don't you spend some time to validate what you have put up as tutorial against your claims? It's a boilerplate code and it only takes 10 minutes to see that.

**Comment by luisquintanilla** [comment] 2022-09-23 18:30
Closing this issue since there have been many changes to the tutorial / Model Builder since the date this was opened. 

@khteh please open a new issue if you still run into problems.

**Closed by luisquintanilla** 2022-09-23 18:30 UTC
Labels: documentation, need info, P3
