### ISSUE TITLE
LightGbm trainer fails in linux container

### ISSUE THREAD

**Issue by moreginger** [dotnet/machinelearning#4905] opened 2020-03-01 09:43 UTC
### System information

- mcr.microsoft.com/dotnet/core/aspnet:3.1
- Version: 3.1.1 

### Issue

- Created application using AutoML. LightGbm trainer was selected.
- Dockerized a webapp using mcr.microsoft.com/dotnet/core/aspnet:3.1 as base.
- Expected: It trains.
- Actual: Unable to load shared library 'lib_lightgbm' (see below).

As per https://github.com/dotnet/machinelearning/issues/4600 it appears that the trainer can be used if clang is present, for example:

```
RUN apt-get update && apt-get install -y \
    clang-3.9 \
 && rm -rf /var/lib/apt/lists/*
```

However this doesn't seem like a satisfactory solution as it adds about a gigabyte to the image size. Surely there is a better answer?

### Source code / logs

```
System.AggregateException: One or more errors occurred. (Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblib_lightgbm: cannot open shared object file: No such file or directory)
 ---> System.DllNotFoundException: Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblib_lightgbm: cannot open shared object file: No such file or directory
```

**Comment by LittleLittleCloud** [comment] 2020-03-20 19:52
Having the same issue
#### container
- mcr.microsoft.com/dotnet/core/sdk:2.1

**Comment by frank-dong-ms** [comment] 2020-05-20 20:44
> However this doesn't seem like a satisfactory solution as it adds about a gigabyte to the image size. Surely there is a better answer?

If you want to use LightGBM related training, clang is required. Please refer to https://github.com/dotnet/machinelearning/blob/master/docs/building/unix-instructions.md for more details. 
We don't enable install clang and other package by default (say if you don't need use LightGBM related training, you don't need to install clang and get your 1GB back), there is a discussion related for your reference: https://github.com/dotnet/machinelearning/issues/1282 
Eric make a very good point: I would vote against this because there are users who just want to build the repo, and use other bits that aren't LightGBM. Forcing them to install software that they aren't going to use isn't a great experience IMO.

**Comment by frank-dong-ms** [comment] 2020-05-20 20:45
I will close the issue for now as seems this is by design, if you have more concerns or suggestions, feel free to reopen and comment, thanks.

**Closed by frank-dong-ms** 2020-05-20 20:45 UTC
Labels: P1, bug, image, lightgbm, loadsave
