### ISSUE TITLE
CoreDump on LoadTensorFlowModel 

### ISSUE THREAD

**Issue by DanBrook** [dotnet/machinelearning#5213] opened 2020-06-07 09:19 UTC
### System information

- **Windows 10 pro/18362.836**:
- **.NET 4.7.2**: 

### Issue

- **Trying to load TensorFlow model tensorflow_inception_graph **
- **Illegal error**
- **model loading**

### Source code / logs
 Microsoft.ML.Transforms.TensorFlowModel tensorFlowModel = mlContext.Model.LoadTensorFlowModel(_inceptionTensorFlowModel);
Error occures on this line from microsoft manual. I have managed to load the model on my laptop and it works properly. When I have tried to run the same progect on my PC I had this error. Please help me to figure out wat is wrong. The problem is not in the code, becouse the same code works fine on the other machine. I have tried different versions of all libreries, but nothing helped.

PC Information:

Processor: Intel(R) Core i7 CPU Q740 1.73GHz 1.73GHz 
RAM: 6.00 Gb
x64

"WpfApplication2.exe" (CLR v4.0.30319: DefaultDomain). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: DefaultDomain). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\WpfApplication2.exe". Symbols loaded.
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x64\Microsoft.VisualStudio.DesignTools.WpfTap.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Xceed.Wpf.Toolkit.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Xceed.Wpf.AvalonDock.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Microsoft.ML.Data.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Microsoft.ML.Core.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Microsoft.ML.TensorFlow.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\v\Desktop\test\WpfApplication2\bin\Debug\Microsoft.ML.DataView.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\System.Collections.Immutable.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Microsoft.ML.ImageAnalytics.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Microsoft.ML.StandardTrainers.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Newtonsoft.Json.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\System.Memory.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\TensorFlow.NET.dll". 
"WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Google.Protobuf.dll". Symbols loaded.
Program "[6780] WpfApplication2.exe" exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.

**Comment by mstfbl** [comment] 2020-06-08 05:45
Hi @DanBrook,

Thank you for letting us know about this issue. I believe you're said you're able to successfully load the [Inception](C:\Users\mubal\Downloads\inception5h\tensorflow_inception_graph.pb) model on your laptop, but not on your desktop, with the following line, and obtain the following error, correct?

```csharp
string _inceptionTensorFlowModel = "PATH_TO_INCEPTION_V3_MODEL";
Microsoft.ML.Transforms.TensorFlowModel tensorFlowModel = mlContext.Model.LoadTensorFlowModel(_inceptionTensorFlowModel);
```

> "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\TensorFlow.NET.dll".
> "WpfApplication2.exe" (CLR v4.0.30319: WpfApplication2.exe). Loaded "C:\Users\MyPC\Desktop\test\WpfApplication2\bin\Debug\Google.Protobuf.dll". Symbols loaded.
> Program "[6780] WpfApplication2.exe" exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.

I have downloaded the inception model and successfully loaded it with the code above, so I was not able to reproduce your error.

I think this error is due to the differing setup on your laptop (working) and on your other machine (not working). Did you reference the correct reference the `SciSharp.TensorFlow.Redist` (training on CPU) or the `SciSharp.TensorFlow.Redist-Windows-GPU/SciSharp.TensorFlow.Redist-Linux-GPU` (training with GPU) NuGet packages on you other machine? The appropiate SciSharp TensorFlow package is necessary to bring in the appropriate TensorFlow native binaries.

In addition, what is the CPU in your laptop and on your other machine? After researching online, I found that the "WpfApplication2.exe illegal instruction" error you've provided may be due to the CPU on your other machine not supporting the `AVX` instruction set needed for TensorFlow.

**Comment by DanBrook** [comment] 2020-06-08 06:46
Hi, @mstfbl.
Thank you for your fast response. 
I have tried different combinations of different versions of redist and redist-Windows-GPU, but nothing helped.
The processor is : Intel(R) Core i7 CPU Q740 1.73GHz 1.73GHz
RAM: 6.00 Gb
x64.
As I have found from the internet, the AVC is for x86. Is there anything else I have missed?

**Comment by mstfbl** [comment] 2020-06-09 09:14
Hi @DanBrook,
The illegal instruction error you received may also hint at a C++ error on your laptop, and since this works on your main machine and my machine, this might indicate that your binaries may not be compiled correctly. Please clean and rebuild your solution, and make sure to delete `bin` and `obj` folders that are produced during builds and runs, and see if your solution works.

**Comment by mstfbl** [comment] 2020-06-10 07:04
Closing this issue as it is currently a non-fix issue.

**Closed by mstfbl** 2020-06-10 07:04 UTC
Labels: P3, need info, wontfix
