### ISSUE TITLE
CreateEnumerable - System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by rzechu** [dotnet/machinelearning#6257] opened 2022-07-21 11:55 UTC
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.7.1
 - .NET Version: Framework 4.8

**Describe the bug**
I am receiving Index out of range exception after trying convert transformedData into enumerable.
Same line of code works fine for same code but using method  - DetectIidSpike and its parameters

**To Reproduce**
Here's minimal working example https://github.com/dotnet/machinelearning/issues/6257#issuecomment-1196329421

```
    internal class LogsPrediction
    {
        //vector to hold alert,score,p-value values
        [VectorType(3)]
        public double[] Prediction { get; set; }
    }
```

Sent parameters
List<SourceRequestData> SourceDatas /*12025 records but filtered inside loop to 517 records*/, 
int windowSize = 6, 
int backAddWindowSize = 5,
 int lookaheadWindowSize = 5, 
int averagingWindowSize = 5,
 int judgementWindowSize = 6, 
double threshold = 0.01
```
public void DetectanAnomalyEnumerable(ref List<SourceRequestData> SourceDatas, int windowSize = 64, int backAddWindowSize = 5, int lookaheadWindowSize = 5, int averagingWindowSize = 5, int judgementWindowSize = 21, double threshold = 0.3)
        {
            try
            {
                var lambdaWorkAround = SourceDatas;
                var differentDefinitions = SourceDatas.Select(s => new { RdMethodType = s.Rd_MethodType, RdMethodID = s.Rd_MethodId }).Distinct().ToList();

                Parallel.ForEach(differentDefinitions, definitionID =>
                {
                    if (windowSize < 5)
                        return;

                    var dataToCheck = lambdaWorkAround.Where(w => w.Rd_MethodType == definitionID.RdMethodType && w.Rd_MethodId == definitionID.RdMethodID).OrderBy(o => o.Rd_ID).ToList();

                    IDataView dataView = mlContext.Data.LoadFromEnumerable<SourceRequestData>(dataToCheck);

                    lookaheadWindowSize = lookaheadWindowSize> windowSize  ? windowSize : lookaheadWindowSize;
                    averagingWindowSize = averagingWindowSize > windowSize  ? windowSize : averagingWindowSize;
                    judgementWindowSize = judgementWindowSize > windowSize  ? windowSize : judgementWindowSize;
                    threshold = threshold == 0 ? 0.01 : threshold;
                    threshold = threshold == 1 ? 0.99 : threshold;

                    var iidSpikeEstimator = mlContext.Transforms.DetectAnomalyBySrCnn(
                        outputColumnName: nameof(LogsPrediction.Prediction),
                        inputColumnName: nameof(SourceRequestData.Rd_DurationPerObject),
                        windowSize: windowSize,
                        backAddWindowSize: backAddWindowSize,
                        lookaheadWindowSize: lookaheadWindowSize,
                        averagingWindowSize: averagingWindowSize,
                        judgementWindowSize: judgementWindowSize,
                        threshold: threshold);
                    ITransformer iidSpikeTransform = iidSpikeEstimator.Fit(dataView);

                    IDataView transformedData = iidSpikeTransform.Transform(dataView);
//EXCEPTION HERE VVVVV
                    var predictions = mlContext.Data.CreateEnumerable<LogsPrediction>(transformedData, reuseRowObject: false).ToList();
//EXCEPTION HERE ^^^^^^^

                    var objectID = dataView.GetColumn<float>(nameof(SourceRequestData.Rd_ID)).ToArray();

                    for (int i = 0; i < predictions.Count(); i++)
                    {
                        if (predictions[i].Prediction[0] == 1)
                        {
                            var recordToChange = dataToCheck.Where(w => w.Rd_ID == objectID[i]).FirstOrDefault();
                            recordToChange.IsSpike = true;
                        }
                    }
                });
                SourceDatas = lambdaWorkAround;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
```

   at Microsoft.ML.Transforms.TimeSeries.SrCnnAnomalyDetectionBase.SrCnnAnomalyDetectionBaseCore.State.BackAdd(FixedSizeQueue`1 data)
   at Microsoft.ML.Transforms.TimeSeries.SrCnnAnomalyDetectionBase.SrCnnAnomalyDetectionBaseCore.State.SpectralResidual(Single input, FixedSizeQueue`1 data, VBufferEditor`1& result)
   at Microsoft.ML.Transforms.TimeSeries.SrCnnTransformBase`2.SrCnnStateBase.TransformCore(TInput& input, FixedSizeQueue`1 windowedBuffer, Int64 iteration, VBuffer`1& dst)
   at Microsoft.ML.Transforms.TimeSeries.SequentialTransformerBase`3.StateBase.Process(TInput& input, TOutput& output)
   at Microsoft.ML.Transforms.LambdaTransform.<>c__DisplayClass5_0`3.<CreateMap>b__0(TSrc src, TDst dst, TState state)
   at Microsoft.ML.Transforms.StatefulFilterTransform`3.Cursor.RunLambda(Boolean& isRowAccepted)
   at Microsoft.ML.Transforms.StatefulFilterTransform`3.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.TypedCursorable`1.RowCursorImplementation.MoveNext()
   at Microsoft.ML.PipeEngine`1.<RunPipe>d__2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MLNet.AnomalyDetection.<>c__DisplayClass5_1.<DetectanAnomalyEnumerable>b__1(<>f__AnonymousType0`2 definitionID) in C:\Users\xyz.zys\Desktop\ML_NET\Common\MLNet\AnomalyDetection.cs:line 178
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
```

**Expected behavior**
Enumerable object is returned (same code works for same method with DetectIidSpike and its own parameters)

**Comment by feiyun0112** [comment] 2022-07-24 14:02
Can you provide a minimal reproduction example

**Comment by rzechu** [comment] 2022-07-27 06:47
Here you are,



```
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GithubExample
{
    internal class Program
    {
        internal static MLContext mlContext;
        static void Main(string[] args)
        {
            mlContext = new MLContext();
            List<SourceRequestData> sourceRequests = new List<SourceRequestData>();
            sourceRequests.Add(new SourceRequestData() { ID = 1, Value = 1 });
            sourceRequests.Add(new SourceRequestData() { ID = 2, Value = 0 });
            sourceRequests.Add(new SourceRequestData() { ID = 3, Value = 100 });
            sourceRequests.Add(new SourceRequestData() { ID = 4, Value = 1 });
            sourceRequests.Add(new SourceRequestData() { ID = 5, Value = 5 });
            //sourceRequests.Add(new SourceRequestData() { ID = 6, Value = 1 });
            //sourceRequests.Add(new SourceRequestData() { ID = 7, Value = 40 });
            //sourceRequests.Add(new SourceRequestData() { ID = 8, Value = 60 });
            //sourceRequests.Add(new SourceRequestData() { ID = 9, Value = 20 });
            //sourceRequests.Add(new SourceRequestData() { ID = 10, Value = 1 });
            //sourceRequests.Add(new SourceRequestData() { ID = 11, Value = 0 });
            //sourceRequests.Add(new SourceRequestData() { ID = 12, Value = 1 });

            DetectanAnomalyEnumerable(ref sourceRequests,
                windowSize: 5,  // 64 no error   5 = error
                backAddWindowSize: 5,
                lookaheadWindowSize: 5,
                averagingWindowSize: 5,
                judgementWindowSize: 5,
                threshold: 0.5F);
        }

        internal class LogsPrediction
        {
            //vector to hold alert,score,p-value values
            [VectorType(3)]
            public double[] Prediction { get; set; }
        }

        internal class SourceRequestData
        {
            public int ID { get; set; }
            public float Value { get; set; }
            public bool IsAnomaly { get; set; }
        }

        public static void DetectanAnomalyEnumerable(ref List<SourceRequestData> SourceDatas, int windowSize = 64, int backAddWindowSize = 5, int lookaheadWindowSize = 5, int averagingWindowSize = 5, int judgementWindowSize = 21, double threshold = 0.3)
        {
            try
            {
                IDataView dataView = mlContext.Data.LoadFromEnumerable<SourceRequestData>(SourceDatas);

                lookaheadWindowSize = lookaheadWindowSize > windowSize ? windowSize : lookaheadWindowSize;
                averagingWindowSize = averagingWindowSize > windowSize ? windowSize : averagingWindowSize;
                judgementWindowSize = judgementWindowSize > windowSize ? windowSize : judgementWindowSize;
                threshold = threshold == 0 ? 0.01 : threshold;
                threshold = threshold == 1 ? 0.99 : threshold;

                var iidSpikeEstimator = mlContext.Transforms.DetectAnomalyBySrCnn(
                    outputColumnName: nameof(LogsPrediction.Prediction),
                    inputColumnName: nameof(SourceRequestData.Value),
                    windowSize: windowSize,
                    backAddWindowSize: backAddWindowSize,
                    lookaheadWindowSize: lookaheadWindowSize,
                    averagingWindowSize: averagingWindowSize,
                    judgementWindowSize: judgementWindowSize,
                    threshold: threshold);
                ITransformer iidSpikeTransform = iidSpikeEstimator.Fit(dataView);

                IDataView transformedData = iidSpikeTransform.Transform(dataView);
                //EXCEPTION HERE VVVVV
                var predictions = mlContext.Data.CreateEnumerable<LogsPrediction>(transformedData, reuseRowObject: false).ToList();
                //EXCEPTION HERE ^^^^^^^

                var preview = dataView.Preview();
                var objectID = dataView.GetColumn<int>(nameof(SourceRequestData.ID)).ToArray();
                for (int i = 0; i < predictions.Count(); i++)
                {
                    if (predictions[i].Prediction[0] == 1)
                    {
                        var recordToChange = SourceDatas.Where(w => w.ID == objectID[i]).FirstOrDefault();
                        recordToChange.IsAnomaly = true;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

**Comment by feiyun0112** [comment] 2022-07-28 04:47
https://github.com/dotnet/machinelearning/blob/0577957256c296fdea2deb6b6e00e7be9b458167/src/Microsoft.ML.TimeSeries/SrCnnAnomalyDetectionBase.cs#L245
@rzechu 
it caused by train dataset is small, or you can decrease lookaheadWindowSize

**Comment by rzechu** [comment] 2022-07-28 06:51
@feiyun0112 yes i finaly managet it regards to small data sets, but maybe there should be a human readable warning while setting parameter properties.
I dont remember accuratelly, but if I set lookheadWindowSize or other properties smaller than windowSize there's setter property exception indicating that value should be equal or less than windowSize or something like that.

"or you can decrease lookaheadWindowSize" - I see now but how anybody can know this?

**Comment by michaelgsharp** [comment] 2022-08-08 16:23
Closing this since its resolved. We will look at adding further warning/errors there.

**Closed by michaelgsharp** 2022-08-08 16:23 UTC
Labels: untriaged
