### ISSUE TITLE
Tokenizer for SentencePiece Unigram models

### ISSUE THREAD

**Issue by KasperNissen1997** [dotnet/machinelearning#7294] opened 2024-11-08 21:15 UTC
Hi all,
Is support planned for Tokenizers for SentencePiece models using the Unigram algorithm?
If I've checked correctly, I see that there's an Tokenizer implementation for SentencePiece models coming in the 4.0 release, but it seems to be limited to only supporting BPE models, in the form of `LlamaTokenizer`.

Specifically, I'd like to create a tokenizer for the Helsinki-NLP/opus-mt-xx-xx models from HuggingFace, but I am having difficulty creating tokenizers for those models.

**Comment by ericstj** [comment] 2024-11-17 21:50
It's in our backlog, duplicate of https://github.com/dotnet/machinelearning/issues/7186

**Closed by ericstj** 2024-11-17 21:50 UTC
Labels: untriaged, Tokenizers
