### ISSUE TITLE
AutoML - Better error message && stop inferring type for label column in regression && classification

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#5235] opened 2020-06-11 16:18 UTC
I have a dataset with sparse data and I can't perform value prediction. 

Can't upload dataset but I can share screen - Come Chat!

**Comment by LittleLittleCloud** [comment] 2020-06-12 16:47
The error is thrown because the dataset's label column has value like `<1.0` in the top 200 lines, which can't be parsed into float, so AutoML infers that column type as 'string' instead of 'single'.

It seems like an AutoML bug to me, when creating regression experiment, we don't have to infer label column purpose, which should always be single. Moreover, a better error message with hint can also be provided here to indicate user that label column might have text value.

**Comment by mstfbl** [comment] 2020-06-12 20:00
Closing this issue, as after chatting offline with @JakeRadMSFT and reading @LittleLittleCloud's comment, that this is not an ML.NET issue.

**Closed** 2020-06-12 20:00 UTC
Labels: wontfix
