### ISSUE TITLE
Assembly fails to load when running a pipeline from console app

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#1049] opened 2018-09-26 21:02 UTC
dotnet MML.dll train data="E:\dataset\day_0_sample.txt" loader=TextLoader{col=Label:R4:0 col=NumFeatures:R4:1-13 col=LowCardCat:TX:19,22,30,33 col=HighCardCat:TX:~} xf=CategoricalTransform{col=LowCardCat} xf=CategoricalHashTransform{col=HighCardCat bits=16} xf=MissingValueIndicatorTransform{col=NumFeatures} xf=Concat{ col=Features:NumFeatures,LowCardCat,HighCardCat } cache- tr=ap{iter=10} out=e:\data\model.zip

Could not load assembly E:\machinelearning\bin\AnyCPU.Release\Microsoft.ML.Console\netcoreapp2.1\CpuMathNative.dll:
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ML.Runtime.AssemblyLoadingUtils.LoadAssembly(IHostEnvironment env, String path) in E:\machinelearning\src\Common\AssemblyLoadingUtils.cs:line 207
Could not load assembly E:\machinelearning\bin\AnyCPU.Release\Microsoft.ML.Console\netcoreapp2.1\FactorizationMachineNative.dll:
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ML.Runtime.AssemblyLoadingUtils.LoadAssembly(IHostEnvironment env, String path) in E:\machinelearning\src\Common\AssemblyLoadingUtils.cs:line 207
Skipping assembly 'E:\machinelearning\bin\AnyCPU.Release\Microsoft.ML.Console\netcoreapp2.1\FastTreeNative.dll' because its name was filtered.
Could not load assembly E:\machinelearning\bin\AnyCPU.Release\Microsoft.ML.Console\netcoreapp2.1\LdaNative.dll:
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ML.Runtime.AssemblyLoadingUtils.LoadAssembly(IHostEnvironment env, String path) in E:\machinelearning\src\Common\AssemblyLoadingUtils.cs:line 207

I see these errors but I can still run the pipeline.

CC: @eerhardt

**Comment by eerhardt** [comment] 2018-09-26 21:56
Dupe of #1034

**Closed** 2018-09-26 22:02 UTC
