### ISSUE TITLE
Use runtime /dynamic created class object in prediction engine.

### ISSUE THREAD

**Issue by jigarhshah17** [dotnet/machinelearning#5476] opened 2020-11-05 10:10 UTC
### System information

- **OS version/distro**:
windows 7
- **.NET Version (eg., dotnet --info)**: 
>  .NET 4.6.1 ML.NET 1.5.2
### Issue

- **What did you do?**
Use runtime /dynamic created class object in prediction engine.

I want to predict different value, so I have created 25+ model
Using those models, I predict different values.
But each time I need to create class object with data and pass it to prediction engine to predict data 
So, every time I need to change in code. So, I take approach to create class object on run time/ Dynamic with data and pass it to prediction engine but it will generate exception. Colum name not found in schema

- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by harishsk** [comment] 2020-11-05 17:52
Hi @jigarhshah17 Can you please attach some sample source code that reproduces your problem?

**Comment by antoniovs1029** [comment] 2020-11-09 18:40
I will close this issue since we haven't received a repro of the scenario.

Also, please note that it isn't advised to dynamically crate types on runtime in order to pass them to a `PredictionEngine`, one of the problems that can happen from it, is the problem you're probably facing, that your model doesn't know how to handle the input, or get some exceptions if the type wasn't created correctly.

Note that it isn't necessary to use the `PredictionEngine` API to work with ML.NET, and in the case where you don't know your data schema in advance, instead of dynamically creating the input type, what is recommended is to use other of ML.NET APIs. Please, take a look into these to consider other options for your use case:

https://github.com/dotnet/machinelearning/issues/5459#issuecomment-718268303

https://github.com/dotnet/machinelearning/issues/5459#issuecomment-719750234

**Closed by antoniovs1029** 2020-11-09 18:40 UTC
