### ISSUE TITLE
TensorFlow support on Apple Silicon (M1, M2)

### ISSUE THREAD

**Issue by iharsuvorau** [dotnet/machinelearning#6526] opened 2022-12-19 16:42 UTC
**Is your feature request related to a problem? Please describe.**
I'm blocked by the current lack of support for TensorFlow on Apple Silicon. The limitation is mentioned at https://github.com/dotnet/machinelearning/blob/main/docs/project-docs/platform-limitations.md

**Describe the solution you'd like**
Use ML.NET on Apple Silicon chips.

**Describe alternatives you've considered**
As alternative, I don't use ML.NET.

**Comment by JakeRadMSFT** [comment] 2022-12-21 21:57
@iharsuvorau what scenario do you want to use M1/M2 for?

**Comment by iharsuvorau** [comment] 2022-12-22 08:34
> @iharsuvorau what scenario do you want to use M1/M2 for?

Hi, for image classification training and prediction for now.

**Comment by michaelgsharp** [comment] 2023-02-06 19:55
@iharsuvorau ML.Net itself is supported on the M1. The problem is that the Tensorflow nugets that we use do not support running on the M1 and that is something that we cannot control. If the maintainers of the tensorflow nuget added binaries for it then we would be able to add support as well.

Closing for now since there is nothing that we can do.

**Closed by michaelgsharp** 2023-02-06 19:55 UTC
Labels: enhancement, untriaged
