### ISSUE TITLE
Load Http

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#2181] opened 2019-01-18 00:03 UTC
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by Ivanidzo4ka** [comment] 2019-01-18 00:33
Looks like duplicate of https://github.com/dotnet/machinelearning/issues/2183

**Closed by Ivanidzo4ka** 2019-01-18 00:33 UTC
