### ISSUE TITLE
CL with Binary Logistic Regression

### ISSUE THREAD

**Issue by JulianusIV** [dotnet/machinelearning#6092] opened 2022-02-17 12:26 UTC
Hello,
I am currently testing some stuff with ML.NET, specifically Binary Logistic Regression, and trying to get CL to work on that.
To do that I found a few different articles, mainly [this one](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net), which I followed as closely as the algorithm allowed.
However when trying to get the parameters from a loaded model, and matching that to ``LinearRegressionModelParameters``, it just returns ``null`` despite previously having data.

This is how I save my model and pipeline:
```cs
MLContext mLContext = new MLContext();

var dataPrepEstimator = mLContext.Transforms.Text.FeaturizeText(inputColumnName: @"comment_text", outputColumnName: @"comment_text")
  .Append(mLContext.Transforms.Concatenate(@"Features", new[] { @"comment_text" }))
  .Append(mLContext.Transforms.NormalizeMinMax(@"Features", @"Features"));

var _data = GetData(mLContext);

var transformer = dataPrepEstimator.Fit(_data);

var lbfgs = mLContext.BinaryClassification.Trainers.LbfgsLogisticRegression("toxic", "Features");

var transformedData = transformer.Transform(_data);

var trainedModel = lbfgs.Fit(transformedData);

mLContext.Model.Save(transformer, _data.Schema, "data_prep_pipeline.zip");
mLContext.Model.Save(trainedModel, _data.Schema, "model.zip");
```

And this is how I load them again:
```cs
var dataPrepPipeline = mLContext.Model.Load("data_prep_pipeline.zip", out _);
var _trainedModel = mLContext.Model.Load("model.zip", out _);

//This next line assigns a object of type Microsoft.ML.Calibrators.ParameterMixingCalibratedModelParameters<Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.Calibrators.PlattCalibrator> to originalParams (according to the debugger)
var originalParams = ((ISingleFeaturePredictionTransformer<object>)_trainedModel).Model;
//this next line just results in originalParamsAsLMP being null
var originalParamsAsLMP = originalParams as LinearModelParameters;

var newData = GetData(mLContext);

var transformedNewData = dataPrepPipeline.Transform(newData);

var retrainedModel = mLContext.BinaryClassification.Trainers.LbfgsLogisticRegression("toxic", "Features").Fit(transformedNewData, originalParamsAsLMP);
```

I have seen in the article I mentioned that the algorithms have different parameter outputs, but cant seem to find the correct one for ``LbfgsLogisticRegression`` 
only thing I found was the one I am currently using, which doesn't work for me, so it seems like I either missed something, or made a mistake in my implementation. Can anyone help me with this?

**Comment by michaelgsharp** [comment] 2022-02-18 04:43
Without more info I'm not entirely sure, but I believe the issue is that you need to change the `as LinearModelParameters` to `as LinearBinaryModelParameters` (found in Microsoft.ML.Trainers.LinearBinaryModelParameters).

Try that out and let me know what happens.

**Comment by JulianusIV** [comment] 2022-02-18 07:45
> Without more info I'm not entirely sure, but I believe the issue is that you need to change the `as LinearModelParameters` to `as LinearBinaryModelParameters` (found in Microsoft.ML.Trainers.LinearBinaryModelParameters).
> 
> Try that out and let me know what happens.

Thank you for the fast response.
I believe I had tested it with that parameter class, and it didn't work, but will try again as soon as I am home today

**Comment by JulianusIV** [comment] 2022-02-18 17:28
@michaelgsharp I have tried the same thing as before, just with ``as LinearBinaryModelParameters``, but as you can see here
![grafik](https://user-images.githubusercontent.com/65790187/154732342-4ed23fae-70bd-49cc-afc2-1885b956f8ef.png)
and as was pretty much predictable by the inheritance of that class:
![grafik](https://user-images.githubusercontent.com/65790187/154732450-3aeb1e45-eb53-43d4-b23c-3a0761613eca.png)
this sadly didn't work

**Comment by JulianusIV** [comment] 2022-03-04 17:47
Hello, 
is there any update on this? I hate to have to annoy someone, but I have to have a project on hold until this can be resolved.
If you can't tell me what exactly would be used in my example, could you instead point me towards another example for CL with Binary Classification?

**Comment by michaelgsharp** [comment] 2022-03-08 23:51
Can you share a small sample data set? You already uploaded the code, and if you share a small dataset I can take a more indepth look at it probably tomorrow.

**Comment by JulianusIV** [comment] 2022-03-09 07:55
Here are some of the rows of the dataset i use (i had to delete some, due to newlines in the comment text, which is the reason I use Sql Server as a datasource).
The dataset itself is from [this old kaggle challenge](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data).

In the modelbuilder gui I set everything but ``comment_text`` and ``toxic`` to ignore.

id | comment_text | toxic | severe_toxic | obscene | threat | insult | identity_hate
--- | --- | --- | --- | --- | --- | --- | ---
2 | D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC) | 0 | 0 | 0 | 0 | 0 | 0
3 | Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info. | 0 | 0 | 0 | 0 | 0 | 0
5 | You, sir, are my hero. Any chance you remember what page that's on? | 0 | 0 | 0 | 0 | 0 | 0
7 | COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK | 1 | 1 | 1 | 0 | 1 | 0
8 | Your vandalism to the Matt Shirvington article has been reverted.  Please don't do it again, or you will be banned. | 0 | 0 | 0 | 0 | 0 | 0
9 | Sorry if the word 'nonsense' was offensive to you. Anyway, I'm not intending to write anything in the article(wow they would jump on me for vandalism), I'm merely requesting that it be more encyclopedic so one can use it for school as a reference. I have been to the selective breeding page but it's almost a stub. It points to 'animal breeding' which is a short messy article that gives you no info. There must be someone around with expertise in eugenics? 93.161.107.169 | 0 | 0 | 0 | 0 | 0 | 0
10 | alignment on this subject and which are contrary to those of DuLithgow | 0 | 0 | 0 | 0 | 0 | 0
15 | Oh, and the girl above started her arguments with me. She stuck her nose where it doesn't belong. I believe the argument was between me and Yvesnimmo. But like I said, the situation was settled and I apologized. Thanks, | 0 | 0 | 0 | 0 | 0 | 0

**Comment by michaelgsharp** [comment] 2022-03-10 03:07
Alright, I was able to get it working. I had to change it to this:
```
var originalParamsAsLMP = (originalParams as CalibratedModelParametersBase).SubModel as LinearModelParameters;
```
Test that and let me know if it works for you.

@luisquintanilla this is an issue with the clarity of the docs. Retraining LbfgsLogisticRegression takes in a LinearModelParameters, so it is reasonable to expect people will think thats what you should cast the model as. In this case because the model is calibrated you have to first cast it as that type and then get the SubModel out. I think we should add instructions for this case into the docs (though I am not sure exactly which trainers have this issue or where would be the best place to put it).

**Comment by JulianusIV** [comment] 2022-03-11 13:10
This seems to work, thank you a lot for your help :D

**Comment by luisquintanilla** [comment] 2022-03-15 17:04
> Alright, I was able to get it working. I had to change it to this:
> 
> ```
> var originalParamsAsLMP = (originalParams as CalibratedModelParametersBase).SubModel as LinearModelParameters;
> ```
> 
> Test that and let me know if it works for you.
> 
> @luisquintanilla this is an issue with the clarity of the docs. Retraining LbfgsLogisticRegression takes in a LinearModelParameters, so it is reasonable to expect people will think thats what you should cast the model as. In this case because the model is calibrated you have to first cast it as that type and then get the SubModel out. I think we should add instructions for this case into the docs (though I am not sure exactly which trainers have this issue or where would be the best place to put it).

I can make a note in the article referenced by @JulianusIV this is the case.

**Comment by michaelgsharp** [comment] 2022-03-18 20:10
Sounds good. I'll go ahead and close this issue then since you are tracking it elsewhere.

**Closed by michaelgsharp** 2022-03-18 20:10 UTC
Labels: documentation, P3
