### ISSUE TITLE
Make Key types consistent.

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#3529] opened 2019-04-23 18:05 UTC
It seems in transformers we have used [Key](link) type and in Trainers we have used [key](link) type. Make it consistent everywhere by using [Key](link) type everywhere. 

CC: @Ivanidzo4ka  @shmoradims @natke

**Comment by Ivanidzo4ka** [comment] 2019-04-24 04:15
>[11:01 AM] Shahab Moradi
    if you have time after closing all your PRs, change all to 'key'
​[11:02 AM] Shahab Moradi
    agree?

I think Shahab wanted to have lower case, not upper case.

**Comment by codemzs** [comment] 2019-04-24 04:20
Capital case is consistent with other types like System.Single, etc. what is important is we chose one convention and be consistent. My memory is we had a conference call and we decided to make it capital case.

**Comment by Ivanidzo4ka** [comment] 2019-04-24 16:30
Well, we there is `byte`, `int`, `enum`, `string`, `float`.
Not what I'm against capital case, I'm all hands for it, but as you can see above, we chose to have lower case. At least that's what I have in my logs. Did you had separate call after that?

**Comment by codemzs** [comment] 2019-04-24 16:32
In xref you use their UIDs and what are those? Do they begin with lower case or uppercase?

**Comment by Ivanidzo4ka** [comment] 2019-04-24 16:42
I personally think about `byte` as C# reference word which hides System.Byte behind. You can look on `key` which hides `KeyDataViewType` same way.

Again, I'm not rooting for specific case. All I'm saying is we had person who made a call to make them lower case, and you making them upper case.
I made/postpone changes in my PR's based on that call.
Now you have issue which state opposite.
All I'm asking is why it's opposite to what internally discussed?

**Comment by TomFinley** [comment] 2019-04-24 17:56
Referring to System.Single has nothing to do with this issue at all. The issue is far simpler than that. We have a bit of text, we've composed a natural sentence which refers to this concept as referring to values of keys with lower-case "key," as we do everywhere else [even in the earliest `IDataView` documentation](https://github.com/dotnet/machinelearning/blob/master/docs/code/IDataViewDesignPrinciples.md#key-types. We don't capitalize things like "key values" and "key types" and whatnot any more than we do "vector" in "vector valued-column."

The issue with `SIngle` is just that, it is literally in text referring to a type with the exact name `Single`. Which is not the case here. We have a prose sentence that happens to mention key values, and for more context we have a link (from what I've seen) on the word `"key"` to link to this other bit of documentation. That doesn't mean that every time we happen to form a link to somewhere else in our documentation, that the text of the link somehow [Must Now Be Capitalized Just Because It's In A Link](https://github.com/dotnet/machinelearning/issues/3529).

Now, if we had been talking specifically about, say, not vectors but `VBuffer`, and not keys as a general concept but specifically `KeyDataViewType`, obviously it is correct to capitalize those. But that's not what we're talking about. We're talking about whether in prose we just as a matter of course capitalization of words is appropriate, and that's more a question of what is correct in English.

So, do not capitalize "key" or "vector" just by itself please. The fact that there's a link to somewhere else doesn't mean that capitalization automatically applies.

**Closed** 2019-04-24 20:47 UTC
Labels: Bug Bash, documentation
