### ISSUE TITLE
ONNX Exporter Needs Examples

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1890] opened 2018-12-17 17:01 UTC
As title. We currently don't have a user-facing example.

**Comment by bartczernicki** [comment] 2019-02-26 02:35
I found an ONNX loading example here:
https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/OnnxTransform.cs

Might be good to move a valid example to the Cookbook as well as the ML.NET Model Library VS Project.  

Most ML libraries include some kind of check on capabilities.  For example, AutoMLConfig in our Automated ML has a simple method to check what valid performance metrics are a valid parameter: azureml.train.automl.utilities.get_primary_metrics(task)  In R, the mlr package support over 50+ classification algorithms with all different config/hyperparameter settings.  They have similar methods like this too.

This should be extended into: ONNX model export, model weights, FCC explainability etc. and other areas where unless the developer is in the weeds of the API and looking at the interfaces...its hard to tell what you can do without hitting runtime errors.

**Comment by shmoradims** [comment] 2019-05-21 18:50
Closing as duplicate of #3143.

**Closed by shmoradims** 2019-05-21 18:50 UTC
Labels: documentation
