### ISSUE TITLE
Automl: feature importance for regression models 

### ISSUE THREAD

**Issue by nilimb2000** [dotnet/machinelearning#4196] opened 2019-09-09 20:05 UTC
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

How do i extract the feature importances for the regression models that automl builds. Something similar to automlexplainer in azure maybe?
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by famschopman** [comment] 2019-09-10 10:54
Related to https://github.com/dotnet/machinelearning/issues/3972

So far it appears this is not implemented for AutoML yet.

**Comment by antoniovs1029** [comment] 2020-06-18 18:34
This looks like a duplicate of #3972 .
The way to make it work with regression models for AutoML should be pretty much the same as to what is explained here: https://github.com/dotnet/machinelearning/issues/3972#issuecomment-638904032 .

**Closed by antoniovs1029** 2020-06-18 18:34 UTC
Labels: AutoML.NET, P2, enhancement
