### ISSUE TITLE
 Deprecate documentation topics migrated to docs.microsoft.com

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/machinelearning#1831] opened 2018-12-05 22:21 UTC
The ML.NET Cookbook and ML.NET High-Level Concepts documents have been migrated to docs.microsoft.com as agreed upon. The current documents need to be updated to point to the migrated ones.

**Comment by JRAlexander** [comment] 2018-12-05 22:30
@shauheen, I'll follow up offlline, as I just saw your email.  Thanks.

**Comment by shmoradims** [comment] 2019-05-21 19:22
@JRAlexander @shauheen , what did you guys end up deciding? Is this a duplicate of #1830?

**Comment by natke** [comment] 2019-06-04 17:29
We can close this. We are creating topics on docs.microsoft.com as needed, and if there is redundancy between the two sources, we can handle those on a case by case basis.

**Comment by shmoradims** [comment] 2019-06-04 18:47
Great. I'll close this uber issue.

**Closed by shmoradims** 2019-06-04 18:47 UTC
Labels: P1, documentation
