### ISSUE TITLE
I am working with the LDA functionality of ML.NET. How can I see the summary terms for a topic. I have the default 10 summary terms per topic set, but after fitting I cannot find the terms.

### ISSUE THREAD

**Issue by nukeandserve** [dotnet/machinelearning#4735] opened 2020-01-29 20:51 UTC
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by antoniovs1029** [comment] 2020-01-29 22:16
Hi @nukeandserve . May I ask how did you get the "default 10 summary terms per topic set" you are referring to? Thanks!

**Comment by justinormont** [comment] 2020-01-29 23:46
See https://github.com/dotnet/machinelearning/issues/4322

**Comment by najeeb-kazmi** [comment] 2020-01-30 22:21
Closing as this is a duplicate of #4322.

@nukeandserve please follow the discussion there.

**Closed by najeeb-kazmi** 2020-01-30 22:21 UTC
