### ISSUE TITLE
DateTime  ERROR

### ISSUE THREAD

**Issue by Alex-fbr** [dotnet/machinelearning#2989] opened 2019-03-16 09:22 UTC
### System information

- **OS version/distro**:  Windows 10 Home
- **.NET Version (eg., dotnet --info)**:  .net core 2.2.0

### Issue
I updated Nuget package from ML 0.8 to 0.11. I have a truble. 
My csv File contain:

SECID,CurrentDate,OpenPrice,FareClosePrice
LKOH,2019-01-01,4984.00,5007.00

### Source code / logs

  _textLoader = mlContext.Data.CreateTextLoader(
                separatorChar: ',',
                hasHeader: true,
                columns: new TextLoader.Column[]
                {
                    new TextLoader.Column("SECID", DataKind.String, 0),
                    new TextLoader.Column("CurrentDate", DataKind.DateTime, 1),
                    new TextLoader.Column("OpenPrice", DataKind.Double, 2),
                    new TextLoader.Column("FareClosePrice", DataKind.Double, 3)
                });

           IDataView dataView = _textLoader.Load(dataPath);
            var pipeline = mlContext.Transforms.CopyColumns("Label", "FareClosePrice")
                .Append(mlContext.Transforms.Categorical.OneHotEncoding("SECID"))
                .Append(mlContext.Transforms.Concatenate("Features", "SECID", "CurrentDate", "OpenPrice", "FareClosePrice"))
            .Append(mlContext.Regression.Trainers.FastTree());

// An error occurs here:  System.InvalidOperationException: "Column 'CurrentDate' has values of // DateTimewhich is not the same as earlier observed type of R4."

            var model = pipeline.Fit(dataView);

**Comment by singlis** [comment] 2019-03-18 19:00
Hi @Alex-fbr, 

Concatenate expects that all of the columns to be concatenated are of the same type. Since CurrentDate is of DateTime and not a float (R4), this generates the error.  Its interesting though that you get this error after upgrading to 0.11 as I would think this to also fail with 0.8. I can test this.

An alternative way to do this is to to break down the day, month year into separate columns and then concatenate those into your features. Our Forecast Model sample does something similiar:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopForecastModelsTrainer

Here is where the concatenate takes place:
https://github.com/dotnet/machinelearning-samples/blob/3cc7a9b881e2e75c409d6653b2719040edda2fc5/samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopForecastModelsTrainer/ProductModelHelper.cs#L42-L47

One thing to note in the sample is the data is in a different format with the month and year being in separate columns. This can either be done by pre-processing your data prior to consuming with ML.Net or you can use a CustomMapping transform to convert the data from DateTime to month, day and year. 

An example of the CustomMapping can be found here:
https://github.com/dotnet/machinelearning-samples/blob/3cc7a9b881e2e75c409d6653b2719040edda2fc5/samples/csharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.cs#L42

**Comment by singlis** [comment] 2019-03-27 14:51
@Alex-fbr  I am closing this issue. If you feel that its not resolved please re-open.

**Closed** 2019-03-27 14:52 UTC
