### ISSUE TITLE
[Bug/issue] Prediction Engine using TensorFlow model doesn't close the used image files?

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#3790] opened 2019-05-30 01:42 UTC
Looks like when I provide an image file to the prediction engine which is using a TensorFlow model, after predicting and getting the result, it never closes the image file and you cannot even delete those image files (in my case, those image files are temp files that I need to delete from the code)

Only when the app using the prediction engine is finished, then the image files are closed and I can delete them (manually). But that is not the desired behavior. 

Here's an app with a repro:
https://github.com/CESARDELATORRE/TensorFlowImageClassificationWebApp/tree/master/WebApp

**Comment by codemzs** [comment] 2019-05-30 02:02
Are you disposing the bitmap image object? Bitmap image object takes a write lock on images.

**Comment by yaeldekel** [comment] 2020-01-09 14:05
Closing the issue, it seems to be a duplicate of these:
#3630
#3327
#3306

**Closed by yaeldekel** 2020-01-09 14:05 UTC
