### ISSUE TITLE
Tensorflow exception triggered while loading model.

### ISSUE THREAD

**Issue by Nico8400** [dotnet/machinelearning#4651] opened 2020-01-13 21:05 UTC
I tried to train an image classification model from ML builder but it always crashes instantly with the following stack trace 
[20200113 - Stack trace.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4055732/20200113.-.Stack.trace.txt)

Operating System: windows

Any hint to solve this problem ?

**Comment by JakeRadMSFT** [comment] 2020-01-14 20:16
Transferring issue to ML.NET repo.

**Comment by JakeRadMSFT** [comment] 2020-01-14 20:17
@Nico8400, are you able to share the dataset you tried with?

**Comment by Nico8400** [comment] 2020-01-15 08:59
> @Nico8400, are you able to share the dataset you tried with?

I'm sorry but I absolutely cannot share the dataset.
I also tried with a dataset made of my wallpapers, with the same result. My original dataset contains .jpg,.jpeg, .png and static .gif files
Here is my wallpaper test dataset
[Google Drive](https://drive.google.com/open?id=1TrsCvSM5O1F1ehiNtFEa-UMUZec2Afd2)

**Comment by Lynx1820** [comment] 2020-01-17 19:49
@Nico8400 I'm unable to reproduce your crash. Are you able to share the code pipeline you use?

**Comment by Nico8400** [comment] 2020-01-17 21:56
@Lynx1820 Since I'm using the model builder everything is done without me touching anything.
How can I see the pipeline in that case ?
Also tried on another computer and had no problem.

**Comment by Lynx1820** [comment] 2020-01-17 23:48
@Nico8400 I can't reproduce the crash while using modelbuilder. Since you got it working in another computer, could you save the model and share the ModelBuilder.cs file? Some things that would be helpful to know: are you using a GPU? What Visual Studio version and .NET Core are you using?  Does your issue happen with any kind dataset or just the specific ones?

**Comment by Lynx1820** [comment] 2020-01-17 23:50
@codemzs have you encountered any similar issues before?

**Comment by codemzs** [comment] 2020-01-17 23:52
![image](https://user-images.githubusercontent.com/1211949/72653746-2c78e780-3941-11ea-9289-cbc2c44566a5.jpg)

This is not an issue on the API side as previously investigated by Brian. It seems to be on the model builder side.

**Comment by Nico8400** [comment] 2020-01-18 17:34
@Lynx1820 I'm not using a GPU.
`Microsoft Visual Studio Community 2019
Version 16.4.3
`
`Target .NET Core version 3.1`
The issue happens with every dataset I tested(including [flower images](http://download.tensorflow.org/example_images/flower_photos.tgz))
I will post the ModelBuilder.cs once my other computer has finished training the flower images

**Comment by Lynx1820** [comment] 2020-01-27 23:01
@Nico8400  Unfortunately, I was not able to replicate this error on my computer.

**Comment by frank-dong-ms** [comment] 2020-10-21 04:06
Close this issue now as we can't repro this issue on any of our dev box and there is nothing we can do from our end now, will reopen and investigate this issue if we have any more information can help us troubleshoot this issue, thanks.

**Closed by frank-dong-ms** 2020-10-21 04:06 UTC
Labels: P3, image
